package com.jabava.dao.salary;

import java.util.List;

import com.jabava.pojo.salary.EhrMonthlySalaryDetail;

public interface EhrMonthlySalaryDetailMapper {
	List<EhrMonthlySalaryDetail> selectByMonthlySalaryPersonId(Long monthlySalaryPersonId);
	
	List<EhrMonthlySalaryDetail> selectForSalarySlip(Long monthlySalaryPersonId);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_monthly_salary_detail
     *
     * @mbggenerated Wed Mar 30 10:55:05 CST 2016
     */
    int deleteByPrimaryKey(Long monthlySalaryDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_monthly_salary_detail
     *
     * @mbggenerated Wed Mar 30 10:55:05 CST 2016
     */
    int insert(EhrMonthlySalaryDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_monthly_salary_detail
     *
     * @mbggenerated Wed Mar 30 10:55:05 CST 2016
     */
    int insertSelective(EhrMonthlySalaryDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_monthly_salary_detail
     *
     * @mbggenerated Wed Mar 30 10:55:05 CST 2016
     */
    EhrMonthlySalaryDetail selectByPrimaryKey(Long monthlySalaryDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_monthly_salary_detail
     *
     * @mbggenerated Wed Mar 30 10:55:05 CST 2016
     */
    int updateByPrimaryKeySelective(EhrMonthlySalaryDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_monthly_salary_detail
     *
     * @mbggenerated Wed Mar 30 10:55:05 CST 2016
     */
    int updateByPrimaryKey(EhrMonthlySalaryDetail record);
}