package com.jabava.dao.salary;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.jabava.pojo.manage.EhrOrganization;
import com.jabava.pojo.salary.EhrMonthlySalary;

public interface EhrMonthlySalaryMapper {
	List<EhrMonthlySalary> listMonthlySalaryPage(Map<String, Object> params);
	
	EhrMonthlySalary selectById(@Param("companyId")Long companyId, @Param("monthlySalaryId")Long monthlySalaryId);
	
	EhrMonthlySalary selectByParam(Map<String,Object> params);
	
	Integer searchMaxVersion(Map<String,Object> params);
	
	Integer countValidByOrgList(@Param("usageFlag")Integer usageFlag, @Param("monthly")String monthly, @Param("orgList")List<EhrOrganization> orgList);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_monthly_salary
     *
     * @mbggenerated Wed Mar 30 10:55:05 CST 2016
     */
    int deleteByPrimaryKey(Long monthlySalaryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_monthly_salary
     *
     * @mbggenerated Wed Mar 30 10:55:05 CST 2016
     */
    int insert(EhrMonthlySalary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_monthly_salary
     *
     * @mbggenerated Wed Mar 30 10:55:05 CST 2016
     */
    int insertSelective(EhrMonthlySalary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_monthly_salary
     *
     * @mbggenerated Wed Mar 30 10:55:05 CST 2016
     */
    EhrMonthlySalary selectByPrimaryKey(Long monthlySalaryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_monthly_salary
     *
     * @mbggenerated Wed Mar 30 10:55:05 CST 2016
     */
    int updateByPrimaryKeySelective(EhrMonthlySalary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_monthly_salary
     *
     * @mbggenerated Wed Mar 30 10:55:05 CST 2016
     */
    int updateByPrimaryKey(EhrMonthlySalary record);
}