package com.jabava.dao.salary;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.jabava.pojo.salary.EhrMonthlySalaryPerson;

public interface EhrMonthlySalaryPersonMapper {
	Map<String,Object> getTaxHistory(Map<String,Object> params);
	
	List<EhrMonthlySalaryPerson> selectByMonthlySalaryIdPage(Map<String,Object> params);
	
	List<Map<String,Object>> selectByMonthlySalaryId(Long monthlySalaryId);
	
	List<Map<String,Object>> listPayoffHistoryPage(Map<String,Object> params);
	
	Map<String, Object> queryByCertIdAndMonth(@Param("cardId")String cardId, @Param("month")String month);
	
	List<Map<String, Object>> queryPersonsForSalarySlip(Map<String,Object> params);
	
	int updateSendStatus(@Param("monthlySalaryPersonId")Long monthlySalaryPersonId, @Param("sendStatus")Integer sendStatus);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_monthly_salary_person
     *
     * @mbggenerated Wed Mar 30 10:55:05 CST 2016
     */
    int deleteByPrimaryKey(Long monthlySalaryPersonId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_monthly_salary_person
     *
     * @mbggenerated Wed Mar 30 10:55:05 CST 2016
     */
    int insert(EhrMonthlySalaryPerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_monthly_salary_person
     *
     * @mbggenerated Wed Mar 30 10:55:05 CST 2016
     */
    int insertSelective(EhrMonthlySalaryPerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_monthly_salary_person
     *
     * @mbggenerated Wed Mar 30 10:55:05 CST 2016
     */
    EhrMonthlySalaryPerson selectByPrimaryKey(Long monthlySalaryPersonId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_monthly_salary_person
     *
     * @mbggenerated Wed Mar 30 10:55:05 CST 2016
     */
    int updateByPrimaryKeySelective(EhrMonthlySalaryPerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_monthly_salary_person
     *
     * @mbggenerated Wed Mar 30 10:55:05 CST 2016
     */
    int updateByPrimaryKey(EhrMonthlySalaryPerson record);
}