package com.jabava.dao.salary;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.jabava.pojo.salary.EhrSalaryChangeDef;

public interface EhrSalaryChangeDefMapper {
	
	List<EhrSalaryChangeDef> queryByCompanyId(Long companyId);
	
	EhrSalaryChangeDef selectByName(@Param("companyId")Long companyId, @Param("name")String name);
	
	int logicDeleteById(@Param("companyId")Long companyId, @Param("salaryChangeDefId")Long salaryChangeDefId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ehr_salary_change_def
	 * @mbggenerated  Fri Mar 18 15:43:14 CST 2016
	 */
	int deleteByPrimaryKey(Long salaryChangeDefId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ehr_salary_change_def
	 * @mbggenerated  Fri Mar 18 15:43:14 CST 2016
	 */
	int insert(EhrSalaryChangeDef record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ehr_salary_change_def
	 * @mbggenerated  Fri Mar 18 15:43:14 CST 2016
	 */
	int insertSelective(EhrSalaryChangeDef record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ehr_salary_change_def
	 * @mbggenerated  Fri Mar 18 15:43:14 CST 2016
	 */
	EhrSalaryChangeDef selectByPrimaryKey(Long salaryChangeDefId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ehr_salary_change_def
	 * @mbggenerated  Fri Mar 18 15:43:14 CST 2016
	 */
	int updateByPrimaryKeySelective(EhrSalaryChangeDef record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ehr_salary_change_def
	 * @mbggenerated  Fri Mar 18 15:43:14 CST 2016
	 */
	int updateByPrimaryKey(EhrSalaryChangeDef record);
}