package com.jabava.dao.salary;

import java.util.List;
import java.util.Map;

import com.jabava.pojo.salary.EhrSalaryDetail;

public interface EhrSalaryDetailMapper {
	List<EhrSalaryDetail> loadDetailList(Long salaryId);
	
	int deleteBySalaryId(Long salaryId);
	
	int updateByParam(Map<String,Object> params);
	
	int countBySalaryItem(Long salaryItemId);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_salary_detail
     *
     * @mbggenerated Thu Mar 24 09:48:32 CST 2016
     */
    int deleteByPrimaryKey(Long salaryDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_salary_detail
     *
     * @mbggenerated Thu Mar 24 09:48:32 CST 2016
     */
    int insert(EhrSalaryDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_salary_detail
     *
     * @mbggenerated Thu Mar 24 09:48:32 CST 2016
     */
    int insertSelective(EhrSalaryDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_salary_detail
     *
     * @mbggenerated Thu Mar 24 09:48:32 CST 2016
     */
    EhrSalaryDetail selectByPrimaryKey(Long salaryDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_salary_detail
     *
     * @mbggenerated Thu Mar 24 09:48:32 CST 2016
     */
    int updateByPrimaryKeySelective(EhrSalaryDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_salary_detail
     *
     * @mbggenerated Thu Mar 24 09:48:32 CST 2016
     */
    int updateByPrimaryKey(EhrSalaryDetail record);
}