package com.jabava.dao.salary;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.jabava.pojo.salary.EhrSalaryTemplate;

public interface EhrSalaryTemplateMapper {
	List<EhrSalaryTemplate> listSalaryTemplatePage(Map<String,Object> params);
	
	List<EhrSalaryTemplate> listSalaryTemplate(Long companyId);
	
	EhrSalaryTemplate selectByName(@Param("companyId")Long companyId, @Param("templateName")String templateName);
	
	int deleteById(@Param("companyId")Long companyId, @Param("salaryTemplateId")Long salaryTemplateId);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_salary_template
     *
     * @mbggenerated Wed Mar 23 10:07:46 CST 2016
     */
    int deleteByPrimaryKey(Long salaryTemplateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_salary_template
     *
     * @mbggenerated Wed Mar 23 10:07:46 CST 2016
     */
    int insert(EhrSalaryTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_salary_template
     *
     * @mbggenerated Wed Mar 23 10:07:46 CST 2016
     */
    int insertSelective(EhrSalaryTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_salary_template
     *
     * @mbggenerated Wed Mar 23 10:07:46 CST 2016
     */
    EhrSalaryTemplate selectByPrimaryKey(Long salaryTemplateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_salary_template
     *
     * @mbggenerated Wed Mar 23 10:07:46 CST 2016
     */
    int updateByPrimaryKeySelective(EhrSalaryTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_salary_template
     *
     * @mbggenerated Wed Mar 23 10:07:46 CST 2016
     */
    int updateByPrimaryKey(EhrSalaryTemplate record);
}