package com.jabava.dao.salary;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.jabava.pojo.salary.EhrSalaryChangeData;

public interface EhrSalaryChangeDataMapper {
	List<Map<String, Object>> listSalaryChangeDataPage(Map<String, Object> params);

	List<Map<String, Object>> listSalaryChangeData(Map<String, Object> params);
	
	int deleteByMonthAndDef(@Param("companyId")Long companyId, @Param("monthly")String monthly, 
			@Param("salaryChangeDefId")Long salaryChangeDefId);
	
	int deleteByDef(@Param("companyId")Long companyId, @Param("salaryChangeDefId")Long salaryChangeDefId);
	
	int deleteById(@Param("companyId")Long companyId, @Param("salaryChangeDataId")Long salaryChangeDataId);
	
	int updateByParam(Map<String,Object> params);
	
	EhrSalaryChangeData selectByDefAndPerson(@Param("salaryChangeDefId")Long salaryChangeDefId,
			@Param("personId")Long personId);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_salary_change_data
     *
     * @mbggenerated Mon Mar 28 15:09:45 CST 2016
     */
    int deleteByPrimaryKey(Long salaryChangeDataId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_salary_change_data
     *
     * @mbggenerated Mon Mar 28 15:09:45 CST 2016
     */
    int insert(EhrSalaryChangeData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_salary_change_data
     *
     * @mbggenerated Mon Mar 28 15:09:45 CST 2016
     */
    int insertSelective(EhrSalaryChangeData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_salary_change_data
     *
     * @mbggenerated Mon Mar 28 15:09:45 CST 2016
     */
    EhrSalaryChangeData selectByPrimaryKey(Long salaryChangeDataId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_salary_change_data
     *
     * @mbggenerated Mon Mar 28 15:09:45 CST 2016
     */
    int updateByPrimaryKeySelective(EhrSalaryChangeData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_salary_change_data
     *
     * @mbggenerated Mon Mar 28 15:09:45 CST 2016
     */
    int updateByPrimaryKey(EhrSalaryChangeData record);
}