package com.jabava.dao.salary;

import java.util.List;

import com.jabava.pojo.salary.EhrSalaryTemplateDetail;

public interface EhrSalaryTemplateDetailMapper {
	List<EhrSalaryTemplateDetail> loadDetailList(Long salaryTemplateId);
	
	int deleteByTemplateId(Long salaryTemplateId);
	
	int countBySalaryItem(Long salaryItemId);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_salary_template_detail
     *
     * @mbggenerated Wed Mar 23 10:07:46 CST 2016
     */
    int deleteByPrimaryKey(Long salaryTemplateDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_salary_template_detail
     *
     * @mbggenerated Wed Mar 23 10:07:46 CST 2016
     */
    int insert(EhrSalaryTemplateDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_salary_template_detail
     *
     * @mbggenerated Wed Mar 23 10:07:46 CST 2016
     */
    int insertSelective(EhrSalaryTemplateDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_salary_template_detail
     *
     * @mbggenerated Wed Mar 23 10:07:46 CST 2016
     */
    EhrSalaryTemplateDetail selectByPrimaryKey(Long salaryTemplateDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_salary_template_detail
     *
     * @mbggenerated Wed Mar 23 10:07:46 CST 2016
     */
    int updateByPrimaryKeySelective(EhrSalaryTemplateDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_salary_template_detail
     *
     * @mbggenerated Wed Mar 23 10:07:46 CST 2016
     */
    int updateByPrimaryKey(EhrSalaryTemplateDetail record);
}