package com.jabava.dao.salary;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.jabava.pojo.salary.EhrTaxRate;

public interface EhrTaxRateMapper {
	List<EhrTaxRate> listTaxRatePage(Map<String, Object> params);

	List<EhrTaxRate> listTaxRate(Long companyId);
	
	EhrTaxRate selectByName(@Param("companyId")Long companyId, @Param("taxRateName")String taxRateName);
	
	int deleteById(@Param("companyId")Long companyId, @Param("taxRateId")Long taxRateId);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_tax_rate
     *
     * @mbggenerated Tue Mar 22 15:39:29 CST 2016
     */
    int deleteByPrimaryKey(Long taxRateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_tax_rate
     *
     * @mbggenerated Tue Mar 22 15:39:29 CST 2016
     */
    int insert(EhrTaxRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_tax_rate
     *
     * @mbggenerated Tue Mar 22 15:39:29 CST 2016
     */
    int insertSelective(EhrTaxRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_tax_rate
     *
     * @mbggenerated Tue Mar 22 15:39:29 CST 2016
     */
    EhrTaxRate selectByPrimaryKey(Long taxRateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_tax_rate
     *
     * @mbggenerated Tue Mar 22 15:39:29 CST 2016
     */
    int updateByPrimaryKeySelective(EhrTaxRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_tax_rate
     *
     * @mbggenerated Tue Mar 22 15:39:29 CST 2016
     */
    int updateByPrimaryKey(EhrTaxRate record);
}