package com.jabava.pojo.hro.order;

import java.math.BigDecimal;
import java.util.Date;
/**
 * 订单非社保段表
 *
 * @version $Id: HsEmpOrdNsbDetailRec.java, 
 * v 0.1 2016年1月21日 下午6:54:37 
 * <pre>
 * @author steven.chen
 * @date 2016年1月21日 下午6:54:37 
 * </pre>
 */
public class HsEmpOrdNsbDetailRec {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_emp_ord_nsb_detail_rec.id
     *
     * @mbggenerated
     */
    private Long ordNsbRecId;
    private Long companyId;
     
    public Long getCompanyId() {
		return companyId;
	}

	public void setCompanyId(Long companyId) {
		this.companyId = companyId;
	}

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_emp_ord_nsb_detail_rec.order_record_id
     *
     * @mbggenerated
     */
    private Long orderRecordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_emp_ord_nsb_detail_rec.quotation_name
     *
     * @mbggenerated
     */
    private String quotationName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_emp_ord_nsb_detail_rec.offer_id
     *
     * @mbggenerated
     */
    private Long offerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_emp_ord_nsb_detail_rec.prod_name
     *
     * @mbggenerated
     */
    private String prodName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_emp_ord_nsb_detail_rec.item_id
     *
     * @mbggenerated
     */
    private Long itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_emp_ord_nsb_detail_rec.item_type
     *
     * @mbggenerated
     */
    private String itemType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_emp_ord_nsb_detail_rec.payment_start_month
     *
     * @mbggenerated
     */
    private String paymentStartMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_emp_ord_nsb_detail_rec.payment_satrt_day
     *
     * @mbggenerated
     */
    private String paymentSatrtDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_emp_ord_nsb_detail_rec.payment_end_month
     *
     * @mbggenerated
     */
    private String paymentEndMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_emp_ord_nsb_detail_rec.payment_end_day
     *
     * @mbggenerated
     */
    private String paymentEndDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_emp_ord_nsb_detail_rec.bill_start_month
     *
     * @mbggenerated
     */
    private String billStartMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_emp_ord_nsb_detail_rec.bill_end_month
     *
     * @mbggenerated
     */
    private String billEndMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_emp_ord_nsb_detail_rec.sum
     *
     * @mbggenerated
     */
    private BigDecimal sum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_emp_ord_nsb_detail_rec.order_index
     *
     * @mbggenerated
     */
    private Integer orderIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_emp_ord_nsb_detail_rec.bill_template_id
     *
     * @mbggenerated
     */
    private Long billTemplateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_emp_ord_nsb_detail_rec.create_user_id
     *
     * @mbggenerated
     */
    private Long createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_emp_ord_nsb_detail_rec.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_emp_ord_nsb_detail_rec.update_user_id
     *
     * @mbggenerated
     */
    private Long updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_emp_ord_nsb_detail_rec.update_date
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_emp_ord_nsb_detail_rec.is_deleted
     *
     * @mbggenerated
     */
    private Integer isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hs_emp_ord_nsb_detail_rec.has_changed
     *
     * @mbggenerated
     */
    private Integer hasChanged;

    

    public Long getOrdNsbRecId() {
		return ordNsbRecId;
	}

	public void setOrdNsbRecId(Long ordNsbRecId) {
		this.ordNsbRecId = ordNsbRecId;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_emp_ord_nsb_detail_rec.order_record_id
     *
     * @return the value of hs_emp_ord_nsb_detail_rec.order_record_id
     *
     * @mbggenerated
     */
    public Long getOrderRecordId() {
        return orderRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_emp_ord_nsb_detail_rec.order_record_id
     *
     * @param orderRecordId the value for hs_emp_ord_nsb_detail_rec.order_record_id
     *
     * @mbggenerated
     */
    public void setOrderRecordId(Long orderRecordId) {
        this.orderRecordId = orderRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_emp_ord_nsb_detail_rec.quotation_name
     *
     * @return the value of hs_emp_ord_nsb_detail_rec.quotation_name
     *
     * @mbggenerated
     */
    public String getQuotationName() {
        return quotationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_emp_ord_nsb_detail_rec.quotation_name
     *
     * @param quotationName the value for hs_emp_ord_nsb_detail_rec.quotation_name
     *
     * @mbggenerated
     */
    public void setQuotationName(String quotationName) {
        this.quotationName = quotationName == null ? null : quotationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_emp_ord_nsb_detail_rec.offer_id
     *
     * @return the value of hs_emp_ord_nsb_detail_rec.offer_id
     *
     * @mbggenerated
     */
    public Long getOfferId() {
        return offerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_emp_ord_nsb_detail_rec.offer_id
     *
     * @param offerId the value for hs_emp_ord_nsb_detail_rec.offer_id
     *
     * @mbggenerated
     */
    public void setOfferId(Long offerId) {
        this.offerId = offerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_emp_ord_nsb_detail_rec.prod_name
     *
     * @return the value of hs_emp_ord_nsb_detail_rec.prod_name
     *
     * @mbggenerated
     */
    public String getProdName() {
        return prodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_emp_ord_nsb_detail_rec.prod_name
     *
     * @param prodName the value for hs_emp_ord_nsb_detail_rec.prod_name
     *
     * @mbggenerated
     */
    public void setProdName(String prodName) {
        this.prodName = prodName == null ? null : prodName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_emp_ord_nsb_detail_rec.item_id
     *
     * @return the value of hs_emp_ord_nsb_detail_rec.item_id
     *
     * @mbggenerated
     */
    public Long getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_emp_ord_nsb_detail_rec.item_id
     *
     * @param itemId the value for hs_emp_ord_nsb_detail_rec.item_id
     *
     * @mbggenerated
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_emp_ord_nsb_detail_rec.item_type
     *
     * @return the value of hs_emp_ord_nsb_detail_rec.item_type
     *
     * @mbggenerated
     */
    public String getItemType() {
        return itemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_emp_ord_nsb_detail_rec.item_type
     *
     * @param itemType the value for hs_emp_ord_nsb_detail_rec.item_type
     *
     * @mbggenerated
     */
    public void setItemType(String itemType) {
        this.itemType = itemType == null ? null : itemType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_emp_ord_nsb_detail_rec.payment_start_month
     *
     * @return the value of hs_emp_ord_nsb_detail_rec.payment_start_month
     *
     * @mbggenerated
     */
    public String getPaymentStartMonth() {
        return paymentStartMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_emp_ord_nsb_detail_rec.payment_start_month
     *
     * @param paymentStartMonth the value for hs_emp_ord_nsb_detail_rec.payment_start_month
     *
     * @mbggenerated
     */
    public void setPaymentStartMonth(String paymentStartMonth) {
        this.paymentStartMonth = paymentStartMonth == null ? null : paymentStartMonth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_emp_ord_nsb_detail_rec.payment_satrt_day
     *
     * @return the value of hs_emp_ord_nsb_detail_rec.payment_satrt_day
     *
     * @mbggenerated
     */
    public String getPaymentSatrtDay() {
        return paymentSatrtDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_emp_ord_nsb_detail_rec.payment_satrt_day
     *
     * @param paymentSatrtDay the value for hs_emp_ord_nsb_detail_rec.payment_satrt_day
     *
     * @mbggenerated
     */
    public void setPaymentSatrtDay(String paymentSatrtDay) {
        this.paymentSatrtDay = paymentSatrtDay == null ? null : paymentSatrtDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_emp_ord_nsb_detail_rec.payment_end_month
     *
     * @return the value of hs_emp_ord_nsb_detail_rec.payment_end_month
     *
     * @mbggenerated
     */
    public String getPaymentEndMonth() {
        return paymentEndMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_emp_ord_nsb_detail_rec.payment_end_month
     *
     * @param paymentEndMonth the value for hs_emp_ord_nsb_detail_rec.payment_end_month
     *
     * @mbggenerated
     */
    public void setPaymentEndMonth(String paymentEndMonth) {
        this.paymentEndMonth = paymentEndMonth == null ? null : paymentEndMonth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_emp_ord_nsb_detail_rec.payment_end_day
     *
     * @return the value of hs_emp_ord_nsb_detail_rec.payment_end_day
     *
     * @mbggenerated
     */
    public String getPaymentEndDay() {
        return paymentEndDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_emp_ord_nsb_detail_rec.payment_end_day
     *
     * @param paymentEndDay the value for hs_emp_ord_nsb_detail_rec.payment_end_day
     *
     * @mbggenerated
     */
    public void setPaymentEndDay(String paymentEndDay) {
        this.paymentEndDay = paymentEndDay == null ? null : paymentEndDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_emp_ord_nsb_detail_rec.bill_start_month
     *
     * @return the value of hs_emp_ord_nsb_detail_rec.bill_start_month
     *
     * @mbggenerated
     */
    public String getBillStartMonth() {
        return billStartMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_emp_ord_nsb_detail_rec.bill_start_month
     *
     * @param billStartMonth the value for hs_emp_ord_nsb_detail_rec.bill_start_month
     *
     * @mbggenerated
     */
    public void setBillStartMonth(String billStartMonth) {
        this.billStartMonth = billStartMonth == null ? null : billStartMonth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_emp_ord_nsb_detail_rec.bill_end_month
     *
     * @return the value of hs_emp_ord_nsb_detail_rec.bill_end_month
     *
     * @mbggenerated
     */
    public String getBillEndMonth() {
        return billEndMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_emp_ord_nsb_detail_rec.bill_end_month
     *
     * @param billEndMonth the value for hs_emp_ord_nsb_detail_rec.bill_end_month
     *
     * @mbggenerated
     */
    public void setBillEndMonth(String billEndMonth) {
        this.billEndMonth = billEndMonth == null ? null : billEndMonth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_emp_ord_nsb_detail_rec.sum
     *
     * @return the value of hs_emp_ord_nsb_detail_rec.sum
     *
     * @mbggenerated
     */
    public BigDecimal getSum() {
        return sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_emp_ord_nsb_detail_rec.sum
     *
     * @param sum the value for hs_emp_ord_nsb_detail_rec.sum
     *
     * @mbggenerated
     */
    public void setSum(BigDecimal sum) {
        this.sum = sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_emp_ord_nsb_detail_rec.order_index
     *
     * @return the value of hs_emp_ord_nsb_detail_rec.order_index
     *
     * @mbggenerated
     */
    public Integer getOrderIndex() {
        return orderIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_emp_ord_nsb_detail_rec.order_index
     *
     * @param orderIndex the value for hs_emp_ord_nsb_detail_rec.order_index
     *
     * @mbggenerated
     */
    public void setOrderIndex(Integer orderIndex) {
        this.orderIndex = orderIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_emp_ord_nsb_detail_rec.bill_template_id
     *
     * @return the value of hs_emp_ord_nsb_detail_rec.bill_template_id
     *
     * @mbggenerated
     */
    public Long getBillTemplateId() {
        return billTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_emp_ord_nsb_detail_rec.bill_template_id
     *
     * @param billTemplateId the value for hs_emp_ord_nsb_detail_rec.bill_template_id
     *
     * @mbggenerated
     */
    public void setBillTemplateId(Long billTemplateId) {
        this.billTemplateId = billTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_emp_ord_nsb_detail_rec.create_user_id
     *
     * @return the value of hs_emp_ord_nsb_detail_rec.create_user_id
     *
     * @mbggenerated
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_emp_ord_nsb_detail_rec.create_user_id
     *
     * @param createUserId the value for hs_emp_ord_nsb_detail_rec.create_user_id
     *
     * @mbggenerated
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_emp_ord_nsb_detail_rec.create_date
     *
     * @return the value of hs_emp_ord_nsb_detail_rec.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_emp_ord_nsb_detail_rec.create_date
     *
     * @param createDate the value for hs_emp_ord_nsb_detail_rec.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_emp_ord_nsb_detail_rec.update_user_id
     *
     * @return the value of hs_emp_ord_nsb_detail_rec.update_user_id
     *
     * @mbggenerated
     */
    public Long getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_emp_ord_nsb_detail_rec.update_user_id
     *
     * @param updateUserId the value for hs_emp_ord_nsb_detail_rec.update_user_id
     *
     * @mbggenerated
     */
    public void setUpdateUserId(Long updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_emp_ord_nsb_detail_rec.update_date
     *
     * @return the value of hs_emp_ord_nsb_detail_rec.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_emp_ord_nsb_detail_rec.update_date
     *
     * @param updateDate the value for hs_emp_ord_nsb_detail_rec.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_emp_ord_nsb_detail_rec.is_deleted
     *
     * @return the value of hs_emp_ord_nsb_detail_rec.is_deleted
     *
     * @mbggenerated
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_emp_ord_nsb_detail_rec.is_deleted
     *
     * @param isDeleted the value for hs_emp_ord_nsb_detail_rec.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hs_emp_ord_nsb_detail_rec.has_changed
     *
     * @return the value of hs_emp_ord_nsb_detail_rec.has_changed
     *
     * @mbggenerated
     */
    public Integer getHasChanged() {
        return hasChanged;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hs_emp_ord_nsb_detail_rec.has_changed
     *
     * @param hasChanged the value for hs_emp_ord_nsb_detail_rec.has_changed
     *
     * @mbggenerated
     */
    public void setHasChanged(Integer hasChanged) {
        this.hasChanged = hasChanged;
    }
}