package com.jabava.pojo.salary;

public class EhrSalaryTemplateDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_salary_template_detail.salary_template_detail_id
     *
     * @mbggenerated Wed Mar 23 10:07:46 CST 2016
     */
    private Long salaryTemplateDetailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_salary_template_detail.salary_template_id
     *
     * @mbggenerated Wed Mar 23 10:07:46 CST 2016
     */
    private Long salaryTemplateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_salary_template_detail.salary_item_id
     *
     * @mbggenerated Wed Mar 23 10:07:46 CST 2016
     */
    private Long salaryItemId;
    
    private String salaryItemName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_salary_template_detail.salary_template_detail_id
     *
     * @return the value of ehr_salary_template_detail.salary_template_detail_id
     *
     * @mbggenerated Wed Mar 23 10:07:46 CST 2016
     */
    public Long getSalaryTemplateDetailId() {
        return salaryTemplateDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_salary_template_detail.salary_template_detail_id
     *
     * @param salaryTemplateDetailId the value for ehr_salary_template_detail.salary_template_detail_id
     *
     * @mbggenerated Wed Mar 23 10:07:46 CST 2016
     */
    public void setSalaryTemplateDetailId(Long salaryTemplateDetailId) {
        this.salaryTemplateDetailId = salaryTemplateDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_salary_template_detail.salary_template_id
     *
     * @return the value of ehr_salary_template_detail.salary_template_id
     *
     * @mbggenerated Wed Mar 23 10:07:46 CST 2016
     */
    public Long getSalaryTemplateId() {
        return salaryTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_salary_template_detail.salary_template_id
     *
     * @param salaryTemplateId the value for ehr_salary_template_detail.salary_template_id
     *
     * @mbggenerated Wed Mar 23 10:07:46 CST 2016
     */
    public void setSalaryTemplateId(Long salaryTemplateId) {
        this.salaryTemplateId = salaryTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_salary_template_detail.salary_item_id
     *
     * @return the value of ehr_salary_template_detail.salary_item_id
     *
     * @mbggenerated Wed Mar 23 10:07:46 CST 2016
     */
    public Long getSalaryItemId() {
        return salaryItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_salary_template_detail.salary_item_id
     *
     * @param salaryItemId the value for ehr_salary_template_detail.salary_item_id
     *
     * @mbggenerated Wed Mar 23 10:07:46 CST 2016
     */
    public void setSalaryItemId(Long salaryItemId) {
        this.salaryItemId = salaryItemId;
    }

	public String getSalaryItemName() {
		return salaryItemName;
	}

	public void setSalaryItemName(String salaryItemName) {
		this.salaryItemName = salaryItemName;
	}
}