package com.jabava.pojo.salary;

import java.util.Date;

public class EhrSalaryItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_salary_item.salary_item_id
     *
     * @mbggenerated Mon Mar 21 14:16:54 CST 2016
     */
    private Long salaryItemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_salary_item.company_id
     *
     * @mbggenerated Mon Mar 21 14:16:54 CST 2016
     */
    private Long companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_salary_item.salary_item_name
     *
     * @mbggenerated Mon Mar 21 14:16:54 CST 2016
     */
    private String salaryItemName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_salary_item.salary_change_def_id
     *
     * @mbggenerated Mon Mar 21 14:16:54 CST 2016
     */
    private Long salaryChangeDefId;
    

    private String salaryChangeDefName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_salary_item.change_table_name
     *
     * @mbggenerated Mon Mar 21 14:16:54 CST 2016
     */
    private String changeTableName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_salary_item.is_transition
     *
     * @mbggenerated Mon Mar 21 14:16:54 CST 2016
     */
    private Boolean isTransition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_salary_item.tax_rule
     *
     * @mbggenerated Mon Mar 21 14:16:54 CST 2016
     */
    private Integer taxRule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_salary_item.tax_rate_id
     *
     * @mbggenerated Mon Mar 21 14:16:54 CST 2016
     */
    private Long taxRateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_salary_item.calculate_rule
     *
     * @mbggenerated Mon Mar 21 14:16:54 CST 2016
     */
    private Integer calculateRule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_salary_item.item_type
     *
     * @mbggenerated Mon Mar 21 14:16:54 CST 2016
     */
    private Integer itemType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_salary_item.change_formula
     *
     * @mbggenerated Mon Mar 21 14:16:54 CST 2016
     */
    private String changeFormula;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_salary_item.item_memo
     *
     * @mbggenerated Mon Mar 21 14:16:54 CST 2016
     */
    private String itemMemo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_salary_item.display_order
     *
     * @mbggenerated Mon Mar 21 14:16:54 CST 2016
     */
    private Integer displayOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_salary_item.yearly_flag
     *
     * @mbggenerated Mon Mar 21 14:16:54 CST 2016
     */
    private Integer yearlyFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_salary_item.create_user_id
     *
     * @mbggenerated Mon Mar 21 14:16:54 CST 2016
     */
    private Long createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_salary_item.create_user_name
     *
     * @mbggenerated Mon Mar 21 14:16:54 CST 2016
     */
    private String createUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_salary_item.create_date
     *
     * @mbggenerated Mon Mar 21 14:16:54 CST 2016
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_salary_item.last_modify_user_id
     *
     * @mbggenerated Mon Mar 21 14:16:54 CST 2016
     */
    private Long lastModifyUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_salary_item.last_modify_user_name
     *
     * @mbggenerated Mon Mar 21 14:16:54 CST 2016
     */
    private String lastModifyUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_salary_item.last_modify_date
     *
     * @mbggenerated Mon Mar 21 14:16:54 CST 2016
     */
    private Date lastModifyDate;
    
    private Boolean isSalarySlipItem;
    
    //是否在模板中(仅用于显示)
    private Integer inTemplate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_salary_item.salary_item_id
     *
     * @return the value of ehr_salary_item.salary_item_id
     *
     * @mbggenerated Mon Mar 21 14:16:54 CST 2016
     */
    public Long getSalaryItemId() {
        return salaryItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_salary_item.salary_item_id
     *
     * @param salaryItemId the value for ehr_salary_item.salary_item_id
     *
     * @mbggenerated Mon Mar 21 14:16:54 CST 2016
     */
    public void setSalaryItemId(Long salaryItemId) {
        this.salaryItemId = salaryItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_salary_item.company_id
     *
     * @return the value of ehr_salary_item.company_id
     *
     * @mbggenerated Mon Mar 21 14:16:54 CST 2016
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_salary_item.company_id
     *
     * @param companyId the value for ehr_salary_item.company_id
     *
     * @mbggenerated Mon Mar 21 14:16:54 CST 2016
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_salary_item.salary_item_name
     *
     * @return the value of ehr_salary_item.salary_item_name
     *
     * @mbggenerated Mon Mar 21 14:16:54 CST 2016
     */
    public String getSalaryItemName() {
        return salaryItemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_salary_item.salary_item_name
     *
     * @param salaryItemName the value for ehr_salary_item.salary_item_name
     *
     * @mbggenerated Mon Mar 21 14:16:54 CST 2016
     */
    public void setSalaryItemName(String salaryItemName) {
        this.salaryItemName = salaryItemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_salary_item.salary_change_def_id
     *
     * @return the value of ehr_salary_item.salary_change_def_id
     *
     * @mbggenerated Mon Mar 21 14:16:54 CST 2016
     */
    public Long getSalaryChangeDefId() {
        return salaryChangeDefId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_salary_item.salary_change_def_id
     *
     * @param salaryChangeDefId the value for ehr_salary_item.salary_change_def_id
     *
     * @mbggenerated Mon Mar 21 14:16:54 CST 2016
     */
    public void setSalaryChangeDefId(Long salaryChangeDefId) {
        this.salaryChangeDefId = salaryChangeDefId;
    }

    public String getSalaryChangeDefName() {
		return salaryChangeDefName;
	}

	public void setSalaryChangeDefName(String salaryChangeDefName) {
		this.salaryChangeDefName = salaryChangeDefName;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_salary_item.change_table_name
     *
     * @return the value of ehr_salary_item.change_table_name
     *
     * @mbggenerated Mon Mar 21 14:16:54 CST 2016
     */
    public String getChangeTableName() {
        return changeTableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_salary_item.change_table_name
     *
     * @param changeTableName the value for ehr_salary_item.change_table_name
     *
     * @mbggenerated Mon Mar 21 14:16:54 CST 2016
     */
    public void setChangeTableName(String changeTableName) {
        this.changeTableName = changeTableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_salary_item.is_transition
     *
     * @return the value of ehr_salary_item.is_transition
     *
     * @mbggenerated Mon Mar 21 14:16:54 CST 2016
     */
    public Boolean getIsTransition() {
        return isTransition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_salary_item.is_transition
     *
     * @param isTransition the value for ehr_salary_item.is_transition
     *
     * @mbggenerated Mon Mar 21 14:16:54 CST 2016
     */
    public void setIsTransition(Boolean isTransition) {
        this.isTransition = isTransition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_salary_item.tax_rule
     *
     * @return the value of ehr_salary_item.tax_rule
     *
     * @mbggenerated Mon Mar 21 14:16:54 CST 2016
     */
    public Integer getTaxRule() {
        return taxRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_salary_item.tax_rule
     *
     * @param taxRule the value for ehr_salary_item.tax_rule
     *
     * @mbggenerated Mon Mar 21 14:16:54 CST 2016
     */
    public void setTaxRule(Integer taxRule) {
        this.taxRule = taxRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_salary_item.tax_rate_id
     *
     * @return the value of ehr_salary_item.tax_rate_id
     *
     * @mbggenerated Mon Mar 21 14:16:54 CST 2016
     */
    public Long getTaxRateId() {
        return taxRateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_salary_item.tax_rate_id
     *
     * @param taxRateId the value for ehr_salary_item.tax_rate_id
     *
     * @mbggenerated Mon Mar 21 14:16:54 CST 2016
     */
    public void setTaxRateId(Long taxRateId) {
        this.taxRateId = taxRateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_salary_item.calculate_rule
     *
     * @return the value of ehr_salary_item.calculate_rule
     *
     * @mbggenerated Mon Mar 21 14:16:54 CST 2016
     */
    public Integer getCalculateRule() {
        return calculateRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_salary_item.calculate_rule
     *
     * @param calculateRule the value for ehr_salary_item.calculate_rule
     *
     * @mbggenerated Mon Mar 21 14:16:54 CST 2016
     */
    public void setCalculateRule(Integer calculateRule) {
        this.calculateRule = calculateRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_salary_item.item_type
     *
     * @return the value of ehr_salary_item.item_type
     *
     * @mbggenerated Mon Mar 21 14:16:54 CST 2016
     */
    public Integer getItemType() {
        return itemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_salary_item.item_type
     *
     * @param itemType the value for ehr_salary_item.item_type
     *
     * @mbggenerated Mon Mar 21 14:16:54 CST 2016
     */
    public void setItemType(Integer itemType) {
        this.itemType = itemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_salary_item.change_formula
     *
     * @return the value of ehr_salary_item.change_formula
     *
     * @mbggenerated Mon Mar 21 14:16:54 CST 2016
     */
    public String getChangeFormula() {
        return changeFormula;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_salary_item.change_formula
     *
     * @param changeFormula the value for ehr_salary_item.change_formula
     *
     * @mbggenerated Mon Mar 21 14:16:54 CST 2016
     */
    public void setChangeFormula(String changeFormula) {
        this.changeFormula = changeFormula;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_salary_item.item_memo
     *
     * @return the value of ehr_salary_item.item_memo
     *
     * @mbggenerated Mon Mar 21 14:16:54 CST 2016
     */
    public String getItemMemo() {
        return itemMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_salary_item.item_memo
     *
     * @param itemMemo the value for ehr_salary_item.item_memo
     *
     * @mbggenerated Mon Mar 21 14:16:54 CST 2016
     */
    public void setItemMemo(String itemMemo) {
        this.itemMemo = itemMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_salary_item.display_order
     *
     * @return the value of ehr_salary_item.display_order
     *
     * @mbggenerated Mon Mar 21 14:16:54 CST 2016
     */
    public Integer getDisplayOrder() {
        return displayOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_salary_item.display_order
     *
     * @param displayOrder the value for ehr_salary_item.display_order
     *
     * @mbggenerated Mon Mar 21 14:16:54 CST 2016
     */
    public void setDisplayOrder(Integer displayOrder) {
        this.displayOrder = displayOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_salary_item.yearly_flag
     *
     * @return the value of ehr_salary_item.yearly_flag
     *
     * @mbggenerated Mon Mar 21 14:16:54 CST 2016
     */
    public Integer getYearlyFlag() {
        return yearlyFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_salary_item.yearly_flag
     *
     * @param yearlyFlag the value for ehr_salary_item.yearly_flag
     *
     * @mbggenerated Mon Mar 21 14:16:54 CST 2016
     */
    public void setYearlyFlag(Integer yearlyFlag) {
        this.yearlyFlag = yearlyFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_salary_item.create_user_id
     *
     * @return the value of ehr_salary_item.create_user_id
     *
     * @mbggenerated Mon Mar 21 14:16:54 CST 2016
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_salary_item.create_user_id
     *
     * @param createUserId the value for ehr_salary_item.create_user_id
     *
     * @mbggenerated Mon Mar 21 14:16:54 CST 2016
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_salary_item.create_user_name
     *
     * @return the value of ehr_salary_item.create_user_name
     *
     * @mbggenerated Mon Mar 21 14:16:54 CST 2016
     */
    public String getCreateUserName() {
        return createUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_salary_item.create_user_name
     *
     * @param createUserName the value for ehr_salary_item.create_user_name
     *
     * @mbggenerated Mon Mar 21 14:16:54 CST 2016
     */
    public void setCreateUserName(String createUserName) {
        this.createUserName = createUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_salary_item.create_date
     *
     * @return the value of ehr_salary_item.create_date
     *
     * @mbggenerated Mon Mar 21 14:16:54 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_salary_item.create_date
     *
     * @param createDate the value for ehr_salary_item.create_date
     *
     * @mbggenerated Mon Mar 21 14:16:54 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_salary_item.last_modify_user_id
     *
     * @return the value of ehr_salary_item.last_modify_user_id
     *
     * @mbggenerated Mon Mar 21 14:16:54 CST 2016
     */
    public Long getLastModifyUserId() {
        return lastModifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_salary_item.last_modify_user_id
     *
     * @param lastModifyUserId the value for ehr_salary_item.last_modify_user_id
     *
     * @mbggenerated Mon Mar 21 14:16:54 CST 2016
     */
    public void setLastModifyUserId(Long lastModifyUserId) {
        this.lastModifyUserId = lastModifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_salary_item.last_modify_user_name
     *
     * @return the value of ehr_salary_item.last_modify_user_name
     *
     * @mbggenerated Mon Mar 21 14:16:54 CST 2016
     */
    public String getLastModifyUserName() {
        return lastModifyUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_salary_item.last_modify_user_name
     *
     * @param lastModifyUserName the value for ehr_salary_item.last_modify_user_name
     *
     * @mbggenerated Mon Mar 21 14:16:54 CST 2016
     */
    public void setLastModifyUserName(String lastModifyUserName) {
        this.lastModifyUserName = lastModifyUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_salary_item.last_modify_date
     *
     * @return the value of ehr_salary_item.last_modify_date
     *
     * @mbggenerated Mon Mar 21 14:16:54 CST 2016
     */
    public Date getLastModifyDate() {
        return lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_salary_item.last_modify_date
     *
     * @param lastModifyDate the value for ehr_salary_item.last_modify_date
     *
     * @mbggenerated Mon Mar 21 14:16:54 CST 2016
     */
    public void setLastModifyDate(Date lastModifyDate) {
        this.lastModifyDate = lastModifyDate;
    }

	public Boolean getIsSalarySlipItem() {
		return isSalarySlipItem;
	}

	public void setIsSalarySlipItem(Boolean isSalarySlipItem) {
		this.isSalarySlipItem = isSalarySlipItem;
	}

	public Integer getInTemplate() {
		return inTemplate;
	}

	public void setInTemplate(Integer inTemplate) {
		this.inTemplate = inTemplate;
	}
}