package com.jabava.pojo.salary;

import java.math.BigDecimal;

public class EhrSalaryDetail {
	public EhrSalaryDetail(){
		
	}
	
	public EhrSalaryDetail(Long salaryId, Long salaryItemId, String salaryItemName){
		this.salaryId = salaryId;
		this.salaryItemId = salaryItemId;
		this.salaryItemName = salaryItemName;
	}
	
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_salary_detail.salary_detail_id
     *
     * @mbggenerated Thu Mar 24 09:48:32 CST 2016
     */
    private Long salaryDetailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_salary_detail.salary_id
     *
     * @mbggenerated Thu Mar 24 09:48:32 CST 2016
     */
    private Long salaryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_salary_detail.salary_item_id
     *
     * @mbggenerated Thu Mar 24 09:48:32 CST 2016
     */
    private Long salaryItemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_salary_detail.salary_item_name
     *
     * @mbggenerated Thu Mar 24 09:48:32 CST 2016
     */
    private String salaryItemName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_salary_detail.amount
     *
     * @mbggenerated Thu Mar 24 09:48:32 CST 2016
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_salary_detail.pay_radio
     *
     * @mbggenerated Thu Mar 24 09:48:32 CST 2016
     */
    private BigDecimal payRadio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_salary_detail.bonus_base
     *
     * @mbggenerated Thu Mar 24 09:48:32 CST 2016
     */
    private BigDecimal bonusBase;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_salary_detail.bonus_rule
     *
     * @mbggenerated Thu Mar 24 09:48:32 CST 2016
     */
    private String bonusRule;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_salary_detail.salary_detail_id
     *
     * @return the value of ehr_salary_detail.salary_detail_id
     *
     * @mbggenerated Thu Mar 24 09:48:32 CST 2016
     */
    public Long getSalaryDetailId() {
        return salaryDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_salary_detail.salary_detail_id
     *
     * @param salaryDetailId the value for ehr_salary_detail.salary_detail_id
     *
     * @mbggenerated Thu Mar 24 09:48:32 CST 2016
     */
    public void setSalaryDetailId(Long salaryDetailId) {
        this.salaryDetailId = salaryDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_salary_detail.salary_id
     *
     * @return the value of ehr_salary_detail.salary_id
     *
     * @mbggenerated Thu Mar 24 09:48:32 CST 2016
     */
    public Long getSalaryId() {
        return salaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_salary_detail.salary_id
     *
     * @param salaryId the value for ehr_salary_detail.salary_id
     *
     * @mbggenerated Thu Mar 24 09:48:32 CST 2016
     */
    public void setSalaryId(Long salaryId) {
        this.salaryId = salaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_salary_detail.salary_item_id
     *
     * @return the value of ehr_salary_detail.salary_item_id
     *
     * @mbggenerated Thu Mar 24 09:48:32 CST 2016
     */
    public Long getSalaryItemId() {
        return salaryItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_salary_detail.salary_item_id
     *
     * @param salaryItemId the value for ehr_salary_detail.salary_item_id
     *
     * @mbggenerated Thu Mar 24 09:48:32 CST 2016
     */
    public void setSalaryItemId(Long salaryItemId) {
        this.salaryItemId = salaryItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_salary_detail.salary_item_name
     *
     * @return the value of ehr_salary_detail.salary_item_name
     *
     * @mbggenerated Thu Mar 24 09:48:32 CST 2016
     */
    public String getSalaryItemName() {
        return salaryItemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_salary_detail.salary_item_name
     *
     * @param salaryItemName the value for ehr_salary_detail.salary_item_name
     *
     * @mbggenerated Thu Mar 24 09:48:32 CST 2016
     */
    public void setSalaryItemName(String salaryItemName) {
        this.salaryItemName = salaryItemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_salary_detail.amount
     *
     * @return the value of ehr_salary_detail.amount
     *
     * @mbggenerated Thu Mar 24 09:48:32 CST 2016
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_salary_detail.amount
     *
     * @param amount the value for ehr_salary_detail.amount
     *
     * @mbggenerated Thu Mar 24 09:48:32 CST 2016
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_salary_detail.pay_radio
     *
     * @return the value of ehr_salary_detail.pay_radio
     *
     * @mbggenerated Thu Mar 24 09:48:32 CST 2016
     */
    public BigDecimal getPayRadio() {
        return payRadio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_salary_detail.pay_radio
     *
     * @param payRadio the value for ehr_salary_detail.pay_radio
     *
     * @mbggenerated Thu Mar 24 09:48:32 CST 2016
     */
    public void setPayRadio(BigDecimal payRadio) {
        this.payRadio = payRadio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_salary_detail.bonus_base
     *
     * @return the value of ehr_salary_detail.bonus_base
     *
     * @mbggenerated Thu Mar 24 09:48:32 CST 2016
     */
    public BigDecimal getBonusBase() {
        return bonusBase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_salary_detail.bonus_base
     *
     * @param bonusBase the value for ehr_salary_detail.bonus_base
     *
     * @mbggenerated Thu Mar 24 09:48:32 CST 2016
     */
    public void setBonusBase(BigDecimal bonusBase) {
        this.bonusBase = bonusBase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_salary_detail.bonus_rule
     *
     * @return the value of ehr_salary_detail.bonus_rule
     *
     * @mbggenerated Thu Mar 24 09:48:32 CST 2016
     */
    public String getBonusRule() {
        return bonusRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_salary_detail.bonus_rule
     *
     * @param bonusRule the value for ehr_salary_detail.bonus_rule
     *
     * @mbggenerated Thu Mar 24 09:48:32 CST 2016
     */
    public void setBonusRule(String bonusRule) {
        this.bonusRule = bonusRule;
    }
}