package com.jabava.pojo.salary;

public class EhrSalaryChangeDefItem {
	
	public EhrSalaryChangeDefItem(){}
	
	public EhrSalaryChangeDefItem(String displayName, String columnName, Integer dataType){
		this.displayName = displayName;
		this.columnName = columnName;
		this.dataType = dataType;
	}
	
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_salary_change_def_item.salary_item_def_item_id
     *
     * @mbggenerated Sun Mar 20 12:57:07 CST 2016
     */
    private Long salaryChangeDefItemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_salary_change_def_item.salary_change_def_id
     *
     * @mbggenerated Sun Mar 20 12:57:07 CST 2016
     */
    private Long salaryChangeDefId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_salary_change_def_item.display_name
     *
     * @mbggenerated Sun Mar 20 12:57:07 CST 2016
     */
    private String displayName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_salary_change_def_item.column_name
     *
     * @mbggenerated Sun Mar 20 12:57:07 CST 2016
     */
    private String columnName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_salary_change_def_item.data_type
     *
     * @mbggenerated Sun Mar 20 12:57:07 CST 2016
     */
    private Integer dataType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_salary_change_def_item.salary_item_def_item_id
     *
     * @return the value of ehr_salary_change_def_item.salary_item_def_item_id
     *
     * @mbggenerated Sun Mar 20 12:57:07 CST 2016
     */
    public Long getSalaryChangeDefItemId() {
        return salaryChangeDefItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_salary_change_def_item.salary_item_def_item_id
     *
     * @param salaryItemDefItemId the value for ehr_salary_change_def_item.salary_item_def_item_id
     *
     * @mbggenerated Sun Mar 20 12:57:07 CST 2016
     */
    public void setSalaryChangeDefItemId(Long salaryChangeDefItemId) {
        this.salaryChangeDefItemId = salaryChangeDefItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_salary_change_def_item.salary_change_def_id
     *
     * @return the value of ehr_salary_change_def_item.salary_change_def_id
     *
     * @mbggenerated Sun Mar 20 12:57:07 CST 2016
     */
    public Long getSalaryChangeDefId() {
        return salaryChangeDefId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_salary_change_def_item.salary_change_def_id
     *
     * @param salaryChangeDefId the value for ehr_salary_change_def_item.salary_change_def_id
     *
     * @mbggenerated Sun Mar 20 12:57:07 CST 2016
     */
    public void setSalaryChangeDefId(Long salaryChangeDefId) {
        this.salaryChangeDefId = salaryChangeDefId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_salary_change_def_item.display_name
     *
     * @return the value of ehr_salary_change_def_item.display_name
     *
     * @mbggenerated Sun Mar 20 12:57:07 CST 2016
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_salary_change_def_item.display_name
     *
     * @param displayName the value for ehr_salary_change_def_item.display_name
     *
     * @mbggenerated Sun Mar 20 12:57:07 CST 2016
     */
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_salary_change_def_item.column_name
     *
     * @return the value of ehr_salary_change_def_item.column_name
     *
     * @mbggenerated Sun Mar 20 12:57:07 CST 2016
     */
    public String getColumnName() {
        return columnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_salary_change_def_item.column_name
     *
     * @param columnName the value for ehr_salary_change_def_item.column_name
     *
     * @mbggenerated Sun Mar 20 12:57:07 CST 2016
     */
    public void setColumnName(String columnName) {
        this.columnName = columnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_salary_change_def_item.data_type
     *
     * @return the value of ehr_salary_change_def_item.data_type
     *
     * @mbggenerated Sun Mar 20 12:57:07 CST 2016
     */
    public Integer getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_salary_change_def_item.data_type
     *
     * @param dataType the value for ehr_salary_change_def_item.data_type
     *
     * @mbggenerated Sun Mar 20 12:57:07 CST 2016
     */
    public void setDataType(Integer dataType) {
        this.dataType = dataType;
    }
}