package com.jabava.dao.hro;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.jabava.pojo.hro.EfArap;

public interface EfArapMapper {
	
	List<EfArap> selectBillPage(Map<String,Object> params);
	
	List<EfArap> selectBill(Map<String,Object> params);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ef_arap
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long billId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ef_arap
     *
     * @mbggenerated
     */
    int insert(EfArap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ef_arap
     *
     * @mbggenerated
     */
    int insertSelective(EfArap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ef_arap
     *
     * @mbggenerated
     */
    EfArap selectByPrimaryKey(Long billId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ef_arap
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EfArap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ef_arap
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EfArap record);
    
    int countByProtocolCode(String protocolCode);

    EfArap selectByBillCode(String billCode);
    
    List<Map<String,Object>> queryAmountByYear(@Param("companyId") Long companyId,@Param("year") String year);
    
    BigDecimal queryAmountBeforeYear(@Param("companyId") Long companyId,@Param("year") String year);
    
    Integer queryPersonCount(@Param("companyId") Long companyId,@Param("ym") String ym);
    
}