package com.jabava.dao.hro;

import java.util.List;
import java.util.Map;

import com.jabava.pojo.hro.HroPactInfo;

public interface HroPactInfoMapper {
	 /**
     * 根据参数分页查询协议
     * <pre>
     * @author steven.chen
     * @date 2016年1月8日 下午1:45:50 
     * </pre>
     *
     * @param record
     * @return
     */
    List<HroPactInfo> queryProtocolPage(Map<String, Object> map);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hro_pact_info
     *
     * @mbggenerated Wed Dec 16 12:00:17 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hro_pact_info
     *
     * @mbggenerated Wed Dec 16 12:00:17 CST 2015
     */
    int insert(HroPactInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hro_pact_info
     *
     * @mbggenerated Wed Dec 16 12:00:17 CST 2015
     */
    int insertSelective(HroPactInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hro_pact_info
     *
     * @mbggenerated Wed Dec 16 12:00:17 CST 2015
     */
    HroPactInfo selectByPrimaryKey(Long id);
    /**
     * 根据参数查询协议
     * <pre>
     * @author steven.chen
     * @date 2016年1月8日 下午1:45:50 
     * </pre>
     *
     * @param record
     * @return
     */
    List<HroPactInfo> queryProtocol(HroPactInfo hroPactInfo);
    /**
     * 根据协议号获取
     * <pre>
     * @author steven.chen
     * @date 2016年1月8日 下午1:37:19 
     * </pre>
     *
     * @param pactCode
     * @return
     */
    HroPactInfo selectByPactCode(String pactCode);
    /**
     * 根据协议号更新状态
     * <pre>
     * @author steven.chen
     * @date 2016年1月8日 下午1:37:34 
     * </pre>
     *
     * @param pactCode
     * @return
     */
    int updateByPactCode(HroPactInfo hroPactInfo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hro_pact_info
     *
     * @mbggenerated Wed Dec 16 12:00:17 CST 2015
     */
    int updateByPrimaryKeySelective(HroPactInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hro_pact_info
     *
     * @mbggenerated Wed Dec 16 12:00:17 CST 2015
     */
    int updateByPrimaryKey(HroPactInfo record);
    
    List<HroPactInfo> queryPactInfoList();
    
    List<HroPactInfo> queryPactInfoListByCompany(Long companyId);
    
}