package com.jabava.dao.hro;

import java.util.List;

import com.jabava.pojo.hro.HroSendDetail;

/**
 * 增减变详情
 *
 * @version $Id: HroSendDetailMapper.java, 
 * v 0.1 2016年1月15日 上午11:04:02 
 * <pre>
 * @author steven.chen
 * @date 2016年1月15日 上午11:04:02 
 * </pre>
 */

public interface HroSendDetailMapper {
	/**
	 * 批量新增详情
	 * <pre>
	 * @author steven.chen
	 * @date 2016年1月15日 上午11:18:16 
	 * </pre>
	 *
	 * @param list
	 * @return
	 */
	int insertList(List<HroSendDetail> list);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hro_send_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long hroSendDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hro_send_detail
     *
     * @mbggenerated
     */
    int insert(HroSendDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hro_send_detail
     *
     * @mbggenerated
     */
    int insertSelective(HroSendDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hro_send_detail
     *
     * @mbggenerated
     */
    HroSendDetail selectByPrimaryKey(Long hroSendDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hro_send_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HroSendDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hro_send_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HroSendDetail record);
}