package com.jabava.pojo.report;

import java.util.Date;

public class EhrReportParam {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_report_param.id
     *
     * @mbggenerated Thu Apr 07 11:45:34 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_report_param.report_id
     *
     * @mbggenerated Thu Apr 07 11:45:34 CST 2016
     */
    private Long reportId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_report_param.english_name
     *
     * @mbggenerated Thu Apr 07 11:45:34 CST 2016
     */
    private String englishName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_report_param.chinese_name
     *
     * @mbggenerated Thu Apr 07 11:45:34 CST 2016
     */
    private String chineseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_report_param.input_type
     *
     * @mbggenerated Thu Apr 07 11:45:34 CST 2016
     */
    private String inputType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_report_param.element_property
     *
     * @mbggenerated Thu Apr 07 11:45:34 CST 2016
     */
    private String elementProperty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_report_param.is_deleted
     *
     * @mbggenerated Thu Apr 07 11:45:34 CST 2016
     */
    private Integer isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_report_param.create_user_id
     *
     * @mbggenerated Thu Apr 07 11:45:34 CST 2016
     */
    private Long createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_report_param.create_user_name
     *
     * @mbggenerated Thu Apr 07 11:45:34 CST 2016
     */
    private String createUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_report_param.create_date
     *
     * @mbggenerated Thu Apr 07 11:45:34 CST 2016
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_report_param.last_modify_user_id
     *
     * @mbggenerated Thu Apr 07 11:45:34 CST 2016
     */
    private Long lastModifyUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_report_param.last_modify_user_name
     *
     * @mbggenerated Thu Apr 07 11:45:34 CST 2016
     */
    private String lastModifyUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_report_param.last_modify_date
     *
     * @mbggenerated Thu Apr 07 11:45:34 CST 2016
     */
    private Date lastModifyDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_report_param.id
     *
     * @return the value of ehr_report_param.id
     *
     * @mbggenerated Thu Apr 07 11:45:34 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_report_param.id
     *
     * @param id the value for ehr_report_param.id
     *
     * @mbggenerated Thu Apr 07 11:45:34 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_report_param.report_id
     *
     * @return the value of ehr_report_param.report_id
     *
     * @mbggenerated Thu Apr 07 11:45:34 CST 2016
     */
    public Long getReportId() {
        return reportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_report_param.report_id
     *
     * @param reportId the value for ehr_report_param.report_id
     *
     * @mbggenerated Thu Apr 07 11:45:34 CST 2016
     */
    public void setReportId(Long reportId) {
        this.reportId = reportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_report_param.english_name
     *
     * @return the value of ehr_report_param.english_name
     *
     * @mbggenerated Thu Apr 07 11:45:34 CST 2016
     */
    public String getEnglishName() {
        return englishName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_report_param.english_name
     *
     * @param englishName the value for ehr_report_param.english_name
     *
     * @mbggenerated Thu Apr 07 11:45:34 CST 2016
     */
    public void setEnglishName(String englishName) {
        this.englishName = englishName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_report_param.chinese_name
     *
     * @return the value of ehr_report_param.chinese_name
     *
     * @mbggenerated Thu Apr 07 11:45:34 CST 2016
     */
    public String getChineseName() {
        return chineseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_report_param.chinese_name
     *
     * @param chineseName the value for ehr_report_param.chinese_name
     *
     * @mbggenerated Thu Apr 07 11:45:34 CST 2016
     */
    public void setChineseName(String chineseName) {
        this.chineseName = chineseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_report_param.input_type
     *
     * @return the value of ehr_report_param.input_type
     *
     * @mbggenerated Thu Apr 07 11:45:34 CST 2016
     */
    public String getInputType() {
        return inputType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_report_param.input_type
     *
     * @param inputType the value for ehr_report_param.input_type
     *
     * @mbggenerated Thu Apr 07 11:45:34 CST 2016
     */
    public void setInputType(String inputType) {
        this.inputType = inputType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_report_param.element_property
     *
     * @return the value of ehr_report_param.element_property
     *
     * @mbggenerated Thu Apr 07 11:45:34 CST 2016
     */
    public String getElementProperty() {
        return elementProperty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_report_param.element_property
     *
     * @param elementProperty the value for ehr_report_param.element_property
     *
     * @mbggenerated Thu Apr 07 11:45:34 CST 2016
     */
    public void setElementProperty(String elementProperty) {
        this.elementProperty = elementProperty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_report_param.is_deleted
     *
     * @return the value of ehr_report_param.is_deleted
     *
     * @mbggenerated Thu Apr 07 11:45:34 CST 2016
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_report_param.is_deleted
     *
     * @param isDeleted the value for ehr_report_param.is_deleted
     *
     * @mbggenerated Thu Apr 07 11:45:34 CST 2016
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_report_param.create_user_id
     *
     * @return the value of ehr_report_param.create_user_id
     *
     * @mbggenerated Thu Apr 07 11:45:34 CST 2016
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_report_param.create_user_id
     *
     * @param createUserId the value for ehr_report_param.create_user_id
     *
     * @mbggenerated Thu Apr 07 11:45:34 CST 2016
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_report_param.create_user_name
     *
     * @return the value of ehr_report_param.create_user_name
     *
     * @mbggenerated Thu Apr 07 11:45:34 CST 2016
     */
    public String getCreateUserName() {
        return createUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_report_param.create_user_name
     *
     * @param createUserName the value for ehr_report_param.create_user_name
     *
     * @mbggenerated Thu Apr 07 11:45:34 CST 2016
     */
    public void setCreateUserName(String createUserName) {
        this.createUserName = createUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_report_param.create_date
     *
     * @return the value of ehr_report_param.create_date
     *
     * @mbggenerated Thu Apr 07 11:45:34 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_report_param.create_date
     *
     * @param createDate the value for ehr_report_param.create_date
     *
     * @mbggenerated Thu Apr 07 11:45:34 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_report_param.last_modify_user_id
     *
     * @return the value of ehr_report_param.last_modify_user_id
     *
     * @mbggenerated Thu Apr 07 11:45:34 CST 2016
     */
    public Long getLastModifyUserId() {
        return lastModifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_report_param.last_modify_user_id
     *
     * @param lastModifyUserId the value for ehr_report_param.last_modify_user_id
     *
     * @mbggenerated Thu Apr 07 11:45:34 CST 2016
     */
    public void setLastModifyUserId(Long lastModifyUserId) {
        this.lastModifyUserId = lastModifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_report_param.last_modify_user_name
     *
     * @return the value of ehr_report_param.last_modify_user_name
     *
     * @mbggenerated Thu Apr 07 11:45:34 CST 2016
     */
    public String getLastModifyUserName() {
        return lastModifyUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_report_param.last_modify_user_name
     *
     * @param lastModifyUserName the value for ehr_report_param.last_modify_user_name
     *
     * @mbggenerated Thu Apr 07 11:45:34 CST 2016
     */
    public void setLastModifyUserName(String lastModifyUserName) {
        this.lastModifyUserName = lastModifyUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_report_param.last_modify_date
     *
     * @return the value of ehr_report_param.last_modify_date
     *
     * @mbggenerated Thu Apr 07 11:45:34 CST 2016
     */
    public Date getLastModifyDate() {
        return lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_report_param.last_modify_date
     *
     * @param lastModifyDate the value for ehr_report_param.last_modify_date
     *
     * @mbggenerated Thu Apr 07 11:45:34 CST 2016
     */
    public void setLastModifyDate(Date lastModifyDate) {
        this.lastModifyDate = lastModifyDate;
    }
}