package com.jabava.pojo.common;

public class EhrCommonDataType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_common_data_type.id
     *
     * @mbggenerated Tue Apr 12 12:05:38 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_common_data_type.name
     *
     * @mbggenerated Tue Apr 12 12:05:38 CST 2016
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_common_data_type.id
     *
     * @return the value of ehr_common_data_type.id
     *
     * @mbggenerated Tue Apr 12 12:05:38 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_common_data_type.id
     *
     * @param id the value for ehr_common_data_type.id
     *
     * @mbggenerated Tue Apr 12 12:05:38 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_common_data_type.name
     *
     * @return the value of ehr_common_data_type.name
     *
     * @mbggenerated Tue Apr 12 12:05:38 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_common_data_type.name
     *
     * @param name the value for ehr_common_data_type.name
     *
     * @mbggenerated Tue Apr 12 12:05:38 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }
}