package com.jabava.pojo.common;

import java.util.Date;

public class EhrFile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_file.file_id
     *
     * @mbggenerated Thu Apr 07 11:49:28 CST 2016
     */
    private Long fileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_file.company_id
     *
     * @mbggenerated Thu Apr 07 11:49:28 CST 2016
     */
    private Long companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_file.file_name
     *
     * @mbggenerated Thu Apr 07 11:49:28 CST 2016
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_file.file_class
     *
     * @mbggenerated Thu Apr 07 11:49:28 CST 2016
     */
    private Integer fileClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_file.file_path
     *
     * @mbggenerated Thu Apr 07 11:49:28 CST 2016
     */
    private String filePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_file.module
     *
     * @mbggenerated Thu Apr 07 11:49:28 CST 2016
     */
    private String module;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_file.entity_name
     *
     * @mbggenerated Thu Apr 07 11:49:28 CST 2016
     */
    private String entityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_file.entity_id
     *
     * @mbggenerated Thu Apr 07 11:49:28 CST 2016
     */
    private Long entityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_file.is_deleted
     *
     * @mbggenerated Thu Apr 07 11:49:28 CST 2016
     */
    private Integer isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_file.create_user_id
     *
     * @mbggenerated Thu Apr 07 11:49:28 CST 2016
     */
    private Long createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_file.create_user_name
     *
     * @mbggenerated Thu Apr 07 11:49:28 CST 2016
     */
    private String createUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_file.create_date
     *
     * @mbggenerated Thu Apr 07 11:49:28 CST 2016
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_file.last_modify_user_id
     *
     * @mbggenerated Thu Apr 07 11:49:28 CST 2016
     */
    private Long lastModifyUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_file.last_modify_user_name
     *
     * @mbggenerated Thu Apr 07 11:49:28 CST 2016
     */
    private String lastModifyUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_file.last_modify_date
     *
     * @mbggenerated Thu Apr 07 11:49:28 CST 2016
     */
    private Date lastModifyDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_file.file_id
     *
     * @return the value of ehr_file.file_id
     *
     * @mbggenerated Thu Apr 07 11:49:28 CST 2016
     */
    public Long getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_file.file_id
     *
     * @param fileId the value for ehr_file.file_id
     *
     * @mbggenerated Thu Apr 07 11:49:28 CST 2016
     */
    public void setFileId(Long fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_file.company_id
     *
     * @return the value of ehr_file.company_id
     *
     * @mbggenerated Thu Apr 07 11:49:28 CST 2016
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_file.company_id
     *
     * @param companyId the value for ehr_file.company_id
     *
     * @mbggenerated Thu Apr 07 11:49:28 CST 2016
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_file.file_name
     *
     * @return the value of ehr_file.file_name
     *
     * @mbggenerated Thu Apr 07 11:49:28 CST 2016
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_file.file_name
     *
     * @param fileName the value for ehr_file.file_name
     *
     * @mbggenerated Thu Apr 07 11:49:28 CST 2016
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_file.file_class
     *
     * @return the value of ehr_file.file_class
     *
     * @mbggenerated Thu Apr 07 11:49:28 CST 2016
     */
    public Integer getFileClass() {
        return fileClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_file.file_class
     *
     * @param fileClass the value for ehr_file.file_class
     *
     * @mbggenerated Thu Apr 07 11:49:28 CST 2016
     */
    public void setFileClass(Integer fileClass) {
        this.fileClass = fileClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_file.file_path
     *
     * @return the value of ehr_file.file_path
     *
     * @mbggenerated Thu Apr 07 11:49:28 CST 2016
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_file.file_path
     *
     * @param filePath the value for ehr_file.file_path
     *
     * @mbggenerated Thu Apr 07 11:49:28 CST 2016
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_file.module
     *
     * @return the value of ehr_file.module
     *
     * @mbggenerated Thu Apr 07 11:49:28 CST 2016
     */
    public String getModule() {
        return module;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_file.module
     *
     * @param module the value for ehr_file.module
     *
     * @mbggenerated Thu Apr 07 11:49:28 CST 2016
     */
    public void setModule(String module) {
        this.module = module;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_file.entity_name
     *
     * @return the value of ehr_file.entity_name
     *
     * @mbggenerated Thu Apr 07 11:49:28 CST 2016
     */
    public String getEntityName() {
        return entityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_file.entity_name
     *
     * @param entityName the value for ehr_file.entity_name
     *
     * @mbggenerated Thu Apr 07 11:49:28 CST 2016
     */
    public void setEntityName(String entityName) {
        this.entityName = entityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_file.entity_id
     *
     * @return the value of ehr_file.entity_id
     *
     * @mbggenerated Thu Apr 07 11:49:28 CST 2016
     */
    public Long getEntityId() {
        return entityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_file.entity_id
     *
     * @param entityId the value for ehr_file.entity_id
     *
     * @mbggenerated Thu Apr 07 11:49:28 CST 2016
     */
    public void setEntityId(Long entityId) {
        this.entityId = entityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_file.is_deleted
     *
     * @return the value of ehr_file.is_deleted
     *
     * @mbggenerated Thu Apr 07 11:49:28 CST 2016
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_file.is_deleted
     *
     * @param isDeleted the value for ehr_file.is_deleted
     *
     * @mbggenerated Thu Apr 07 11:49:28 CST 2016
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_file.create_user_id
     *
     * @return the value of ehr_file.create_user_id
     *
     * @mbggenerated Thu Apr 07 11:49:28 CST 2016
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_file.create_user_id
     *
     * @param createUserId the value for ehr_file.create_user_id
     *
     * @mbggenerated Thu Apr 07 11:49:28 CST 2016
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_file.create_user_name
     *
     * @return the value of ehr_file.create_user_name
     *
     * @mbggenerated Thu Apr 07 11:49:28 CST 2016
     */
    public String getCreateUserName() {
        return createUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_file.create_user_name
     *
     * @param createUserName the value for ehr_file.create_user_name
     *
     * @mbggenerated Thu Apr 07 11:49:28 CST 2016
     */
    public void setCreateUserName(String createUserName) {
        this.createUserName = createUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_file.create_date
     *
     * @return the value of ehr_file.create_date
     *
     * @mbggenerated Thu Apr 07 11:49:28 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_file.create_date
     *
     * @param createDate the value for ehr_file.create_date
     *
     * @mbggenerated Thu Apr 07 11:49:28 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_file.last_modify_user_id
     *
     * @return the value of ehr_file.last_modify_user_id
     *
     * @mbggenerated Thu Apr 07 11:49:28 CST 2016
     */
    public Long getLastModifyUserId() {
        return lastModifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_file.last_modify_user_id
     *
     * @param lastModifyUserId the value for ehr_file.last_modify_user_id
     *
     * @mbggenerated Thu Apr 07 11:49:28 CST 2016
     */
    public void setLastModifyUserId(Long lastModifyUserId) {
        this.lastModifyUserId = lastModifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_file.last_modify_user_name
     *
     * @return the value of ehr_file.last_modify_user_name
     *
     * @mbggenerated Thu Apr 07 11:49:28 CST 2016
     */
    public String getLastModifyUserName() {
        return lastModifyUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_file.last_modify_user_name
     *
     * @param lastModifyUserName the value for ehr_file.last_modify_user_name
     *
     * @mbggenerated Thu Apr 07 11:49:28 CST 2016
     */
    public void setLastModifyUserName(String lastModifyUserName) {
        this.lastModifyUserName = lastModifyUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_file.last_modify_date
     *
     * @return the value of ehr_file.last_modify_date
     *
     * @mbggenerated Thu Apr 07 11:49:28 CST 2016
     */
    public Date getLastModifyDate() {
        return lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_file.last_modify_date
     *
     * @param lastModifyDate the value for ehr_file.last_modify_date
     *
     * @mbggenerated Thu Apr 07 11:49:28 CST 2016
     */
    public void setLastModifyDate(Date lastModifyDate) {
        this.lastModifyDate = lastModifyDate;
    }
}