package com.jabava.pojo.socialsecurity;

public class EhrDesignatedHospital {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_designated_hospital.hospital_id
     *
     * @mbggenerated Sun Apr 24 18:26:36 CST 2016
     */
    private Long hospitalId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_designated_hospital.profile_id
     *
     * @mbggenerated Sun Apr 24 18:26:36 CST 2016
     */
    private Long profileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_designated_hospital.person_id
     *
     * @mbggenerated Sun Apr 24 18:26:36 CST 2016
     */
    private Long personId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_designated_hospital.hospita_code
     *
     * @mbggenerated Sun Apr 24 18:26:36 CST 2016
     */
    private String hospitaCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_designated_hospital.hospital_name
     *
     * @mbggenerated Sun Apr 24 18:26:36 CST 2016
     */
    private String hospitalName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_designated_hospital.create_time
     *
     * @mbggenerated Sun Apr 24 18:26:36 CST 2016
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_designated_hospital.is_deleted
     *
     * @mbggenerated Sun Apr 24 18:26:36 CST 2016
     */
    private Integer isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_designated_hospital.hospital_id
     *
     * @return the value of ehr_designated_hospital.hospital_id
     *
     * @mbggenerated Sun Apr 24 18:26:36 CST 2016
     */
    public Long getHospitalId() {
        return hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_designated_hospital.hospital_id
     *
     * @param hospitalId the value for ehr_designated_hospital.hospital_id
     *
     * @mbggenerated Sun Apr 24 18:26:36 CST 2016
     */
    public void setHospitalId(Long hospitalId) {
        this.hospitalId = hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_designated_hospital.profile_id
     *
     * @return the value of ehr_designated_hospital.profile_id
     *
     * @mbggenerated Sun Apr 24 18:26:36 CST 2016
     */
    public Long getProfileId() {
        return profileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_designated_hospital.profile_id
     *
     * @param profileId the value for ehr_designated_hospital.profile_id
     *
     * @mbggenerated Sun Apr 24 18:26:36 CST 2016
     */
    public void setProfileId(Long profileId) {
        this.profileId = profileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_designated_hospital.person_id
     *
     * @return the value of ehr_designated_hospital.person_id
     *
     * @mbggenerated Sun Apr 24 18:26:36 CST 2016
     */
    public Long getPersonId() {
        return personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_designated_hospital.person_id
     *
     * @param personId the value for ehr_designated_hospital.person_id
     *
     * @mbggenerated Sun Apr 24 18:26:36 CST 2016
     */
    public void setPersonId(Long personId) {
        this.personId = personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_designated_hospital.hospita_code
     *
     * @return the value of ehr_designated_hospital.hospita_code
     *
     * @mbggenerated Sun Apr 24 18:26:36 CST 2016
     */
    public String getHospitaCode() {
        return hospitaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_designated_hospital.hospita_code
     *
     * @param hospitaCode the value for ehr_designated_hospital.hospita_code
     *
     * @mbggenerated Sun Apr 24 18:26:36 CST 2016
     */
    public void setHospitaCode(String hospitaCode) {
        this.hospitaCode = hospitaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_designated_hospital.hospital_name
     *
     * @return the value of ehr_designated_hospital.hospital_name
     *
     * @mbggenerated Sun Apr 24 18:26:36 CST 2016
     */
    public String getHospitalName() {
        return hospitalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_designated_hospital.hospital_name
     *
     * @param hospitalName the value for ehr_designated_hospital.hospital_name
     *
     * @mbggenerated Sun Apr 24 18:26:36 CST 2016
     */
    public void setHospitalName(String hospitalName) {
        this.hospitalName = hospitalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_designated_hospital.create_time
     *
     * @return the value of ehr_designated_hospital.create_time
     *
     * @mbggenerated Sun Apr 24 18:26:36 CST 2016
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_designated_hospital.create_time
     *
     * @param createTime the value for ehr_designated_hospital.create_time
     *
     * @mbggenerated Sun Apr 24 18:26:36 CST 2016
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_designated_hospital.is_deleted
     *
     * @return the value of ehr_designated_hospital.is_deleted
     *
     * @mbggenerated Sun Apr 24 18:26:36 CST 2016
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_designated_hospital.is_deleted
     *
     * @param isDeleted the value for ehr_designated_hospital.is_deleted
     *
     * @mbggenerated Sun Apr 24 18:26:36 CST 2016
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }
}