package com.jabava.pojo.socialsecurity;

import java.math.BigDecimal;
import java.util.List;

import com.jabava.pojo.employee.EhrPosition;
import com.jabava.pojo.manage.EhrBaseData;
import com.jabava.pojo.manage.EhrOrganization;

public class EhrPersonSecurityProfile {
	public EhrPersonSecurityProfile(){
		
	}
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person_security_profile.profile_id
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    private Long profileId;
    private String department;//部门
    private String post;//职位
    private String employeeNumber;//工号    
    private BigDecimal salary;//基本工资
    private EhrPosition position;
    private EhrBaseData baseData;
    private EhrOrganization organization;
    

	public EhrPosition getPosition() {
		return position;
	}

	public void setPosition(EhrPosition position) {
		this.position = position;
	}

	public EhrBaseData getBaseData() {
		return baseData;
	}

	public void setBaseData(EhrBaseData baseData) {
		this.baseData = baseData;
	}

	public EhrOrganization getOrganization() {
		return organization;
	}

	public void setOrganization(EhrOrganization organization) {
		this.organization = organization;
	}
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person_security_profile.profile_code
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    private String profileCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person_security_profile.personId
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    private Long personid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person_security_profile.security_switch
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    private Integer securitySwitch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person_security_profile.security_status
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    private Integer securityStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person_security_profile.security_org_account
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    private Long securityOrgAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person_security_profile.security_city
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    private String securityCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person_security_profile.security_type
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    private Long securityType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person_security_profile.security_create_type
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    private Integer securityCreateType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person_security_profile.security_account
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    private String securityAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person_security_profile.security_base
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    private BigDecimal securityBase;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person_security_profile.security_base
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    private BigDecimal securityOrgBase;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person_security_profile.security_starttime
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    private String securityStarttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person_security_profile.security_endtime_status
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    private Integer securityEndtimeStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person_security_profile.security_endtime
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    private String securityEndtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person_security_profile.security_activatetime
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    private String securityActivatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person_security_profile.gongjijin_switch
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    private Integer gongjijinSwitch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person_security_profile.gongjijin_status
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    private Integer gongjijinStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person_security_profile.gongjijin_base
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    private BigDecimal gongjijinBase;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person_security_profile.gongjijin_base
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    private BigDecimal gongjijinOrgBase;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person_security_profile.gongjijin_starttime
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    private String gongjijinStarttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person_security_profile.gongjijin_endtime_status
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    private Integer gongjijinEndtimeStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person_security_profile.gongjijin_endtime
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    private String gongjijinEndtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person_security_profile.gongjijin_activatetime
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    private String gongjijinActivatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person_security_profile.gongjijin_org_account
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    private Long gongjijinOrgAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person_security_profile.gongjijin_city
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    private String gongjijinCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person_security_profile.gongjijin_type
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    private Integer gongjijinType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person_security_profile.gongjijin_create_type
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    private Integer gongjijinCreateType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person_security_profile.gongjijin_account
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    private String gongjijinAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person_security_profile.create_time
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person_security_profile.is_deleted
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    private Integer isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person_security_profile.input_help_switch
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    private Integer inputHelpSwitch;
    
    //非表字段
    private String jobNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person_security_profile.profile_id
     *
     * @return the value of ehr_person_security_profile.profile_id
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    public Long getProfileId() {
        return profileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person_security_profile.profile_id
     *
     * @param profileId the value for ehr_person_security_profile.profile_id
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    public void setProfileId(Long profileId) {
        this.profileId = profileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person_security_profile.profile_code
     *
     * @return the value of ehr_person_security_profile.profile_code
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    public String getProfileCode() {
        return profileCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person_security_profile.profile_code
     *
     * @param profileCode the value for ehr_person_security_profile.profile_code
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    public void setProfileCode(String profileCode) {
        this.profileCode = profileCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person_security_profile.personId
     *
     * @return the value of ehr_person_security_profile.personId
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    public Long getPersonid() {
        return personid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person_security_profile.personId
     *
     * @param personid the value for ehr_person_security_profile.personId
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    public void setPersonid(Long personid) {
        this.personid = personid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person_security_profile.security_switch
     *
     * @return the value of ehr_person_security_profile.security_switch
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    public Integer getSecuritySwitch() {
        return securitySwitch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person_security_profile.security_switch
     *
     * @param securitySwitch the value for ehr_person_security_profile.security_switch
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    public void setSecuritySwitch(Integer securitySwitch) {
        this.securitySwitch = securitySwitch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person_security_profile.security_status
     *
     * @return the value of ehr_person_security_profile.security_status
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    public Integer getSecurityStatus() {
        return securityStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person_security_profile.security_status
     *
     * @param securityStatus the value for ehr_person_security_profile.security_status
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    public void setSecurityStatus(Integer securityStatus) {
        this.securityStatus = securityStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person_security_profile.security_org_account
     *
     * @return the value of ehr_person_security_profile.security_org_account
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    public Long getSecurityOrgAccount() {
        return securityOrgAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person_security_profile.security_org_account
     *
     * @param securityOrgAccount the value for ehr_person_security_profile.security_org_account
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    public void setSecurityOrgAccount(Long securityOrgAccount) {
        this.securityOrgAccount = securityOrgAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person_security_profile.security_city
     *
     * @return the value of ehr_person_security_profile.security_city
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    public String getSecurityCity() {
        return securityCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person_security_profile.security_city
     *
     * @param securityCity the value for ehr_person_security_profile.security_city
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    public void setSecurityCity(String securityCity) {
        this.securityCity = securityCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person_security_profile.security_type
     *
     * @return the value of ehr_person_security_profile.security_type
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    public Long getSecurityType() {
        return securityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person_security_profile.security_type
     *
     * @param securityType the value for ehr_person_security_profile.security_type
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    public void setSecurityType(Long securityType) {
        this.securityType = securityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person_security_profile.security_create_type
     *
     * @return the value of ehr_person_security_profile.security_create_type
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    public Integer getSecurityCreateType() {
        return securityCreateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person_security_profile.security_create_type
     *
     * @param securityCreateType the value for ehr_person_security_profile.security_create_type
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    public void setSecurityCreateType(Integer securityCreateType) {
        this.securityCreateType = securityCreateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person_security_profile.security_account
     *
     * @return the value of ehr_person_security_profile.security_account
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    public String getSecurityAccount() {
        return securityAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person_security_profile.security_account
     *
     * @param securityAccount the value for ehr_person_security_profile.security_account
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    public void setSecurityAccount(String securityAccount) {
        this.securityAccount = securityAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person_security_profile.security_base
     *
     * @return the value of ehr_person_security_profile.security_base
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    public BigDecimal getSecurityBase() {
        return securityBase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person_security_profile.security_base
     *
     * @param securityBase the value for ehr_person_security_profile.security_base
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    public void setSecurityBase(BigDecimal securityBase) {
        this.securityBase = securityBase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person_security_profile.security_starttime
     *
     * @return the value of ehr_person_security_profile.security_starttime
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    public String getSecurityStarttime() {
        return securityStarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person_security_profile.security_starttime
     *
     * @param securityStarttime the value for ehr_person_security_profile.security_starttime
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    public void setSecurityStarttime(String securityStarttime) {
        this.securityStarttime = securityStarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person_security_profile.security_endtime_status
     *
     * @return the value of ehr_person_security_profile.security_endtime_status
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    public Integer getSecurityEndtimeStatus() {
        return securityEndtimeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person_security_profile.security_endtime_status
     *
     * @param securityEndtimeStatus the value for ehr_person_security_profile.security_endtime_status
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    public void setSecurityEndtimeStatus(Integer securityEndtimeStatus) {
        this.securityEndtimeStatus = securityEndtimeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person_security_profile.security_endtime
     *
     * @return the value of ehr_person_security_profile.security_endtime
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    public String getSecurityEndtime() {
        return securityEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person_security_profile.security_endtime
     *
     * @param securityEndtime the value for ehr_person_security_profile.security_endtime
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    public void setSecurityEndtime(String securityEndtime) {
        this.securityEndtime = securityEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person_security_profile.security_activatetime
     *
     * @return the value of ehr_person_security_profile.security_activatetime
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    public String getSecurityActivatetime() {
        return securityActivatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person_security_profile.security_activatetime
     *
     * @param securityActivatetime the value for ehr_person_security_profile.security_activatetime
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    public void setSecurityActivatetime(String securityActivatetime) {
        this.securityActivatetime = securityActivatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person_security_profile.gongjijin_switch
     *
     * @return the value of ehr_person_security_profile.gongjijin_switch
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    public Integer getGongjijinSwitch() {
        return gongjijinSwitch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person_security_profile.gongjijin_switch
     *
     * @param gongjijinSwitch the value for ehr_person_security_profile.gongjijin_switch
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    public void setGongjijinSwitch(Integer gongjijinSwitch) {
        this.gongjijinSwitch = gongjijinSwitch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person_security_profile.gongjijin_status
     *
     * @return the value of ehr_person_security_profile.gongjijin_status
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    public Integer getGongjijinStatus() {
        return gongjijinStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person_security_profile.gongjijin_status
     *
     * @param gongjijinStatus the value for ehr_person_security_profile.gongjijin_status
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    public void setGongjijinStatus(Integer gongjijinStatus) {
        this.gongjijinStatus = gongjijinStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person_security_profile.gongjijin_base
     *
     * @return the value of ehr_person_security_profile.gongjijin_base
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    public BigDecimal getGongjijinBase() {
        return gongjijinBase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person_security_profile.gongjijin_base
     *
     * @param gongjijinBase the value for ehr_person_security_profile.gongjijin_base
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    public void setGongjijinBase(BigDecimal gongjijinBase) {
        this.gongjijinBase = gongjijinBase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person_security_profile.gongjijin_starttime
     *
     * @return the value of ehr_person_security_profile.gongjijin_starttime
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    public String getGongjijinStarttime() {
        return gongjijinStarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person_security_profile.gongjijin_starttime
     *
     * @param gongjijinStarttime the value for ehr_person_security_profile.gongjijin_starttime
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    public void setGongjijinStarttime(String gongjijinStarttime) {
        this.gongjijinStarttime = gongjijinStarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person_security_profile.gongjijin_endtime_status
     *
     * @return the value of ehr_person_security_profile.gongjijin_endtime_status
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    public Integer getGongjijinEndtimeStatus() {
        return gongjijinEndtimeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person_security_profile.gongjijin_endtime_status
     *
     * @param gongjijinEndtimeStatus the value for ehr_person_security_profile.gongjijin_endtime_status
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    public void setGongjijinEndtimeStatus(Integer gongjijinEndtimeStatus) {
        this.gongjijinEndtimeStatus = gongjijinEndtimeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person_security_profile.gongjijin_endtime
     *
     * @return the value of ehr_person_security_profile.gongjijin_endtime
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    public String getGongjijinEndtime() {
        return gongjijinEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person_security_profile.gongjijin_endtime
     *
     * @param gongjijinEndtime the value for ehr_person_security_profile.gongjijin_endtime
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    public void setGongjijinEndtime(String gongjijinEndtime) {
        this.gongjijinEndtime = gongjijinEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person_security_profile.gongjijin_activatetime
     *
     * @return the value of ehr_person_security_profile.gongjijin_activatetime
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    public String getGongjijinActivatetime() {
        return gongjijinActivatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person_security_profile.gongjijin_activatetime
     *
     * @param gongjijinActivatetime the value for ehr_person_security_profile.gongjijin_activatetime
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    public void setGongjijinActivatetime(String gongjijinActivatetime) {
        this.gongjijinActivatetime = gongjijinActivatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person_security_profile.gongjijin_org_account
     *
     * @return the value of ehr_person_security_profile.gongjijin_org_account
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    public Long getGongjijinOrgAccount() {
        return gongjijinOrgAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person_security_profile.gongjijin_org_account
     *
     * @param gongjijinOrgAccount the value for ehr_person_security_profile.gongjijin_org_account
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    public void setGongjijinOrgAccount(Long gongjijinOrgAccount) {
        this.gongjijinOrgAccount = gongjijinOrgAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person_security_profile.gongjijin_city
     *
     * @return the value of ehr_person_security_profile.gongjijin_city
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    public String getGongjijinCity() {
        return gongjijinCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person_security_profile.gongjijin_city
     *
     * @param gongjijinCity the value for ehr_person_security_profile.gongjijin_city
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    public void setGongjijinCity(String gongjijinCity) {
        this.gongjijinCity = gongjijinCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person_security_profile.gongjijin_type
     *
     * @return the value of ehr_person_security_profile.gongjijin_type
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    public Integer getGongjijinType() {
        return gongjijinType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person_security_profile.gongjijin_type
     *
     * @param gongjijinType the value for ehr_person_security_profile.gongjijin_type
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    public void setGongjijinType(Integer gongjijinType) {
        this.gongjijinType = gongjijinType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person_security_profile.gongjijin_create_type
     *
     * @return the value of ehr_person_security_profile.gongjijin_create_type
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    public Integer getGongjijinCreateType() {
        return gongjijinCreateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person_security_profile.gongjijin_create_type
     *
     * @param gongjijinCreateType the value for ehr_person_security_profile.gongjijin_create_type
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    public void setGongjijinCreateType(Integer gongjijinCreateType) {
        this.gongjijinCreateType = gongjijinCreateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person_security_profile.gongjijin_account
     *
     * @return the value of ehr_person_security_profile.gongjijin_account
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    public String getGongjijinAccount() {
        return gongjijinAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person_security_profile.gongjijin_account
     *
     * @param gongjijinAccount the value for ehr_person_security_profile.gongjijin_account
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    public void setGongjijinAccount(String gongjijinAccount) {
        this.gongjijinAccount = gongjijinAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person_security_profile.create_time
     *
     * @return the value of ehr_person_security_profile.create_time
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person_security_profile.create_time
     *
     * @param createTime the value for ehr_person_security_profile.create_time
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person_security_profile.is_deleted
     *
     * @return the value of ehr_person_security_profile.is_deleted
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person_security_profile.is_deleted
     *
     * @param isDeleted the value for ehr_person_security_profile.is_deleted
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person_security_profile.input_help_switch
     *
     * @return the value of ehr_person_security_profile.input_help_switch
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    public Integer getInputHelpSwitch() {
        return inputHelpSwitch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person_security_profile.input_help_switch
     *
     * @param inputHelpSwitch the value for ehr_person_security_profile.input_help_switch
     *
     * @mbggenerated Fri Apr 22 11:31:35 CST 2016
     */
    public void setInputHelpSwitch(Integer inputHelpSwitch) {
        this.inputHelpSwitch = inputHelpSwitch;
    }
  

	public String getDepartment() {
		return department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	public String getPost() {
		return post;
	}

	public void setPost(String post) {
		this.post = post;
	}

	public String getEmployeeNumber() {
		return employeeNumber;
	}

	public void setEmployeeNumber(String employeeNumber) {
		this.employeeNumber = employeeNumber;
	}

	public BigDecimal getSalary() {
		return salary;
	}

	public void setSalary(BigDecimal salary) {
		this.salary = salary;
	}
    //////////////////// 关联社保项目 ///////////////////
    private List <EhrSecurityItem> ehrSecurityItems;

	public List<EhrSecurityItem> getEhrSecurityItems() {
		return ehrSecurityItems;
	}

	public void setEhrSecurityItems(List<EhrSecurityItem> ehrSecurityItems) {
		this.ehrSecurityItems = ehrSecurityItems;
	}

	public BigDecimal getSecurityOrgBase() {
		return securityOrgBase;
	}

	public void setSecurityOrgBase(BigDecimal securityOrgBase) {
		this.securityOrgBase = securityOrgBase;
	}

	public BigDecimal getGongjijinOrgBase() {
		return gongjijinOrgBase;
	}

	public void setGongjijinOrgBase(BigDecimal gongjijinOrgBase) {
		this.gongjijinOrgBase = gongjijinOrgBase;
	}

	public String getJobNumber() {
		return jobNumber;
	}

	public void setJobNumber(String jobNumber) {
		this.jobNumber = jobNumber;
	}
	
}