package com.jabava.pojo.socialsecurity;

import java.math.BigDecimal;

public class SsPaymentBillDetail {
	public SsPaymentBillDetail(){
		
	}
	
	public SsPaymentBillDetail(Long sbGroupDetailId, BigDecimal ratioE, BigDecimal ratioP){
		this.sbGroupDetailId = sbGroupDetailId;
		this.ratioE = ratioE;
		this.ratioP = ratioP;
		this.bqNum = 0;
		this.bjNum = 0;
		this.bqBaseE = BigDecimal.ZERO;
		this.bjBaseE = BigDecimal.ZERO;
		this.bqBaseP = BigDecimal.ZERO;
		this.bjBaseP = BigDecimal.ZERO;
		this.bqAmountE = BigDecimal.ZERO;
		this.bjAmountE = BigDecimal.ZERO;
		this.bqAmountP = BigDecimal.ZERO;
		this.bjAmountP = BigDecimal.ZERO;
		this.subtotal = BigDecimal.ZERO;
	}
	
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_payment_bill_detail.id
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_payment_bill_detail.ss_payment_bill_id
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    private Long ssPaymentBillId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_payment_bill_detail.sb_group_detail_id
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    private Long sbGroupDetailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_payment_bill_detail.bq_num
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    private Integer bqNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_payment_bill_detail.bj_num
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    private Integer bjNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_payment_bill_detail.bq_base_e
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    private BigDecimal bqBaseE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_payment_bill_detail.bj_base_e
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    private BigDecimal bjBaseE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_payment_bill_detail.bq_base_p
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    private BigDecimal bqBaseP;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_payment_bill_detail.bj_base_p
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    private BigDecimal bjBaseP;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_payment_bill_detail.ratio_e
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    private BigDecimal ratioE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_payment_bill_detail.ratio_p
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    private BigDecimal ratioP;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_payment_bill_detail.bq_amount_e
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    private BigDecimal bqAmountE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_payment_bill_detail.bj_amount_e
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    private BigDecimal bjAmountE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_payment_bill_detail.bq_amount_p
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    private BigDecimal bqAmountP;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_payment_bill_detail.bj_amount_p
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    private BigDecimal bjAmountP;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_payment_bill_detail.subtotal
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    private BigDecimal subtotal;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_payment_bill_detail.id
     *
     * @return the value of ss_payment_bill_detail.id
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_payment_bill_detail.id
     *
     * @param id the value for ss_payment_bill_detail.id
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_payment_bill_detail.ss_payment_bill_id
     *
     * @return the value of ss_payment_bill_detail.ss_payment_bill_id
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public Long getSsPaymentBillId() {
        return ssPaymentBillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_payment_bill_detail.ss_payment_bill_id
     *
     * @param ssPaymentBillId the value for ss_payment_bill_detail.ss_payment_bill_id
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public void setSsPaymentBillId(Long ssPaymentBillId) {
        this.ssPaymentBillId = ssPaymentBillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_payment_bill_detail.sb_group_detail_id
     *
     * @return the value of ss_payment_bill_detail.sb_group_detail_id
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public Long getSbGroupDetailId() {
        return sbGroupDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_payment_bill_detail.sb_group_detail_id
     *
     * @param sbGroupDetailId the value for ss_payment_bill_detail.sb_group_detail_id
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public void setSbGroupDetailId(Long sbGroupDetailId) {
        this.sbGroupDetailId = sbGroupDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_payment_bill_detail.bq_num
     *
     * @return the value of ss_payment_bill_detail.bq_num
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public Integer getBqNum() {
        return bqNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_payment_bill_detail.bq_num
     *
     * @param bqNum the value for ss_payment_bill_detail.bq_num
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public void setBqNum(Integer bqNum) {
        this.bqNum = bqNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_payment_bill_detail.bj_num
     *
     * @return the value of ss_payment_bill_detail.bj_num
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public Integer getBjNum() {
        return bjNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_payment_bill_detail.bj_num
     *
     * @param bjNum the value for ss_payment_bill_detail.bj_num
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public void setBjNum(Integer bjNum) {
        this.bjNum = bjNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_payment_bill_detail.bq_base_e
     *
     * @return the value of ss_payment_bill_detail.bq_base_e
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public BigDecimal getBqBaseE() {
        return bqBaseE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_payment_bill_detail.bq_base_e
     *
     * @param bqBaseE the value for ss_payment_bill_detail.bq_base_e
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public void setBqBaseE(BigDecimal bqBaseE) {
        this.bqBaseE = bqBaseE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_payment_bill_detail.bj_base_e
     *
     * @return the value of ss_payment_bill_detail.bj_base_e
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public BigDecimal getBjBaseE() {
        return bjBaseE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_payment_bill_detail.bj_base_e
     *
     * @param bjBaseE the value for ss_payment_bill_detail.bj_base_e
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public void setBjBaseE(BigDecimal bjBaseE) {
        this.bjBaseE = bjBaseE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_payment_bill_detail.bq_base_p
     *
     * @return the value of ss_payment_bill_detail.bq_base_p
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public BigDecimal getBqBaseP() {
        return bqBaseP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_payment_bill_detail.bq_base_p
     *
     * @param bqBaseP the value for ss_payment_bill_detail.bq_base_p
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public void setBqBaseP(BigDecimal bqBaseP) {
        this.bqBaseP = bqBaseP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_payment_bill_detail.bj_base_p
     *
     * @return the value of ss_payment_bill_detail.bj_base_p
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public BigDecimal getBjBaseP() {
        return bjBaseP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_payment_bill_detail.bj_base_p
     *
     * @param bjBaseP the value for ss_payment_bill_detail.bj_base_p
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public void setBjBaseP(BigDecimal bjBaseP) {
        this.bjBaseP = bjBaseP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_payment_bill_detail.ratio_e
     *
     * @return the value of ss_payment_bill_detail.ratio_e
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public BigDecimal getRatioE() {
        return ratioE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_payment_bill_detail.ratio_e
     *
     * @param ratioE the value for ss_payment_bill_detail.ratio_e
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public void setRatioE(BigDecimal ratioE) {
        this.ratioE = ratioE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_payment_bill_detail.ratio_p
     *
     * @return the value of ss_payment_bill_detail.ratio_p
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public BigDecimal getRatioP() {
        return ratioP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_payment_bill_detail.ratio_p
     *
     * @param ratioP the value for ss_payment_bill_detail.ratio_p
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public void setRatioP(BigDecimal ratioP) {
        this.ratioP = ratioP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_payment_bill_detail.bq_amount_e
     *
     * @return the value of ss_payment_bill_detail.bq_amount_e
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public BigDecimal getBqAmountE() {
        return bqAmountE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_payment_bill_detail.bq_amount_e
     *
     * @param bqAmountE the value for ss_payment_bill_detail.bq_amount_e
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public void setBqAmountE(BigDecimal bqAmountE) {
        this.bqAmountE = bqAmountE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_payment_bill_detail.bj_amount_e
     *
     * @return the value of ss_payment_bill_detail.bj_amount_e
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public BigDecimal getBjAmountE() {
        return bjAmountE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_payment_bill_detail.bj_amount_e
     *
     * @param bjAmountE the value for ss_payment_bill_detail.bj_amount_e
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public void setBjAmountE(BigDecimal bjAmountE) {
        this.bjAmountE = bjAmountE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_payment_bill_detail.bq_amount_p
     *
     * @return the value of ss_payment_bill_detail.bq_amount_p
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public BigDecimal getBqAmountP() {
        return bqAmountP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_payment_bill_detail.bq_amount_p
     *
     * @param bqAmountP the value for ss_payment_bill_detail.bq_amount_p
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public void setBqAmountP(BigDecimal bqAmountP) {
        this.bqAmountP = bqAmountP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_payment_bill_detail.bj_amount_p
     *
     * @return the value of ss_payment_bill_detail.bj_amount_p
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public BigDecimal getBjAmountP() {
        return bjAmountP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_payment_bill_detail.bj_amount_p
     *
     * @param bjAmountP the value for ss_payment_bill_detail.bj_amount_p
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public void setBjAmountP(BigDecimal bjAmountP) {
        this.bjAmountP = bjAmountP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_payment_bill_detail.subtotal
     *
     * @return the value of ss_payment_bill_detail.subtotal
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public BigDecimal getSubtotal() {
        return subtotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_payment_bill_detail.subtotal
     *
     * @param subtotal the value for ss_payment_bill_detail.subtotal
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public void setSubtotal(BigDecimal subtotal) {
        this.subtotal = subtotal;
    }
}