package com.jabava.pojo.socialsecurity;

import java.math.BigDecimal;

public class SsPaymentBillPersonDetail {
	public SsPaymentBillPersonDetail(){
		
	}
	
	public SsPaymentBillPersonDetail(Long sbGroupDetailId){
		this.sbGroupDetailId = sbGroupDetailId;
		this.amountE = BigDecimal.ZERO;
		this.amountP = BigDecimal.ZERO;
		this.baseE = BigDecimal.ZERO;
		this.baseP = BigDecimal.ZERO;
		this.bjAmountE = BigDecimal.ZERO;
		this.bjAmountP = BigDecimal.ZERO;
		this.bjBaseE = BigDecimal.ZERO;
		this.bjBaseP = BigDecimal.ZERO;
		this.bjRatioE = BigDecimal.ZERO;
		this.bjRatioP = BigDecimal.ZERO;
		this.ratioE = BigDecimal.ZERO;
		this.ratioP = BigDecimal.ZERO;
	}
	
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_payment_bill_person_detail.id
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_payment_bill_person_detail.ss_payment_bill_person_id
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    private Long ssPaymentBillPersonId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_payment_bill_person_detail.sb_group_detail_id
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    private Long sbGroupDetailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_payment_bill_person_detail.base_e
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    private BigDecimal baseE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_payment_bill_person_detail.ratio_e
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    private BigDecimal ratioE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_payment_bill_person_detail.amount_e
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    private BigDecimal amountE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_payment_bill_person_detail.base_p
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    private BigDecimal baseP;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_payment_bill_person_detail.ratio_p
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    private BigDecimal ratioP;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_payment_bill_person_detail.amount_p
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    private BigDecimal amountP;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_payment_bill_person_detail.bj_month_start
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    private String bjMonthStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_payment_bill_person_detail.bj_month_end
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    private String bjMonthEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_payment_bill_person_detail.bj_month_num
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    private Integer bjMonthNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_payment_bill_person_detail.bj_base_e
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    private BigDecimal bjBaseE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_payment_bill_person_detail.bj_ratio_e
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    private BigDecimal bjRatioE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_payment_bill_person_detail.bj_amount_e
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    private BigDecimal bjAmountE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_payment_bill_person_detail.bj_base_p
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    private BigDecimal bjBaseP;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_payment_bill_person_detail.bj_ratio_p
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    private BigDecimal bjRatioP;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_payment_bill_person_detail.bj_amount_p
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    private BigDecimal bjAmountP;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_payment_bill_person_detail.id
     *
     * @return the value of ss_payment_bill_person_detail.id
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_payment_bill_person_detail.id
     *
     * @param id the value for ss_payment_bill_person_detail.id
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_payment_bill_person_detail.ss_payment_bill_person_id
     *
     * @return the value of ss_payment_bill_person_detail.ss_payment_bill_person_id
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public Long getSsPaymentBillPersonId() {
        return ssPaymentBillPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_payment_bill_person_detail.ss_payment_bill_person_id
     *
     * @param ssPaymentBillPersonId the value for ss_payment_bill_person_detail.ss_payment_bill_person_id
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public void setSsPaymentBillPersonId(Long ssPaymentBillPersonId) {
        this.ssPaymentBillPersonId = ssPaymentBillPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_payment_bill_person_detail.sb_group_detail_id
     *
     * @return the value of ss_payment_bill_person_detail.sb_group_detail_id
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public Long getSbGroupDetailId() {
        return sbGroupDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_payment_bill_person_detail.sb_group_detail_id
     *
     * @param sbGroupDetailId the value for ss_payment_bill_person_detail.sb_group_detail_id
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public void setSbGroupDetailId(Long sbGroupDetailId) {
        this.sbGroupDetailId = sbGroupDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_payment_bill_person_detail.base_e
     *
     * @return the value of ss_payment_bill_person_detail.base_e
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public BigDecimal getBaseE() {
        return baseE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_payment_bill_person_detail.base_e
     *
     * @param baseE the value for ss_payment_bill_person_detail.base_e
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public void setBaseE(BigDecimal baseE) {
        this.baseE = baseE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_payment_bill_person_detail.ratio_e
     *
     * @return the value of ss_payment_bill_person_detail.ratio_e
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public BigDecimal getRatioE() {
        return ratioE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_payment_bill_person_detail.ratio_e
     *
     * @param ratioE the value for ss_payment_bill_person_detail.ratio_e
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public void setRatioE(BigDecimal ratioE) {
        this.ratioE = ratioE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_payment_bill_person_detail.amount_e
     *
     * @return the value of ss_payment_bill_person_detail.amount_e
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public BigDecimal getAmountE() {
        return amountE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_payment_bill_person_detail.amount_e
     *
     * @param amountE the value for ss_payment_bill_person_detail.amount_e
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public void setAmountE(BigDecimal amountE) {
        this.amountE = amountE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_payment_bill_person_detail.base_p
     *
     * @return the value of ss_payment_bill_person_detail.base_p
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public BigDecimal getBaseP() {
        return baseP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_payment_bill_person_detail.base_p
     *
     * @param baseP the value for ss_payment_bill_person_detail.base_p
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public void setBaseP(BigDecimal baseP) {
        this.baseP = baseP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_payment_bill_person_detail.ratio_p
     *
     * @return the value of ss_payment_bill_person_detail.ratio_p
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public BigDecimal getRatioP() {
        return ratioP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_payment_bill_person_detail.ratio_p
     *
     * @param ratioP the value for ss_payment_bill_person_detail.ratio_p
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public void setRatioP(BigDecimal ratioP) {
        this.ratioP = ratioP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_payment_bill_person_detail.amount_p
     *
     * @return the value of ss_payment_bill_person_detail.amount_p
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public BigDecimal getAmountP() {
        return amountP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_payment_bill_person_detail.amount_p
     *
     * @param amountP the value for ss_payment_bill_person_detail.amount_p
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public void setAmountP(BigDecimal amountP) {
        this.amountP = amountP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_payment_bill_person_detail.bj_month_start
     *
     * @return the value of ss_payment_bill_person_detail.bj_month_start
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public String getBjMonthStart() {
        return bjMonthStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_payment_bill_person_detail.bj_month_start
     *
     * @param bjMonthStart the value for ss_payment_bill_person_detail.bj_month_start
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public void setBjMonthStart(String bjMonthStart) {
        this.bjMonthStart = bjMonthStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_payment_bill_person_detail.bj_month_end
     *
     * @return the value of ss_payment_bill_person_detail.bj_month_end
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public String getBjMonthEnd() {
        return bjMonthEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_payment_bill_person_detail.bj_month_end
     *
     * @param bjMonthEnd the value for ss_payment_bill_person_detail.bj_month_end
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public void setBjMonthEnd(String bjMonthEnd) {
        this.bjMonthEnd = bjMonthEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_payment_bill_person_detail.bj_month_num
     *
     * @return the value of ss_payment_bill_person_detail.bj_month_num
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public Integer getBjMonthNum() {
        return bjMonthNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_payment_bill_person_detail.bj_month_num
     *
     * @param bjMonthNum the value for ss_payment_bill_person_detail.bj_month_num
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public void setBjMonthNum(Integer bjMonthNum) {
        this.bjMonthNum = bjMonthNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_payment_bill_person_detail.bj_base_e
     *
     * @return the value of ss_payment_bill_person_detail.bj_base_e
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public BigDecimal getBjBaseE() {
        return bjBaseE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_payment_bill_person_detail.bj_base_e
     *
     * @param bjBaseE the value for ss_payment_bill_person_detail.bj_base_e
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public void setBjBaseE(BigDecimal bjBaseE) {
        this.bjBaseE = bjBaseE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_payment_bill_person_detail.bj_ratio_e
     *
     * @return the value of ss_payment_bill_person_detail.bj_ratio_e
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public BigDecimal getBjRatioE() {
        return bjRatioE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_payment_bill_person_detail.bj_ratio_e
     *
     * @param bjRatioE the value for ss_payment_bill_person_detail.bj_ratio_e
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public void setBjRatioE(BigDecimal bjRatioE) {
        this.bjRatioE = bjRatioE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_payment_bill_person_detail.bj_amount_e
     *
     * @return the value of ss_payment_bill_person_detail.bj_amount_e
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public BigDecimal getBjAmountE() {
        return bjAmountE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_payment_bill_person_detail.bj_amount_e
     *
     * @param bjAmountE the value for ss_payment_bill_person_detail.bj_amount_e
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public void setBjAmountE(BigDecimal bjAmountE) {
        this.bjAmountE = bjAmountE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_payment_bill_person_detail.bj_base_p
     *
     * @return the value of ss_payment_bill_person_detail.bj_base_p
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public BigDecimal getBjBaseP() {
        return bjBaseP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_payment_bill_person_detail.bj_base_p
     *
     * @param bjBaseP the value for ss_payment_bill_person_detail.bj_base_p
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public void setBjBaseP(BigDecimal bjBaseP) {
        this.bjBaseP = bjBaseP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_payment_bill_person_detail.bj_ratio_p
     *
     * @return the value of ss_payment_bill_person_detail.bj_ratio_p
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public BigDecimal getBjRatioP() {
        return bjRatioP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_payment_bill_person_detail.bj_ratio_p
     *
     * @param bjRatioP the value for ss_payment_bill_person_detail.bj_ratio_p
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public void setBjRatioP(BigDecimal bjRatioP) {
        this.bjRatioP = bjRatioP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_payment_bill_person_detail.bj_amount_p
     *
     * @return the value of ss_payment_bill_person_detail.bj_amount_p
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public BigDecimal getBjAmountP() {
        return bjAmountP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_payment_bill_person_detail.bj_amount_p
     *
     * @param bjAmountP the value for ss_payment_bill_person_detail.bj_amount_p
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    public void setBjAmountP(BigDecimal bjAmountP) {
        this.bjAmountP = bjAmountP;
    }
}