package com.jabava.pojo.socialsecurity;

import java.util.Date;
import java.util.List;

import com.jabava.pojo.manage.EhrPerson;
import com.jabava.pojo.policygroup.PolicyGroup;
import com.jabava.pojo.policygroup.SbGroup;
import com.jabava.pojo.tools.EhrCity;

public class SsSocialSecurityAccountVO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_social_security_account.social_security_account_id
     *
     * @mbggenerated
     */
    private Long socialSecurityAccountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_social_security_account.company_id
     *
     * @mbggenerated
     */
    private Long companyId;
    //参保地所在省份的ID
    private Long provinceId;
    //参保地
    private EhrCity city;
    //参保规则
    private String socialSecurityRuleShow;
    //参保地列表
    private List<EhrCity> cityList;
    //政策包列表
    private List<PolicyGroup> policyGroupList;
    //政策包组合列表
    private List<SbGroup> groupList;
    //政策组合包
    private SbGroup group;
    // 社保档案
    private EhrPersonSecurityProfile personSecurityProfile;
    //人员
    private  EhrPerson person;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_social_security_account.social_security_account_name
     *
     * @mbggenerated
     */
    private String socialSecurityAccountName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_social_security_account.location_city_id
     *
     * @mbggenerated
     */
    private Long locationCityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_social_security_account.social_security_code
     *
     * @mbggenerated
     */
    private String socialSecurityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_social_security_account.social_security_role
     *
     * @mbggenerated
     */
    private String socialSecurityRule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_social_security_account.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_social_security_account.create_user_id
     *
     * @mbggenerated
     */
    private Long createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_social_security_account.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_social_security_account.update_user_id
     *
     * @mbggenerated
     */
    private Long updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_social_security_account.update_date
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_social_security_account.is_deleted
     *
     * @mbggenerated
     */
    private Integer isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_social_security_account.social_security_account_id
     *
     * @return the value of ss_social_security_account.social_security_account_id
     *
     * @mbggenerated
     */
    public Long getSocialSecurityAccountId() {
        return socialSecurityAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_social_security_account.social_security_account_id
     *
     * @param socialSecurityAccountId the value for ss_social_security_account.social_security_account_id
     *
     * @mbggenerated
     */
    public void setSocialSecurityAccountId(Long socialSecurityAccountId) {
        this.socialSecurityAccountId = socialSecurityAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_social_security_account.company_id
     *
     * @return the value of ss_social_security_account.company_id
     *
     * @mbggenerated
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_social_security_account.company_id
     *
     * @param companyId the value for ss_social_security_account.company_id
     *
     * @mbggenerated
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_social_security_account.social_security_account_name
     *
     * @return the value of ss_social_security_account.social_security_account_name
     *
     * @mbggenerated
     */
    public String getSocialSecurityAccountName() {
        return socialSecurityAccountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_social_security_account.social_security_account_name
     *
     * @param socialSecurityAccountName the value for ss_social_security_account.social_security_account_name
     *
     * @mbggenerated
     */
    public void setSocialSecurityAccountName(String socialSecurityAccountName) {
        this.socialSecurityAccountName = socialSecurityAccountName == null ? null : socialSecurityAccountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_social_security_account.location_city_id
     *
     * @return the value of ss_social_security_account.location_city_id
     *
     * @mbggenerated
     */
    public Long getLocationCityId() {
        return locationCityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_social_security_account.location_city_id
     *
     * @param locationCityId the value for ss_social_security_account.location_city_id
     *
     * @mbggenerated
     */
    public void setLocationCityId(Long locationCityId) {
        this.locationCityId = locationCityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_social_security_account.social_security_code
     *
     * @return the value of ss_social_security_account.social_security_code
     *
     * @mbggenerated
     */
    public String getSocialSecurityCode() {
        return socialSecurityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_social_security_account.social_security_code
     *
     * @param socialSecurityCode the value for ss_social_security_account.social_security_code
     *
     * @mbggenerated
     */
    public void setSocialSecurityCode(String socialSecurityCode) {
        this.socialSecurityCode = socialSecurityCode == null ? null : socialSecurityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_social_security_account.social_security_role
     *
     * @return the value of ss_social_security_account.social_security_role
     *
     * @mbggenerated
     */
    public String getSocialSecurityRule() {
        return socialSecurityRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_social_security_account.social_security_role
     *
     * @param socialSecurityRule the value for ss_social_security_account.social_security_role
     *
     * @mbggenerated
     */
    public void setSocialSecurityRule(String socialSecurityRule) {
        this.socialSecurityRule = socialSecurityRule == null ? null : socialSecurityRule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_social_security_account.remark
     *
     * @return the value of ss_social_security_account.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_social_security_account.remark
     *
     * @param remark the value for ss_social_security_account.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_social_security_account.create_user_id
     *
     * @return the value of ss_social_security_account.create_user_id
     *
     * @mbggenerated
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_social_security_account.create_user_id
     *
     * @param createUserId the value for ss_social_security_account.create_user_id
     *
     * @mbggenerated
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_social_security_account.create_date
     *
     * @return the value of ss_social_security_account.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_social_security_account.create_date
     *
     * @param createDate the value for ss_social_security_account.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_social_security_account.update_user_id
     *
     * @return the value of ss_social_security_account.update_user_id
     *
     * @mbggenerated
     */
    public Long getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_social_security_account.update_user_id
     *
     * @param updateUserId the value for ss_social_security_account.update_user_id
     *
     * @mbggenerated
     */
    public void setUpdateUserId(Long updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_social_security_account.update_date
     *
     * @return the value of ss_social_security_account.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_social_security_account.update_date
     *
     * @param updateDate the value for ss_social_security_account.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_social_security_account.is_deleted
     *
     * @return the value of ss_social_security_account.is_deleted
     *
     * @mbggenerated
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_social_security_account.is_deleted
     *
     * @param isDeleted the value for ss_social_security_account.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

	public EhrCity getCity() {
		return city;
	}

	public void setCity(EhrCity city) {
		this.city = city;
	}

	public String getSocialSecurityRuleShow() {
		return socialSecurityRuleShow;
	}

	public void setSocialSecurityRuleShow(String socialSecurityRuleShow) {
		this.socialSecurityRuleShow = socialSecurityRuleShow;
	}

	public List<EhrCity> getCityList() {
		return cityList;
	}

	public void setCityList(List<EhrCity> cityList) {
		this.cityList = cityList;
	}

	public List<PolicyGroup> getPolicyGroupList() {
		return policyGroupList;
	}

	public void setPolicyGroupList(List<PolicyGroup> policyGroupList) {
		this.policyGroupList = policyGroupList;
	}

	public Long getProvinceId() {
		return provinceId;
	}

	public void setProvinceId(Long provinceId) {
		this.provinceId = provinceId;
	}

	public List<SbGroup> getGroupList() {
		return groupList;
	}

	public void setGroupList(List<SbGroup> groupList) {
		this.groupList = groupList;
	}

	public SbGroup getGroup() {
		return group;
	}

	public void setGroup(SbGroup group) {
		this.group = group;
	}

	public EhrPersonSecurityProfile getPersonSecurityProfile() {
		return personSecurityProfile;
	}

	public void setPersonSecurityProfile(
			EhrPersonSecurityProfile personSecurityProfile) {
		this.personSecurityProfile = personSecurityProfile;
	}

	public EhrPerson getPerson() {
		return person;
	}

	public void setPerson(EhrPerson person) {
		this.person = person;
	}
	
}