package com.jabava.pojo.manage;

public class EhrArgumentInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ehr_argument_info.ID
	 * @mbggenerated  Fri Dec 18 17:50:58 CST 2015
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ehr_argument_info.ARGUMENT_KEY
	 * @mbggenerated  Fri Dec 18 17:50:58 CST 2015
	 */
	private String argumentKey;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ehr_argument_info.ARGUMENT_VALUE
	 * @mbggenerated  Fri Dec 18 17:50:58 CST 2015
	 */
	private String argumentValue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ehr_argument_info.COMPANY_ID
	 * @mbggenerated  Fri Dec 18 17:50:58 CST 2015
	 */
	private Long companyId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ehr_argument_info.REMARK
	 * @mbggenerated  Fri Dec 18 17:50:58 CST 2015
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ehr_argument_info.ID
	 * @return  the value of ehr_argument_info.ID
	 * @mbggenerated  Fri Dec 18 17:50:58 CST 2015
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ehr_argument_info.ID
	 * @param id  the value for ehr_argument_info.ID
	 * @mbggenerated  Fri Dec 18 17:50:58 CST 2015
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ehr_argument_info.ARGUMENT_KEY
	 * @return  the value of ehr_argument_info.ARGUMENT_KEY
	 * @mbggenerated  Fri Dec 18 17:50:58 CST 2015
	 */
	public String getArgumentKey() {
		return argumentKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ehr_argument_info.ARGUMENT_KEY
	 * @param argumentKey  the value for ehr_argument_info.ARGUMENT_KEY
	 * @mbggenerated  Fri Dec 18 17:50:58 CST 2015
	 */
	public void setArgumentKey(String argumentKey) {
		this.argumentKey = argumentKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ehr_argument_info.ARGUMENT_VALUE
	 * @return  the value of ehr_argument_info.ARGUMENT_VALUE
	 * @mbggenerated  Fri Dec 18 17:50:58 CST 2015
	 */
	public String getArgumentValue() {
		return argumentValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ehr_argument_info.ARGUMENT_VALUE
	 * @param argumentValue  the value for ehr_argument_info.ARGUMENT_VALUE
	 * @mbggenerated  Fri Dec 18 17:50:58 CST 2015
	 */
	public void setArgumentValue(String argumentValue) {
		this.argumentValue = argumentValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ehr_argument_info.COMPANY_ID
	 * @return  the value of ehr_argument_info.COMPANY_ID
	 * @mbggenerated  Fri Dec 18 17:50:58 CST 2015
	 */
	public Long getCompanyId() {
		return companyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ehr_argument_info.COMPANY_ID
	 * @param companyId  the value for ehr_argument_info.COMPANY_ID
	 * @mbggenerated  Fri Dec 18 17:50:58 CST 2015
	 */
	public void setCompanyId(Long companyId) {
		this.companyId = companyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ehr_argument_info.REMARK
	 * @return  the value of ehr_argument_info.REMARK
	 * @mbggenerated  Fri Dec 18 17:50:58 CST 2015
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ehr_argument_info.REMARK
	 * @param remark  the value for ehr_argument_info.REMARK
	 * @mbggenerated  Fri Dec 18 17:50:58 CST 2015
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}
	
	public static String getColumnName(String colmun) {
		if ("id".equals(colmun)) {
			return "ID";
		} else if ("argumentKey".equals(colmun)) {
			return "ARGUMENT_KEY";
		} else if ("argumentValue".equals(colmun)) {
			return "ARGUMENT_VALUE";
		} else if ("remark".equals(colmun)) {
			return "REMARK";
		}
		return "ID";
	}
	
}