package com.jabava.pojo.manage;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

import com.jabava.pojo.employee.EhrPersonFile;
import com.jabava.pojo.employee.EhrPosition;

public class EhrPerson {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person.person_id
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private Long personId;
    //工作地
    private EhrBaseData workAddress;
    
    private EhrCompany company;
    private EhrUser user;
    
    private EhrPosition position;
    private String employeeNumber;
    

    public String getEmployeeNumber() {
		return employeeNumber;
	}

	public void setEmployeeNumber(String employeeNumber) {
		this.employeeNumber = employeeNumber;
	}

	public EhrPosition getPosition() {
		return position;
	}

	public void setPosition(EhrPosition position) {
		this.position = position;
	}

	public EhrUser getUser() {
		return user;
	}

	public void setUser(EhrUser user) {
		this.user = user;
	}

	public EhrCompany getCompany() {
		return company;
	}

	public void setCompany(EhrCompany company) {
		this.company = company;
	}

	public EhrBaseData getWorkAddress() {
		return workAddress;
	}

	public void setWorkAddress(EhrBaseData workAddress) {
		this.workAddress = workAddress;
	}


	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person.company_id
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private Long companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person.organization_id
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private Long organizationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person.post_id
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private Long postId; 

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person.cost_id
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private Long costId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person.job_number
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private String jobNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person.employee_name
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private String employeeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person.employee_photo
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private String employeePhoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person.employment_type
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private String employmentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person.rank_id
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private Long rankId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person.key_person
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private Integer keyPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person.sex
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person.report_object
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private String reportObject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person.entry_date
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private Date entryDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person.positive_date
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private Date positiveDate;
    private String positiveDate1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person.in_company_time
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private Byte inCompanyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person.firstjob_date
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private Date firstjobDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person.birth_date
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private Date birthDate;
    private String birthDate1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person.age
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person.cert_type
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private Integer certType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person.cert_id
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private String certId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person.bank_name
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private String bankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person.salary_card
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private String salaryCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person.marital
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private Integer marital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person.degree
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private String degree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person.education
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private String education;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person.study_abroad
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private Byte studyAbroad;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person.work_location
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private String workLocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person.payroll_location
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private String payrollLocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person.register_location
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private String registerLocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person.social_security_location
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private String socialSecurityLocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person.register_type
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private Integer registerType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person.birth_place
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private String birthPlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person.nationality
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private String nationality;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person.mobile
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person.phone
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person.Email
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person.contact_address
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private String contactAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person.family_address
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private String familyAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person.post_code
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private String postCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person.is_payroll_flag
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private Byte isPayrollFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person.file_location
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private String fileLocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person.is_foreign
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private Integer isForeign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person.left_date
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private Date leftDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person.left_cause
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private String leftCause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person.expire_date
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private Date expireDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person.memo
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person.create_user_id
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private Long createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person.create_user_name
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private String createUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person.create_date
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person.last_modify_user_id
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private Long lastModifyUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person.last_modify_user_name
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private String lastModifyUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person.last_modify_date
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private Date lastModifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person.status
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person.employee_group
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private String employeeGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person.team
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private Long team;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person.is_workplace
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private Byte isWorkplace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person.resume
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private String resume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person.subbank
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private String subbank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person.recruit
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private String recruit;
    
    private String personPassword;
    
    private String originPlace;    
    
    private int isDeleted;
    
    private String politicsStatus;
    
    private String referrer;
    
    /**
     * 非数据库字段
     */
    
    private String post;
    
    private String cost;
    
    private String org;
    
    private String totalCode;
    
    private Date entryDateStart;
    
    private Date entryDateEnd;
    
    private Date leftDateStart;
    
    private Date leftDateEnd;
    
    private Date positiveDateStart;
    
    private Date positiveDateEnd;
    
    private Date expireDateStart;
    
    private Date expireDateEnd;
    
    private String certificate;
    
    private String costcode;
    
    private String where;
    
    private String distinguish;
    
    private Integer isOpen;//添加员工时，用于区分是否发送邮件和短信
    
    private String companyName;
    
    private String firstjobDate1;
    
    private List<EhrPersonFile> certTypeUrl;//证件类型电子版图片
    private List<EhrPersonFile> resumeUrl;//电子简历图片
    private List<EhrPersonFile> educationUrl;//学历证明图片
    private List<EhrPersonFile> residenceUrl;//户口薄图片
    private List<EhrPersonFile> jobpostUrl;//离职证明图片
    private List<EhrPersonFile> healthUrl;//健康证明图片
    private List<EhrPersonFile> salaryUrl;//薪资证明图片
    
    
	public String getFirstjobDate1() {
		return firstjobDate1;
	}

	public void setFirstjobDate1(String firstjobDate1) {
		this.firstjobDate1 = firstjobDate1;
	}

	public String getPositiveDate1() {
		return positiveDate1;
	}

	public void setPositiveDate1(String positiveDate1) {
		this.positiveDate1 = positiveDate1;
	}

	public String getBirthDate1() {
		return birthDate1;
	}

	public void setBirthDate1(String birthDate1) {
		this.birthDate1 = birthDate1;
	}

	public String getCompanyName() {
		return companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	public String getTotalCode() {
		return totalCode;
	}

	public void setTotalCode(String totalCode) {
		this.totalCode = totalCode;
	}

	public Date getEntryDateStart() {
		return entryDateStart;
	}

	public void setEntryDateStart(Date entryDateStart) {
		this.entryDateStart = entryDateStart;
	}

	public Date getEntryDateEnd() {
		return entryDateEnd;
	}

	public void setEntryDateEnd(Date entryDateEnd) {
		this.entryDateEnd = entryDateEnd;
	}

	public Date getLeftDateStart() {
		return leftDateStart;
	}

	public void setLeftDateStart(Date leftDateStart) {
		this.leftDateStart = leftDateStart;
	}

	public Date getLeftDateEnd() {
		return leftDateEnd;
	}

	public void setLeftDateEnd(Date leftDateEnd) {
		this.leftDateEnd = leftDateEnd;
	}

	public Date getPositiveDateStart() {
		return positiveDateStart;
	}

	public void setPositiveDateStart(Date positiveDateStart) {
		this.positiveDateStart = positiveDateStart;
	}

	public Date getPositiveDateEnd() {
		return positiveDateEnd;
	}

	public void setPositiveDateEnd(Date positiveDateEnd) {
		this.positiveDateEnd = positiveDateEnd;
	}

	public Date getExpireDateStart() {
		return expireDateStart;
	}

	public void setExpireDateStart(Date expireDateStart) {
		this.expireDateStart = expireDateStart;
	}

	public Date getExpireDateEnd() {
		return expireDateEnd;
	}

	public void setExpireDateEnd(Date expireDateEnd) {
		this.expireDateEnd = expireDateEnd;
	}

	public String getCertificate() {
		return certificate;
	}

	public void setCertificate(String certificate) {
		this.certificate = certificate;
	}

	public String getCostcode() {
		return costcode;
	}

	public void setCostcode(String costcode) {
		this.costcode = costcode;
	}

	public String getWhere() {
		return where;
	}

	public void setWhere(String where) {
		this.where = where;
	}

	public String getDistinguish() {
		return distinguish;
	}

	public void setDistinguish(String distinguish) {
		this.distinguish = distinguish;
	}

	public Integer getIsOpen() {
		return isOpen;
	}

	public void setIsOpen(Integer isOpen) {
		this.isOpen = isOpen;
	}


	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person.person_id
     *
     * @return the value of ehr_person.person_id
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public Long getPersonId() {
        return personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person.person_id
     *
     * @param personId the value for ehr_person.person_id
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setPersonId(Long personId) {
        this.personId = personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person.company_id
     *
     * @return the value of ehr_person.company_id
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person.company_id
     *
     * @param companyId the value for ehr_person.company_id
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person.organization_id
     *
     * @return the value of ehr_person.organization_id
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public Long getOrganizationId() {
        return organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person.organization_id
     *
     * @param organizationId the value for ehr_person.organization_id
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setOrganizationId(Long organizationId) {
        this.organizationId = organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person.post_id
     *
     * @return the value of ehr_person.post_id
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public Long getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person.post_id
     *
     * @param postId the value for ehr_person.post_id
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setPostId(Long postId) {
        this.postId = postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person.cost_id
     *
     * @return the value of ehr_person.cost_id
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public Long getCostId() {
        return costId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person.cost_id
     *
     * @param costId the value for ehr_person.cost_id
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setCostId(Long costId) {
        this.costId = costId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person.job_number
     *
     * @return the value of ehr_person.job_number
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public String getJobNumber() {
        return jobNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person.job_number
     *
     * @param jobNumber the value for ehr_person.job_number
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setJobNumber(String jobNumber) {
        this.jobNumber = jobNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person.employee_name
     *
     * @return the value of ehr_person.employee_name
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public String getEmployeeName() {
        return employeeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person.employee_name
     *
     * @param employeeName the value for ehr_person.employee_name
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setEmployeeName(String employeeName) {
        this.employeeName = employeeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person.employee_photo
     *
     * @return the value of ehr_person.employee_photo
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public String getEmployeePhoto() {
        return employeePhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person.employee_photo
     *
     * @param employeePhoto the value for ehr_person.employee_photo
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setEmployeePhoto(String employeePhoto) {
        this.employeePhoto = employeePhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person.employment_type
     *
     * @return the value of ehr_person.employment_type
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public String getEmploymentType() {
        return employmentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person.employment_type
     *
     * @param employmentType the value for ehr_person.employment_type
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setEmploymentType(String employmentType) {
        this.employmentType = employmentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person.rank_id
     *
     * @return the value of ehr_person.rank_id
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public Long getRankId() {
        return rankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person.rank_id
     *
     * @param rankId the value for ehr_person.rank_id
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setRankId(Long rankId) {
        this.rankId = rankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person.key_person
     *
     * @return the value of ehr_person.key_person
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public Integer getKeyPerson() {
        return keyPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person.key_person
     *
     * @param keyPerson the value for ehr_person.key_person
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setKeyPerson(Integer keyPerson) {
        this.keyPerson = keyPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person.sex
     *
     * @return the value of ehr_person.sex
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person.sex
     *
     * @param sex the value for ehr_person.sex
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person.report_object
     *
     * @return the value of ehr_person.report_object
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public String getReportObject() {
        return reportObject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person.report_object
     *
     * @param reportObject the value for ehr_person.report_object
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setReportObject(String reportObject) {
        this.reportObject = reportObject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person.entry_date
     *
     * @return the value of ehr_person.entry_date
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public Date getEntryDate() {
        return entryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person.entry_date
     *
     * @param entryDate the value for ehr_person.entry_date
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setEntryDate(Date entryDate) {
        this.entryDate = entryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person.positive_date
     *
     * @return the value of ehr_person.positive_date
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public Date getPositiveDate() {
        return positiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person.positive_date
     *
     * @param positiveDate the value for ehr_person.positive_date
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setPositiveDate(Date positiveDate) {
        this.positiveDate = positiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person.in_company_time
     *
     * @return the value of ehr_person.in_company_time
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public Byte getInCompanyTime() {
        return inCompanyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person.in_company_time
     *
     * @param inCompanyTime the value for ehr_person.in_company_time
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setInCompanyTime(Byte inCompanyTime) {
        this.inCompanyTime = inCompanyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person.firstjob_date
     *
     * @return the value of ehr_person.firstjob_date
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public Date getFirstjobDate() {
        return firstjobDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person.firstjob_date
     *
     * @param firstjobDate the value for ehr_person.firstjob_date
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setFirstjobDate(Date firstjobDate) {
        this.firstjobDate = firstjobDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person.birth_date
     *
     * @return the value of ehr_person.birth_date
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public Date getBirthDate() {
        return birthDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person.birth_date
     *
     * @param birthDate the value for ehr_person.birth_date
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person.age
     *
     * @return the value of ehr_person.age
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person.age
     *
     * @param age the value for ehr_person.age
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person.cert_type
     *
     * @return the value of ehr_person.cert_type
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public Integer getCertType() {
        return certType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person.cert_type
     *
     * @param certType the value for ehr_person.cert_type
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setCertType(Integer certType) {
        this.certType = certType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person.cert_id
     *
     * @return the value of ehr_person.cert_id
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public String getCertId() {
        return certId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person.cert_id
     *
     * @param certId the value for ehr_person.cert_id
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setCertId(String certId) {
        this.certId = certId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person.bank_name
     *
     * @return the value of ehr_person.bank_name
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */ 
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person.bank_name
     *
     * @param bankName the value for ehr_person.bank_name
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person.salary_card
     *
     * @return the value of ehr_person.salary_card
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public String getSalaryCard() {
        return salaryCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person.salary_card
     *
     * @param salaryCard the value for ehr_person.salary_card
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setSalaryCard(String salaryCard) {
        this.salaryCard = salaryCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person.marital
     *
     * @return the value of ehr_person.marital
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public Integer getMarital() {
        return marital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person.marital
     *
     * @param marital the value for ehr_person.marital
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setMarital(Integer marital) {
        this.marital = marital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person.degree
     *
     * @return the value of ehr_person.degree
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public String getDegree() {
        return degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person.degree
     *
     * @param degree the value for ehr_person.degree
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setDegree(String degree) {
        this.degree = degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person.education
     *
     * @return the value of ehr_person.education
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person.education
     *
     * @param education the value for ehr_person.education
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setEducation(String education) {
        this.education = education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person.study_abroad
     *
     * @return the value of ehr_person.study_abroad
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public Byte getStudyAbroad() {
        return studyAbroad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person.study_abroad
     *
     * @param studyAbroad the value for ehr_person.study_abroad
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setStudyAbroad(Byte studyAbroad) {
        this.studyAbroad = studyAbroad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person.work_location
     *
     * @return the value of ehr_person.work_location
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public String getWorkLocation() {
        return workLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person.work_location
     *
     * @param workLocation the value for ehr_person.work_location
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setWorkLocation(String workLocation) {
        this.workLocation = workLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person.payroll_location
     *
     * @return the value of ehr_person.payroll_location
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public String getPayrollLocation() {
        return payrollLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person.payroll_location
     *
     * @param payrollLocation the value for ehr_person.payroll_location
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setPayrollLocation(String payrollLocation) {
        this.payrollLocation = payrollLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person.register_location
     *
     * @return the value of ehr_person.register_location
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public String getRegisterLocation() {
        return registerLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person.register_location
     *
     * @param registerLocation the value for ehr_person.register_location
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setRegisterLocation(String registerLocation) {
        this.registerLocation = registerLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person.social_security_location
     *
     * @return the value of ehr_person.social_security_location
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public String getSocialSecurityLocation() {
        return socialSecurityLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person.social_security_location
     *
     * @param socialSecurityLocation the value for ehr_person.social_security_location
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setSocialSecurityLocation(String socialSecurityLocation) {
        this.socialSecurityLocation = socialSecurityLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person.register_type
     *
     * @return the value of ehr_person.register_type
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public Integer getRegisterType() {
        return registerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person.register_type
     *
     * @param registerType the value for ehr_person.register_type
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setRegisterType(Integer registerType) {
        this.registerType = registerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person.birth_place
     *
     * @return the value of ehr_person.birth_place
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public String getBirthPlace() {
        return birthPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person.birth_place
     *
     * @param birthPlace the value for ehr_person.birth_place
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setBirthPlace(String birthPlace) {
        this.birthPlace = birthPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person.nationality
     *
     * @return the value of ehr_person.nationality
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public String getNationality() {
        return nationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person.nationality
     *
     * @param nationality the value for ehr_person.nationality
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setNationality(String nationality) {
        this.nationality = nationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person.mobile
     *
     * @return the value of ehr_person.mobile
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person.mobile
     *
     * @param mobile the value for ehr_person.mobile
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person.phone
     *
     * @return the value of ehr_person.phone
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person.phone
     *
     * @param phone the value for ehr_person.phone
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person.Email
     *
     * @return the value of ehr_person.Email
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person.Email
     *
     * @param email the value for ehr_person.Email
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person.contact_address
     *
     * @return the value of ehr_person.contact_address
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public String getContactAddress() {
        return contactAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person.contact_address
     *
     * @param contactAddress the value for ehr_person.contact_address
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setContactAddress(String contactAddress) {
        this.contactAddress = contactAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person.family_address
     *
     * @return the value of ehr_person.family_address
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public String getFamilyAddress() {
        return familyAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person.family_address
     *
     * @param familyAddress the value for ehr_person.family_address
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setFamilyAddress(String familyAddress) {
        this.familyAddress = familyAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person.post_code
     *
     * @return the value of ehr_person.post_code
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person.post_code
     *
     * @param postCode the value for ehr_person.post_code
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setPostCode(String postCode) {
        this.postCode = postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person.is_payroll_flag
     *
     * @return the value of ehr_person.is_payroll_flag
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public Byte getIsPayrollFlag() {
        return isPayrollFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person.is_payroll_flag
     *
     * @param isPayrollFlag the value for ehr_person.is_payroll_flag
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setIsPayrollFlag(Byte isPayrollFlag) {
        this.isPayrollFlag = isPayrollFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person.file_location
     *
     * @return the value of ehr_person.file_location
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public String getFileLocation() {
        return fileLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person.file_location
     *
     * @param fileLocation the value for ehr_person.file_location
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setFileLocation(String fileLocation) {
        this.fileLocation = fileLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person.is_foreign
     *
     * @return the value of ehr_person.is_foreign
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public Integer getIsForeign() {
        return isForeign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person.is_foreign
     *
     * @param isForeign the value for ehr_person.is_foreign
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setIsForeign(Integer isForeign) {
        this.isForeign = isForeign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person.left_date
     *
     * @return the value of ehr_person.left_date
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public Date getLeftDate() {
        return leftDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person.left_date
     *
     * @param leftDate the value for ehr_person.left_date
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setLeftDate(Date leftDate) {
        this.leftDate = leftDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person.left_cause
     *
     * @return the value of ehr_person.left_cause
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public String getLeftCause() {
        return leftCause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person.left_cause
     *
     * @param leftCause the value for ehr_person.left_cause
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setLeftCause(String leftCause) {
        this.leftCause = leftCause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person.expire_date
     *
     * @return the value of ehr_person.expire_date
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public Date getExpireDate() {
        return expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person.expire_date
     *
     * @param expireDate the value for ehr_person.expire_date
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setExpireDate(Date expireDate) {
        this.expireDate = expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person.memo
     *
     * @return the value of ehr_person.memo
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person.memo
     *
     * @param memo the value for ehr_person.memo
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setMemo(String memo) {
        this.memo = memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person.create_user_id
     *
     * @return the value of ehr_person.create_user_id
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person.create_user_id
     *
     * @param createUserId the value for ehr_person.create_user_id
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person.create_user_name
     *
     * @return the value of ehr_person.create_user_name
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public String getCreateUserName() {
        return createUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person.create_user_name
     *
     * @param createUserName the value for ehr_person.create_user_name
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setCreateUserName(String createUserName) {
        this.createUserName = createUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person.create_date
     *
     * @return the value of ehr_person.create_date
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person.create_date
     *
     * @param createDate the value for ehr_person.create_date
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person.last_modify_user_id
     *
     * @return the value of ehr_person.last_modify_user_id
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public Long getLastModifyUserId() {
        return lastModifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person.last_modify_user_id
     *
     * @param lastModifyUserId the value for ehr_person.last_modify_user_id
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setLastModifyUserId(Long lastModifyUserId) {
        this.lastModifyUserId = lastModifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person.last_modify_user_name
     *
     * @return the value of ehr_person.last_modify_user_name
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public String getLastModifyUserName() {
        return lastModifyUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person.last_modify_user_name
     *
     * @param lastModifyUserName the value for ehr_person.last_modify_user_name
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setLastModifyUserName(String lastModifyUserName) {
        this.lastModifyUserName = lastModifyUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person.last_modify_date
     *
     * @return the value of ehr_person.last_modify_date
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public Date getLastModifyDate() {
        return lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person.last_modify_date
     *
     * @param lastModifyDate the value for ehr_person.last_modify_date
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setLastModifyDate(Date lastModifyDate) {
        this.lastModifyDate = lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person.status
     *
     * @return the value of ehr_person.status
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person.status
     *
     * @param status the value for ehr_person.status
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setStatus(Integer status){
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person.employee_group
     *
     * @return the value of ehr_person.employee_group
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public String getEmployeeGroup() {
        return employeeGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person.employee_group
     *
     * @param employeeGroup the value for ehr_person.employee_group
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setEmployeeGroup(String employeeGroup) {
        this.employeeGroup = employeeGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person.team
     *
     * @return the value of ehr_person.team
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public Long getTeam() {
        return team;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person.team
     *
     * @param team the value for ehr_person.team
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setTeam(Long team) {
        this.team = team;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person.is_workplace
     *
     * @return the value of ehr_person.is_workplace
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public Byte getIsWorkplace() {
        return isWorkplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person.is_workplace
     *
     * @param isWorkplace the value for ehr_person.is_workplace
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setIsWorkplace(Byte isWorkplace) {
        this.isWorkplace = isWorkplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person.resume
     *
     * @return the value of ehr_person.resume
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public String getResume() {
        return resume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person.resume
     *
     * @param resume the value for ehr_person.resume
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setResume(String resume) {
        this.resume = resume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person.subbank
     *
     * @return the value of ehr_person.subbank
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public String getSubbank() {
        return subbank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person.subbank
     *
     * @param subbank the value for ehr_person.subbank
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setSubbank(String subbank) {
        this.subbank = subbank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person.recruit
     *
     * @return the value of ehr_person.recruit
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public String getRecruit() {
        return recruit;
    }

    public String getOriginPlace() {
		return originPlace;
	}

	public void setOriginPlace(String originPlace) {
		this.originPlace = originPlace;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person.recruit
     *
     * @param recruit the value for ehr_person.recruit
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setRecruit(String recruit) {
        this.recruit = recruit;
    }

	public String getPersonPassword() {
		return personPassword;
	}

	public void setPersonPassword(String personPassword) {
		this.personPassword = personPassword;
	}

	public String getPost() {
		return post;
	}

	public void setPost(String post) {
		this.post = post;
	}

	public String getCost() {
		return cost;
	}

	public void setCost(String cost) {
		this.cost = cost;
	}

	public String getOrg() {
		return org;
	}

	public void setOrg(String org) {
		this.org = org;
	}

	public int getIsDeleted() {
		return isDeleted;
	}

	public void setIsDeleted(int isDeleted) {
		this.isDeleted = isDeleted;
	}

	public String getPoliticsStatus() {
		return politicsStatus;
	}

	public void setPoliticsStatus(String politicsStatus) {
		this.politicsStatus = politicsStatus;
	}

	public String getReferrer() {
		return referrer;
	}

	public void setReferrer(String referrer) {
		this.referrer = referrer;
	}

	public List<EhrPersonFile> getCertTypeUrl() {
		return certTypeUrl;
	}

	public void setCertTypeUrl(List<EhrPersonFile> certTypeUrl) {
		this.certTypeUrl = certTypeUrl;
	}

	public List<EhrPersonFile> getResumeUrl() {
		return resumeUrl;
	}

	public void setResumeUrl(List<EhrPersonFile> resumeUrl) {
		this.resumeUrl = resumeUrl;
	}

	public List<EhrPersonFile> getEducationUrl() {
		return educationUrl;
	}

	public void setEducationUrl(List<EhrPersonFile> educationUrl) {
		this.educationUrl = educationUrl;
	}

	public List<EhrPersonFile> getResidenceUrl() {
		return residenceUrl;
	}

	public void setResidenceUrl(List<EhrPersonFile> residenceUrl) {
		this.residenceUrl = residenceUrl;
	}

	public List<EhrPersonFile> getJobpostUrl() {
		return jobpostUrl;
	}

	public void setJobpostUrl(List<EhrPersonFile> jobpostUrl) {
		this.jobpostUrl = jobpostUrl;
	}

	public List<EhrPersonFile> getHealthUrl() {
		return healthUrl;
	}

	public void setHealthUrl(List<EhrPersonFile> healthUrl) {
		this.healthUrl = healthUrl;
	}

	public List<EhrPersonFile> getSalaryUrl() {
		return salaryUrl;
	}

	public void setSalaryUrl(List<EhrPersonFile> salaryUrl) {
		this.salaryUrl = salaryUrl;
	}

	

	public static String getColumnName(String colmun) {
		if ("personId".equals(colmun)) {
			return "person_id";
		} else if ("jobNumber".equals(colmun)) {
			return "job_number";
		} else if ("employeeName".equals(colmun)) {
			return "employee_name";
		} else if ("organizationId".equals(colmun)||"org".equals(colmun)) {
			return "organization_id";
		} else if ("postId".equals(colmun)||"post".equals(colmun)) {
			return "post_id";
		} else if ("mobile".equals(colmun)) {
			return "mobile";
		} else if ("email".equals(colmun)) {
			return "email";
		}
		return "job_number";
	}
    

public String getCol(int ol)
{
	SimpleDateFormat simpledate = new SimpleDateFormat("yyyy-MM-dd");
	switch (ol)
	{
	case 0:
		return this.getPersonId().toString();
	case 1:
		return (this.getCompanyId()==null)?"":this.getCompanyId().toString();
	case 2:
		return (this.getOrganizationId()==null)?"":this.getOrganizationId().toString();
	case 5:
		return (this.getPostId()==null)?"":this.getPostId().toString();
	case 6:
		return (this.getCostId()==null)?"":this.getCostId().toString();
	case 7:
		return (this.getCost()==null)?"":this.getCost().toString();
	case 8:
		return (this.getJobNumber()==null)?"":this.getJobNumber().toString();	
	case 9:
		return (this.getEmployeeName()==null)?"":this.getEmployeeName().toString();
	case 10:
		return (this.getEmploymentType()==null)?"":this.getEmploymentType().toString();
	case 11:
		return (this.getRankId()==null)?"":this.getRankId().toString();	
	case 12:
		return (this.getKeyPerson()==null)?"":this.getKeyPerson().toString();
	case 13:
		return (this.getSex()==null)?"":this.getSex().toString();
	case 14:
		return (this.getReportObject()==null)?"":this.getReportObject().toString();	
	case 15:
		return (this.getEntryDate()==null)?"":simpledate.format(this.getEntryDate());
	case 16:
		return (this.getPositiveDate()==null)?"":simpledate.format(this.getPositiveDate());
	case 17:
		return (this.getInCompanyTime()==null)?"":this.getInCompanyTime().toString();	
	case 18:
		return (this.getFirstjobDate()==null)?"":simpledate.format(this.getFirstjobDate());
	case 19:
		return (this.getBirthDate()==null)?"":simpledate.format(this.getBirthDate());
	case 20:
		return (this.getAge()==null)?"":this.getAge().toString();	
	case 21:
		return (this.getCertType()==null)?"":this.getCertType().toString();
	case 22:
		return (this.getCertId()==null)?"":this.getCertId().toString();
	case 23:
		return (this.getBankName()==null)?"":this.getBankName();
	case 24:
		return (this.getSalaryCard()==null)?"":this.getSalaryCard().toString();
	case 25:
		return (this.getMarital()==null)?"":this.getMarital().toString();
	case 26:
		return (this.getDegree()==null)?"":this.getDegree().toString();
	case 27:
		return (this.getEducation()==null)?"":this.getEducation().toString();
	case 28:
		return (this.getStudyAbroad()==null)?"":this.getStudyAbroad().toString();
	case 29:
		return (this.getWorkLocation()==null)?"":this.getWorkLocation().toString();	
	case 30:
		return (this.getPayrollLocation()==null)?"":this.getPayrollLocation().toString();
	case 31:
		return (this.getRegisterLocation()==null)?"":this.getRegisterLocation().toString();
	case 32:
		return (this.getSocialSecurityLocation()==null)?"":this.getSocialSecurityLocation().toString();	
	case 33:
		return (this.getRegisterType()==null)?"":this.getRegisterType().toString();
	case 34:
		return (this.getBirthPlace()==null)?"":this.getBirthPlace().toString();
	case 35:
		return (this.getNationality()==null)?"":this.getNationality().toString();	
	case 36:
		return (this.getMobile()==null)?"":this.getMobile().toString();
	case 37:
		return (this.getPhone()==null)?"":this.getPhone().toString();
	case 38:
		return (this.getEmail()==null)?"":this.getEmail().toString();	
	case 39:
		return (this.getContactAddress()==null)?"":this.getContactAddress().toString();
	case 40:
		return (this.getFamilyAddress()==null)?"":this.getFamilyAddress().toString();
	case 41:
		return (this.getPostCode()==null)?"":this.getPostCode().toString();	
	case 42:
		return (this.getIsPayrollFlag()==null)?"":this.getIsPayrollFlag().toString();
	case 43:
		return (this.getFileLocation()==null)?"":this.getFileLocation().toString();
	case 44:
		return (this.getIsForeign()==null)?"":this.getIsForeign().toString();
	case 45:
		return (this.getLeftDate()==null)?"":simpledate.format(this.getLeftDate());	
	case 46:
		return (this.getLeftCause()==null)?"":this.getLeftCause().toString();
	case 47:
		return (this.getExpireDate()==null)?"":simpledate.format(this.getExpireDate());
	case 48:
		return (this.getMemo()==null)?"":this.getMemo().toString();
	case 49:
		return (this.getEmployeeGroup()==null)?"":this.getEmployeeGroup().toString();
	default:
		return "";
	}
}
}