package com.jabava.pojo.manage;

public class EhrPersonHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person_history.person_history_id
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private Long personHistoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person_history.organization_detail_history_id
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private Long organizationDetailHistoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person_history.organization_id
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private Long organizationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person_history.person_id
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private Long personId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person_history.person_code
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private String personCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_person_history.person_name
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    private String personName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person_history.person_history_id
     *
     * @return the value of ehr_person_history.person_history_id
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public Long getPersonHistoryId() {
        return personHistoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person_history.person_history_id
     *
     * @param personHistoryId the value for ehr_person_history.person_history_id
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setPersonHistoryId(Long personHistoryId) {
        this.personHistoryId = personHistoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person_history.organization_detail_history_id
     *
     * @return the value of ehr_person_history.organization_detail_history_id
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public Long getOrganizationDetailHistoryId() {
        return organizationDetailHistoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person_history.organization_detail_history_id
     *
     * @param organizationDetailHistoryId the value for ehr_person_history.organization_detail_history_id
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setOrganizationDetailHistoryId(Long organizationDetailHistoryId) {
        this.organizationDetailHistoryId = organizationDetailHistoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person_history.organization_id
     *
     * @return the value of ehr_person_history.organization_id
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public Long getOrganizationId() {
        return organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person_history.organization_id
     *
     * @param organizationId the value for ehr_person_history.organization_id
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setOrganizationId(Long organizationId) {
        this.organizationId = organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person_history.person_id
     *
     * @return the value of ehr_person_history.person_id
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public Long getPersonId() {
        return personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person_history.person_id
     *
     * @param personId the value for ehr_person_history.person_id
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setPersonId(Long personId) {
        this.personId = personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person_history.person_code
     *
     * @return the value of ehr_person_history.person_code
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public String getPersonCode() {
        return personCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person_history.person_code
     *
     * @param personCode the value for ehr_person_history.person_code
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setPersonCode(String personCode) {
        this.personCode = personCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_person_history.person_name
     *
     * @return the value of ehr_person_history.person_name
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public String getPersonName() {
        return personName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_person_history.person_name
     *
     * @param personName the value for ehr_person_history.person_name
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    public void setPersonName(String personName) {
        this.personName = personName;
    }
}