package com.jabava.dao.hro.order;

import java.util.List;
import java.util.Map;

import com.jabava.pojo.hro.order.HsEmpOrdNsbDetail;
import com.jabava.pojo.hro.order.HsEmpOrdVO;
/**
 * 非社保月度表
 *
 * @version $Id: HsEmpOrdNsbDetailMapper.java, 
 * v 0.1 2016年1月25日 下午3:34:21 
 * <pre>
 * @author steven.chen
 * @date 2016年1月25日 下午3:34:21 
 * </pre>
 */
public interface HsEmpOrdNsbDetailMapper {
	/**
	 * 批量新增或者更新订单详情，如果 ordNsbDetailId 存在就更新，如果ordNsbDetailId 不存在就新增
	 * <pre>
	 * @author steven.chen
	 * @date 2016年1月23日 下午6:42:46 
	 * </pre>
	 *
	 * @param list
	 * @return
	 */
	int insertOrUpdateList(List<HsEmpOrdNsbDetail> list);
	/**
	 * 
	 * <pre>
	 * @author steven.chen
	 * @date 2016年3月21日 下午2:00:33 
	 * </pre>
	 *
	 * @param hsEmpOrdVO
	 * @return
	 */
	int updateIsDeleted(HsEmpOrdVO hsEmpOrdVO);
	/**
	 * 根据order_id 更新isdeletd 为 null
	 * <pre>
	 * @author steven.chen
	 * @date 2016年3月16日 上午9:43:47 
	 * </pre>
	 *
	 * @param list
	 * @return
	 */
	int updateIsDeleted(List<Long> list);
	/**
	 * 根据账单月，服务月查询信息
	 * <pre>
	 * @author steven.chen
	 * @date 2016年1月25日 下午3:34:53 
	 * </pre>
	 *
	 * @param ordNsbDetailId
	 * @return
	 */
    List<HsEmpOrdNsbDetail> findOrderCostPage(Map<String, Object> map);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_emp_ord_nsb_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long ordNsbDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_emp_ord_nsb_detail
     *
     * @mbggenerated
     */
    int insert(HsEmpOrdNsbDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_emp_ord_nsb_detail
     *
     * @mbggenerated
     */
    int insertSelective(HsEmpOrdNsbDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_emp_ord_nsb_detail
     *
     * @mbggenerated
     */
    HsEmpOrdNsbDetail selectByPrimaryKey(Long ordNsbDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_emp_ord_nsb_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HsEmpOrdNsbDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_emp_ord_nsb_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HsEmpOrdNsbDetail record);
}