package com.jabava.dao.hro.order;

import java.util.List;

import com.jabava.pojo.hro.order.HsEmpOrdRec;

public interface HsEmpOrdRecMapper {
	/**
	 * 批量新增或者更新订单详情，如果 ordRecId 存在就更新，如果ordRecId 不存在就新增
	 * <pre>
	 * @author steven.chen
	 * @date 2016年1月20日 下午6:22:21 
	 * </pre>
	 *
	 * @param hsEmpOrdList
	 * @return
	 */
	int insertOrUpdateList(List<HsEmpOrdRec> list);
	/**
	 * 根据orderId 更新 islast  为 null
	 * <pre>
	 * @author steven.chen
	 * @date 2016年3月9日 下午4:06:36 
	 * </pre>
	 *
	 * @param list
	 * @return
	 */
	int updateIsLast(List<Long> list);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_emp_ord_rec
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long ordRecId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_emp_ord_rec
     *
     * @mbggenerated
     */
    int insert(HsEmpOrdRec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_emp_ord_rec
     *
     * @mbggenerated
     */
    int insertSelective(HsEmpOrdRec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_emp_ord_rec
     *
     * @mbggenerated
     */
    HsEmpOrdRec selectByPrimaryKey(Long ordRecId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_emp_ord_rec
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HsEmpOrdRec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_emp_ord_rec
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HsEmpOrdRec record);
}