package com.jabava.dao.hro.order;

import java.util.List;
import java.util.Map;

import com.jabava.pojo.hro.order.HsEmpOrdSbDetail;
import com.jabava.pojo.hro.order.HsEmpOrdVO;

/**
 * 社保月度表
 *
 * @version $Id: HsEmpOrdSbDetailMapper.java, 
 * v 0.1 2016年1月23日 下午6:41:35 
 * <pre>
 * @author steven.chen
 * @date 2016年1月23日 下午6:41:35 
 * </pre>
 */
public interface HsEmpOrdSbDetailMapper {
	
	/**
	 * 根据order_id 更新 id not in  idList isdeletd 为 1
	 * <pre>
	 * @author steven.chen
	 * @date 2016年3月16日 上午9:43:47 
	 * </pre>
	 *
	 * @param list
	 * @return
	 */
	int updateIsDeleted(HsEmpOrdVO hsEmpOrdVO);
	/**
	 * 批量新增或者更新订单详情，如果 ordSbDetailId 存在就更新，如果ordSbDetailId 不存在就新增
	 * <pre>
	 * @author steven.chen
	 * @date 2016年1月23日 下午6:42:01 
	 * </pre>
	 *
	 * @param list
	 * @return
	 */
	int insertOrUpdateList(List<HsEmpOrdSbDetail> list);
	/**
	 * 根据服务月，账单月查询信息
	 * <pre>
	 * @author steven.chen
	 * @date 2016年1月26日 上午10:16:08 
	 * </pre>
	 *
	 * @param map
	 * @return
	 */
    List<HsEmpOrdSbDetail> findOrderCostPage(Map<String, Object> map);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_emp_ord_sb_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long ordSbDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_emp_ord_sb_detail
     *
     * @mbggenerated
     */
    int insert(HsEmpOrdSbDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_emp_ord_sb_detail
     *
     * @mbggenerated
     */
    int insertSelective(HsEmpOrdSbDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_emp_ord_sb_detail
     *
     * @mbggenerated
     */
    HsEmpOrdSbDetail selectByPrimaryKey(Long ordSbDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_emp_ord_sb_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HsEmpOrdSbDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hs_emp_ord_sb_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HsEmpOrdSbDetail record);
}