package com.jabava.service.weixin;

import java.io.IOException;
import java.util.List;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;

import org.springframework.web.multipart.commons.CommonsMultipartFile;

import com.jabava.pojo.manage.EhrOrganization;
import com.jabava.pojo.weixin.WeiXinNews;
import com.jabava.pojo.weixin.WeiXinNewsVO;

/**
 * 新闻模板接口
 *
 * @version $Id: WeiXinNewsService.java, 
 * v 0.1 2016年5月23日 上午10:52:46 
 * <pre>
 * @author steven.chen
 * @date 2016年5月23日 上午10:52:46 
 * </pre>
 */
public interface WeiXinNewsService {
	/**
	 * 分页查询新闻模板
	 * <pre>
	 * @author steven.chen
	 * @date 2016年5月23日 下午1:50:40 
	 * </pre>
	 *
	 * @param map
	 * @return
	 */	
	List<WeiXinNewsVO> findNewsPage(Map<String, Object> map);	
	/**
	 * 发送内容到员工帮手
	 * <pre>
	 * @author steven.chen
	 * @date 2016年5月23日 下午2:44:46 
	 * </pre>
	 *
	 * @param weiXinNewsVO
	 * @return
	 */
	String sendNews(WeiXinNewsVO weiXinNewsVO);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_news
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(WeiXinNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_news
     *
     * @mbggenerated
     */
    int insertSelective(WeiXinNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_news
     *
     * @mbggenerated
     */
    WeiXinNews selectByPrimaryKey(Long newsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_news
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WeiXinNews record);
    /**
     * 树形列表
     * <pre>
     * @author steven.chen
     * @date 2016年5月31日 下午1:31:51 
     * </pre>
     *
     * @param companyId
     * @return
     */
	List<EhrOrganization> loadTree(Long companyId);
	/**
	 * 上传文件到HRO服务器，返回url
	 * <pre>
	 * @author steven.chen
	 * @date 2016年6月3日 下午2:07:24 
	 * </pre>
	 *
	 * @param myfiles
	 * @param request
	 * @return
	 * @throws IOException
	 */
	String uploadFile(CommonsMultipartFile myfiles, HttpServletRequest request)
			throws IOException;


}
