package com.jabava.pojo.appStore;

public class EhrAppStore {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_app_store.APP_ID
     *
     * @mbggenerated Tue Aug 09 11:02:08 CST 2016
     */
    private Long appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_app_store.SYSTEM_ID
     *
     * @mbggenerated Tue Aug 09 11:02:08 CST 2016
     */
    private Long systemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_app_store.APP_NAME
     *
     * @mbggenerated Tue Aug 09 11:02:08 CST 2016
     */
    private String appName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_app_store.ICON_PATH
     *
     * @mbggenerated Tue Aug 09 11:02:08 CST 2016
     */
    private String iconPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_app_store.APP_SORT
     *
     * @mbggenerated Tue Aug 09 11:02:08 CST 2016
     */
    private Integer appSort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_app_store.PARENT_ID
     *
     * @mbggenerated Tue Aug 09 11:02:08 CST 2016
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_app_store.IS_ONLINE
     *
     * @mbggenerated Tue Aug 09 11:02:08 CST 2016
     */
    private Integer isOnline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_app_store.IS_DELETED
     *
     * @mbggenerated Tue Aug 09 11:02:08 CST 2016
     */
    private Integer isDeleted;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_app_store.OPENED_URL
     *
     * @mbggenerated Tue Aug 09 11:02:08 CST 2016
     */
    private String openedUrl;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_app_store.UN_OPENED_URL
     *
     * @mbggenerated Tue Aug 09 11:02:08 CST 2016
     */
    private String unOpenedUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_app_store.APP_ID
     *
     * @return the value of ehr_app_store.APP_ID
     *
     * @mbggenerated Tue Aug 09 11:02:08 CST 2016
     */
    public Long getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_app_store.APP_ID
     *
     * @param appId the value for ehr_app_store.APP_ID
     *
     * @mbggenerated Tue Aug 09 11:02:08 CST 2016
     */
    public void setAppId(Long appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_app_store.SYSTEM_ID
     *
     * @return the value of ehr_app_store.SYSTEM_ID
     *
     * @mbggenerated Tue Aug 09 11:02:08 CST 2016
     */
    public Long getSystemId() {
        return systemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_app_store.SYSTEM_ID
     *
     * @param systemId the value for ehr_app_store.SYSTEM_ID
     *
     * @mbggenerated Tue Aug 09 11:02:08 CST 2016
     */
    public void setSystemId(Long systemId) {
        this.systemId = systemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_app_store.APP_NAME
     *
     * @return the value of ehr_app_store.APP_NAME
     *
     * @mbggenerated Tue Aug 09 11:02:08 CST 2016
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_app_store.APP_NAME
     *
     * @param appName the value for ehr_app_store.APP_NAME
     *
     * @mbggenerated Tue Aug 09 11:02:08 CST 2016
     */
    public void setAppName(String appName) {
        this.appName = appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_app_store.ICON_PATH
     *
     * @return the value of ehr_app_store.ICON_PATH
     *
     * @mbggenerated Tue Aug 09 11:02:08 CST 2016
     */
    public String getIconPath() {
        return iconPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_app_store.ICON_PATH
     *
     * @param iconPath the value for ehr_app_store.ICON_PATH
     *
     * @mbggenerated Tue Aug 09 11:02:08 CST 2016
     */
    public void setIconPath(String iconPath) {
        this.iconPath = iconPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_app_store.APP_SORT
     *
     * @return the value of ehr_app_store.APP_SORT
     *
     * @mbggenerated Tue Aug 09 11:02:08 CST 2016
     */
    public Integer getAppSort() {
        return appSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_app_store.APP_SORT
     *
     * @param appSort the value for ehr_app_store.APP_SORT
     *
     * @mbggenerated Tue Aug 09 11:02:08 CST 2016
     */
    public void setAppSort(Integer appSort) {
        this.appSort = appSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_app_store.PARENT_ID
     *
     * @return the value of ehr_app_store.PARENT_ID
     *
     * @mbggenerated Tue Aug 09 11:02:08 CST 2016
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_app_store.PARENT_ID
     *
     * @param parentId the value for ehr_app_store.PARENT_ID
     *
     * @mbggenerated Tue Aug 09 11:02:08 CST 2016
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_app_store.IS_ONLINE
     *
     * @return the value of ehr_app_store.IS_ONLINE
     *
     * @mbggenerated Tue Aug 09 11:02:08 CST 2016
     */
    public Integer getIsOnline() {
        return isOnline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_app_store.IS_ONLINE
     *
     * @param isOnline the value for ehr_app_store.IS_ONLINE
     *
     * @mbggenerated Tue Aug 09 11:02:08 CST 2016
     */
    public void setIsOnline(Integer isOnline) {
        this.isOnline = isOnline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_app_store.IS_DELETED
     *
     * @return the value of ehr_app_store.IS_DELETED
     *
     * @mbggenerated Tue Aug 09 11:02:08 CST 2016
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_app_store.IS_DELETED
     *
     * @param isDeleted the value for ehr_app_store.IS_DELETED
     *
     * @mbggenerated Tue Aug 09 11:02:08 CST 2016
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_app_store.OPENED_URL
     *
     * @return the value of ehr_app_store.OPENED_URL
     *
     * @mbggenerated Tue Aug 09 11:02:08 CST 2016
     */
    public String getOpenedUrl() {
        return openedUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_app_store.OPENED_URL
     *
     * @param isDeleted the value for ehr_app_store.OPENED_URL
     *
     * @mbggenerated Tue Aug 09 11:02:08 CST 2016
     */
    public void setOpenedUrl(String openedUrl) {
        this.openedUrl = openedUrl;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_app_store.UN_OPENED_URL
     *
     * @return the value of ehr_app_store.UN_OPENED_URL
     *
     * @mbggenerated Tue Aug 09 11:02:08 CST 2016
     */
    public String getUnOpenedUrl() {
        return unOpenedUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_app_store.UN_OPENED_URL
     *
     * @param isDeleted the value for ehr_app_store.UN_OPENED_URL
     *
     * @mbggenerated Tue Aug 09 11:02:08 CST 2016
     */
    public void setUnOpenedUrl(String unOpenedUrl) {
        this.unOpenedUrl = unOpenedUrl;
    }
}