package com.jabava.dao.socialsecurity;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.jabava.pojo.socialsecurity.EhrSupplementPayment;

public interface EhrSupplementPaymentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_supplement_payment
     *
     * @mbggenerated Fri Apr 29 11:44:57 CST 2016
     */
    int deleteByPrimaryKey(Integer paymentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_supplement_payment
     *
     * @mbggenerated Fri Apr 29 11:44:57 CST 2016
     */
    int insert(EhrSupplementPayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_supplement_payment
     *
     * @mbggenerated Fri Apr 29 11:44:57 CST 2016
     */
    int insertSelective(EhrSupplementPayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_supplement_payment
     *
     * @mbggenerated Fri Apr 29 11:44:57 CST 2016
     */
    EhrSupplementPayment selectByPrimaryKey(Integer paymentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_supplement_payment
     *
     * @mbggenerated Fri Apr 29 11:44:57 CST 2016
     */
    int updateByPrimaryKeySelective(EhrSupplementPayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_supplement_payment
     *
     * @mbggenerated Fri Apr 29 11:44:57 CST 2016
     */
    int updateByPrimaryKey(EhrSupplementPayment record);

	/**
	* 依据社保档案代码和办理月份获取社保补缴记录
	* @param profileID 社保档案代码
	* @param month     社保办理月
	* @param type      社保 公积金
	* @return
	*/
	List <EhrSupplementPayment> getSupplementPayment(@Param("profileId")String profileId,@Param("month")String month,@Param("type")Long type);
	
	/**
     * 批量插入补缴信息
     * @param list
     * @return
     */
    public int addBatchSupplementPaymentInfo(List<EhrSupplementPayment> list);
    
    public List <EhrSupplementPayment> getSupplementPaymentByMonth(@Param("personId")Long personId,@Param("month")String month);
    
    /**
     * 根据月份和人员信息，清空月份不缴记录
     * @param personId 员工信息
     * @param month    月份信息
     */
    public void deleteSupplementPaymentInfo(@Param("personId")Long personId,@Param("month")String month);
}