package com.jabava.dao.socialsecurity;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.jabava.pojo.socialsecurity.SsPaymentBillPerson;

public interface SsPaymentBillPersonMapper {
	List<SsPaymentBillPerson> selectByBillId(Long ssPaymentBillId);
	
	Map<String,Object> selectByPersonAndMonth(@Param("month")String month, @Param("personId")Long personId);
	
	List<Map<String,Object>> selectBillPersonByPerson(Map<String,Object> params);
	
	Map<String, Object> queryByCertIdAndMonth(@Param("cardId")String cardId, @Param("month")String month);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ss_payment_bill_person
	 * @mbggenerated  Wed Apr 20 20:01:30 CST 2016
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ss_payment_bill_person
	 * @mbggenerated  Wed Apr 20 20:01:30 CST 2016
	 */
	int insert(SsPaymentBillPerson record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ss_payment_bill_person
	 * @mbggenerated  Wed Apr 20 20:01:30 CST 2016
	 */
	int insertSelective(SsPaymentBillPerson record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ss_payment_bill_person
	 * @mbggenerated  Wed Apr 20 20:01:30 CST 2016
	 */
	SsPaymentBillPerson selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ss_payment_bill_person
	 * @mbggenerated  Wed Apr 20 20:01:30 CST 2016
	 */
	int updateByPrimaryKeySelective(SsPaymentBillPerson record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ss_payment_bill_person
	 * @mbggenerated  Wed Apr 20 20:01:30 CST 2016
	 */
	int updateByPrimaryKey(SsPaymentBillPerson record);
}