package com.jabava.dao.socialsecurity;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.jabava.pojo.socialsecurity.SsPaymentBillDetail;

public interface SsPaymentBillDetailMapper {
	Map<String,Object> sumPaymentBillDetail(@Param("companyId")Long companyId, @Param("ssPaymentBillId")Long ssPaymentBillId);
	
	List<Map<String,Object>> listPaymentBillDetail(@Param("companyId")Long companyId, @Param("ssPaymentBillId")Long ssPaymentBillId);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_payment_bill_detail
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_payment_bill_detail
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    int insert(SsPaymentBillDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_payment_bill_detail
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    int insertSelective(SsPaymentBillDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_payment_bill_detail
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    SsPaymentBillDetail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_payment_bill_detail
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    int updateByPrimaryKeySelective(SsPaymentBillDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_payment_bill_detail
     *
     * @mbggenerated Tue Apr 19 19:22:20 CST 2016
     */
    int updateByPrimaryKey(SsPaymentBillDetail record);
}