package com.jabava.dao.socialsecurity;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.jabava.pojo.policygroup.SbGroup;
import com.jabava.pojo.socialsecurity.SsSocialSecurityAccount;
import com.jabava.pojo.socialsecurity.SsSocialSecurityAccountVO;


public interface SsSocialSecurityAccountMapper {
	
	/**
	 * 分页查询社保账户列表
	 * <pre>
	 * @author steven.chen
	 * @date 2016年4月14日 下午7:46:56 
	 * </pre>
	 *
	 * @param map
	 * @return
	 */
	public List<SsSocialSecurityAccountVO> findSocialSecurityAccountPage(Map<String, Object> map);
	/**
	 * 分页查询人员列表
	 * <pre>
	 * @author steven.chen
	 * @date 2016年4月19日 下午7:42:37 
	 * </pre>
	 *
	 * @param map
	 * @return
	 */
	public List<SsSocialSecurityAccountVO> findPersonListPage(Map<String, Object> map);
	/**
	 * 根据ID查询 社保账户
	 * <pre>
	 * @author steven.chen
	 * @date 2016年4月20日 下午1:58:13 
	 * </pre>
	 *
	 * @param ssSocialSecurityAccount
	 * @return
	 */
	SsSocialSecurityAccountVO getSocialSecurityAccountById(SsSocialSecurityAccount ssSocialSecurityAccount);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_social_security_account
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long socialSecurityAccountId);
    /**
     * 把 is_deleted 设为  1
     * <pre>
     * @author steven.chen
     * @date 2016年4月19日 下午3:58:04 
     * </pre>
     *
     * @param socialSecurityAccountId
     * @return
     */
    int deleteById(Long socialSecurityAccountId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_social_security_account
     *
     * @mbggenerated
     */
    int insert(SsSocialSecurityAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_social_security_account
     *
     * @mbggenerated
     */
    int insertSelective(SsSocialSecurityAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_social_security_account
     *
     * @mbggenerated
     */
    SsSocialSecurityAccountVO selectByPrimaryKey(Long socialSecurityAccountId);
    /**
     * 根据socialSecurityCode  查询社保账户列表  
     * 
     * socialSecurityCode 不可为空
     * <pre>
     * @author steven.chen
     * @date 2016年4月14日 下午4:31:41 
     * </pre>
     *
     * @param record
     * @return
     */
    List<SsSocialSecurityAccount> findSocialSecurityByCode(String socialSecurityCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_social_security_account
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SsSocialSecurityAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_social_security_account
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SsSocialSecurityAccount record);
    
    /**
     * 根据公司代码查询社保账户列表  
     * @param companyId
     * @return
     */
    public List<SsSocialSecurityAccount> getSecurityAccountByCompanyId(Long companyId);
    
    public String getSocialSecurityRules(Long accountId);
    
    public List<SbGroup> getSocialSecurityRulesDetail(String [] profilelist);
    
    public List<Map<String,Object>> getSecurityGroupDetail(@Param("groupId")Long groupId,@Param("groupType")Long groupType);
}