package com.jabava.dao.announcement;

import java.util.List;
import java.util.Map;

import com.jabava.controller.announcement.QeuryEhrInformation;
import com.jabava.pojo.announcement.EhrInformation;

/**
 * 信息公告
 *
 * @version $Id: EhrInformationMapper.java, 
 * v 0.1 2015年12月28日 上午11:19:14 
 * <pre>
 * @author steven.chen
 * @date 2015年12月28日 上午11:19:14 
 * </pre>
 */
public interface EhrInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_information
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long informationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_information
     *
     * @mbggenerated
     */
    int insert(EhrInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_information
     *
     * @mbggenerated
     */
    int insertSelective(EhrInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_information
     *
     * @mbggenerated
     */
    EhrInformation selectByPrimaryKey(Long informationId);
    /**
     * 根据参数查询信息列表
     * <pre>
     * @author steven.chen
     * @date 2015年12月28日 下午4:44:41 
     * </pre>
     *
     * @param record
     * @return
     */
    List<EhrInformation> findInformationByParams (QeuryEhrInformation ehrInformation);
    
    List<Map<String, Object>> findInformationByParamsPage (Map<String, Object> map);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_information
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EhrInformation record);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_information
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EhrInformation record);
}