package com.jabava.pojo.policygroup;

import java.math.BigDecimal;
import java.util.Date;

public class SbGroupDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_group_detail.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_group_detail.sb_group_id
     *
     * @mbggenerated
     */
    private Long sbGroupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_group_detail.policy_group_id
     *
     * @mbggenerated
     */
    private Long policyGroupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_group_detail.policy_group_name
     *
     * @mbggenerated
     */
    private String policyGroupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_group_detail.city_id
     *
     * @mbggenerated
     */
    private Long cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_group_detail.prod_id
     *
     * @mbggenerated
     */
    private Long prodId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_group_detail.prod_name
     *
     * @mbggenerated
     */
    private String prodName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_group_detail.is_payment
     *
     * @mbggenerated
     */
    private Boolean isPayment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_group_detail.base_id
     *
     * @mbggenerated
     */
    private Long baseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_group_detail.company_base_scope
     *
     * @mbggenerated
     */
    private String companyBaseScope;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_group_detail.individual_base_scope
     *
     * @mbggenerated
     */
    private String individualBaseScope;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_group_detail.ratio_id
     *
     * @mbggenerated
     */
    private Long ratioId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_group_detail.ratio_name
     *
     * @mbggenerated
     */
    private String ratioName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_group_detail.com_ratio
     *
     * @mbggenerated
     */
    private BigDecimal comRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_group_detail.ind_ratio
     *
     * @mbggenerated
     */
    private BigDecimal indRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_group_detail.com_add_amount
     *
     * @mbggenerated
     */
    private BigDecimal comAddAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_group_detail.ind_add_amount
     *
     * @mbggenerated
     */
    private BigDecimal indAddAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_group_detail.pay_type
     *
     * @mbggenerated
     */
    private Integer payType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_group_detail.company_base_grade
     *
     * @mbggenerated
     */
    private String companyBaseGrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_group_detail.individual_base_grade
     *
     * @mbggenerated
     */
    private String individualBaseGrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_group_detail.company_ratio_id
     *
     * @mbggenerated
     */
    private Long companyRatioId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_group_detail.individual_ratio_id
     *
     * @mbggenerated
     */
    private Long individualRatioId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_group_detail.is_deleted
     *
     * @mbggenerated
     */
    private Integer isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_group_detail.create_by
     *
     * @mbggenerated
     */
    private Long createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_group_detail.create_dt
     *
     * @mbggenerated
     */
    private Date createDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_group_detail.update_by
     *
     * @mbggenerated
     */
    private Long updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_group_detail.update_dt
     *
     * @mbggenerated
     */
    private Date updateDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_group_detail.mimic_by
     *
     * @mbggenerated
     */
    private Long mimicBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_group_detail.proxy_by
     *
     * @mbggenerated
     */
    private Long proxyBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_group_detail.company_ratio
     *
     * @mbggenerated
     */
    private String companyRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_group_detail.individual_ratio
     *
     * @mbggenerated
     */
    private String individualRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_group_detail.service_type
     *
     * @mbggenerated
     */
    private Long serviceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_group_detail.is_load
     *
     * @mbggenerated
     */
    private Boolean isLoad;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_group_detail.id
     *
     * @return the value of sb_group_detail.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_group_detail.id
     *
     * @param id the value for sb_group_detail.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_group_detail.sb_group_id
     *
     * @return the value of sb_group_detail.sb_group_id
     *
     * @mbggenerated
     */
    public Long getSbGroupId() {
        return sbGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_group_detail.sb_group_id
     *
     * @param sbGroupId the value for sb_group_detail.sb_group_id
     *
     * @mbggenerated
     */
    public void setSbGroupId(Long sbGroupId) {
        this.sbGroupId = sbGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_group_detail.policy_group_id
     *
     * @return the value of sb_group_detail.policy_group_id
     *
     * @mbggenerated
     */
    public Long getPolicyGroupId() {
        return policyGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_group_detail.policy_group_id
     *
     * @param policyGroupId the value for sb_group_detail.policy_group_id
     *
     * @mbggenerated
     */
    public void setPolicyGroupId(Long policyGroupId) {
        this.policyGroupId = policyGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_group_detail.policy_group_name
     *
     * @return the value of sb_group_detail.policy_group_name
     *
     * @mbggenerated
     */
    public String getPolicyGroupName() {
        return policyGroupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_group_detail.policy_group_name
     *
     * @param policyGroupName the value for sb_group_detail.policy_group_name
     *
     * @mbggenerated
     */
    public void setPolicyGroupName(String policyGroupName) {
        this.policyGroupName = policyGroupName == null ? null : policyGroupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_group_detail.city_id
     *
     * @return the value of sb_group_detail.city_id
     *
     * @mbggenerated
     */
    public Long getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_group_detail.city_id
     *
     * @param cityId the value for sb_group_detail.city_id
     *
     * @mbggenerated
     */
    public void setCityId(Long cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_group_detail.prod_id
     *
     * @return the value of sb_group_detail.prod_id
     *
     * @mbggenerated
     */
    public Long getProdId() {
        return prodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_group_detail.prod_id
     *
     * @param prodId the value for sb_group_detail.prod_id
     *
     * @mbggenerated
     */
    public void setProdId(Long prodId) {
        this.prodId = prodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_group_detail.prod_name
     *
     * @return the value of sb_group_detail.prod_name
     *
     * @mbggenerated
     */
    public String getProdName() {
        return prodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_group_detail.prod_name
     *
     * @param prodName the value for sb_group_detail.prod_name
     *
     * @mbggenerated
     */
    public void setProdName(String prodName) {
        this.prodName = prodName == null ? null : prodName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_group_detail.is_payment
     *
     * @return the value of sb_group_detail.is_payment
     *
     * @mbggenerated
     */
    public Boolean getIsPayment() {
        return isPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_group_detail.is_payment
     *
     * @param isPayment the value for sb_group_detail.is_payment
     *
     * @mbggenerated
     */
    public void setIsPayment(Boolean isPayment) {
        this.isPayment = isPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_group_detail.base_id
     *
     * @return the value of sb_group_detail.base_id
     *
     * @mbggenerated
     */
    public Long getBaseId() {
        return baseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_group_detail.base_id
     *
     * @param baseId the value for sb_group_detail.base_id
     *
     * @mbggenerated
     */
    public void setBaseId(Long baseId) {
        this.baseId = baseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_group_detail.company_base_scope
     *
     * @return the value of sb_group_detail.company_base_scope
     *
     * @mbggenerated
     */
    public String getCompanyBaseScope() {
        return companyBaseScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_group_detail.company_base_scope
     *
     * @param companyBaseScope the value for sb_group_detail.company_base_scope
     *
     * @mbggenerated
     */
    public void setCompanyBaseScope(String companyBaseScope) {
        this.companyBaseScope = companyBaseScope == null ? null : companyBaseScope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_group_detail.individual_base_scope
     *
     * @return the value of sb_group_detail.individual_base_scope
     *
     * @mbggenerated
     */
    public String getIndividualBaseScope() {
        return individualBaseScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_group_detail.individual_base_scope
     *
     * @param individualBaseScope the value for sb_group_detail.individual_base_scope
     *
     * @mbggenerated
     */
    public void setIndividualBaseScope(String individualBaseScope) {
        this.individualBaseScope = individualBaseScope == null ? null : individualBaseScope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_group_detail.ratio_id
     *
     * @return the value of sb_group_detail.ratio_id
     *
     * @mbggenerated
     */
    public Long getRatioId() {
        return ratioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_group_detail.ratio_id
     *
     * @param ratioId the value for sb_group_detail.ratio_id
     *
     * @mbggenerated
     */
    public void setRatioId(Long ratioId) {
        this.ratioId = ratioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_group_detail.ratio_name
     *
     * @return the value of sb_group_detail.ratio_name
     *
     * @mbggenerated
     */
    public String getRatioName() {
        return ratioName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_group_detail.ratio_name
     *
     * @param ratioName the value for sb_group_detail.ratio_name
     *
     * @mbggenerated
     */
    public void setRatioName(String ratioName) {
        this.ratioName = ratioName == null ? null : ratioName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_group_detail.com_ratio
     *
     * @return the value of sb_group_detail.com_ratio
     *
     * @mbggenerated
     */
    public BigDecimal getComRatio() {
        return comRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_group_detail.com_ratio
     *
     * @param comRatio the value for sb_group_detail.com_ratio
     *
     * @mbggenerated
     */
    public void setComRatio(BigDecimal comRatio) {
        this.comRatio = comRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_group_detail.ind_ratio
     *
     * @return the value of sb_group_detail.ind_ratio
     *
     * @mbggenerated
     */
    public BigDecimal getIndRatio() {
        return indRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_group_detail.ind_ratio
     *
     * @param indRatio the value for sb_group_detail.ind_ratio
     *
     * @mbggenerated
     */
    public void setIndRatio(BigDecimal indRatio) {
        this.indRatio = indRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_group_detail.com_add_amount
     *
     * @return the value of sb_group_detail.com_add_amount
     *
     * @mbggenerated
     */
    public BigDecimal getComAddAmount() {
        return comAddAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_group_detail.com_add_amount
     *
     * @param comAddAmount the value for sb_group_detail.com_add_amount
     *
     * @mbggenerated
     */
    public void setComAddAmount(BigDecimal comAddAmount) {
        this.comAddAmount = comAddAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_group_detail.ind_add_amount
     *
     * @return the value of sb_group_detail.ind_add_amount
     *
     * @mbggenerated
     */
    public BigDecimal getIndAddAmount() {
        return indAddAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_group_detail.ind_add_amount
     *
     * @param indAddAmount the value for sb_group_detail.ind_add_amount
     *
     * @mbggenerated
     */
    public void setIndAddAmount(BigDecimal indAddAmount) {
        this.indAddAmount = indAddAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_group_detail.pay_type
     *
     * @return the value of sb_group_detail.pay_type
     *
     * @mbggenerated
     */
    public Integer getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_group_detail.pay_type
     *
     * @param payType the value for sb_group_detail.pay_type
     *
     * @mbggenerated
     */
    public void setPayType(Integer payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_group_detail.company_base_grade
     *
     * @return the value of sb_group_detail.company_base_grade
     *
     * @mbggenerated
     */
    public String getCompanyBaseGrade() {
        return companyBaseGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_group_detail.company_base_grade
     *
     * @param companyBaseGrade the value for sb_group_detail.company_base_grade
     *
     * @mbggenerated
     */
    public void setCompanyBaseGrade(String companyBaseGrade) {
        this.companyBaseGrade = companyBaseGrade == null ? null : companyBaseGrade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_group_detail.individual_base_grade
     *
     * @return the value of sb_group_detail.individual_base_grade
     *
     * @mbggenerated
     */
    public String getIndividualBaseGrade() {
        return individualBaseGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_group_detail.individual_base_grade
     *
     * @param individualBaseGrade the value for sb_group_detail.individual_base_grade
     *
     * @mbggenerated
     */
    public void setIndividualBaseGrade(String individualBaseGrade) {
        this.individualBaseGrade = individualBaseGrade == null ? null : individualBaseGrade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_group_detail.company_ratio_id
     *
     * @return the value of sb_group_detail.company_ratio_id
     *
     * @mbggenerated
     */
    public Long getCompanyRatioId() {
        return companyRatioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_group_detail.company_ratio_id
     *
     * @param companyRatioId the value for sb_group_detail.company_ratio_id
     *
     * @mbggenerated
     */
    public void setCompanyRatioId(Long companyRatioId) {
        this.companyRatioId = companyRatioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_group_detail.individual_ratio_id
     *
     * @return the value of sb_group_detail.individual_ratio_id
     *
     * @mbggenerated
     */
    public Long getIndividualRatioId() {
        return individualRatioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_group_detail.individual_ratio_id
     *
     * @param individualRatioId the value for sb_group_detail.individual_ratio_id
     *
     * @mbggenerated
     */
    public void setIndividualRatioId(Long individualRatioId) {
        this.individualRatioId = individualRatioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_group_detail.is_deleted
     *
     * @return the value of sb_group_detail.is_deleted
     *
     * @mbggenerated
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_group_detail.is_deleted
     *
     * @param isDeleted the value for sb_group_detail.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_group_detail.create_by
     *
     * @return the value of sb_group_detail.create_by
     *
     * @mbggenerated
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_group_detail.create_by
     *
     * @param createBy the value for sb_group_detail.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_group_detail.create_dt
     *
     * @return the value of sb_group_detail.create_dt
     *
     * @mbggenerated
     */
    public Date getCreateDt() {
        return createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_group_detail.create_dt
     *
     * @param createDt the value for sb_group_detail.create_dt
     *
     * @mbggenerated
     */
    public void setCreateDt(Date createDt) {
        this.createDt = createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_group_detail.update_by
     *
     * @return the value of sb_group_detail.update_by
     *
     * @mbggenerated
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_group_detail.update_by
     *
     * @param updateBy the value for sb_group_detail.update_by
     *
     * @mbggenerated
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_group_detail.update_dt
     *
     * @return the value of sb_group_detail.update_dt
     *
     * @mbggenerated
     */
    public Date getUpdateDt() {
        return updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_group_detail.update_dt
     *
     * @param updateDt the value for sb_group_detail.update_dt
     *
     * @mbggenerated
     */
    public void setUpdateDt(Date updateDt) {
        this.updateDt = updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_group_detail.mimic_by
     *
     * @return the value of sb_group_detail.mimic_by
     *
     * @mbggenerated
     */
    public Long getMimicBy() {
        return mimicBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_group_detail.mimic_by
     *
     * @param mimicBy the value for sb_group_detail.mimic_by
     *
     * @mbggenerated
     */
    public void setMimicBy(Long mimicBy) {
        this.mimicBy = mimicBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_group_detail.proxy_by
     *
     * @return the value of sb_group_detail.proxy_by
     *
     * @mbggenerated
     */
    public Long getProxyBy() {
        return proxyBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_group_detail.proxy_by
     *
     * @param proxyBy the value for sb_group_detail.proxy_by
     *
     * @mbggenerated
     */
    public void setProxyBy(Long proxyBy) {
        this.proxyBy = proxyBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_group_detail.company_ratio
     *
     * @return the value of sb_group_detail.company_ratio
     *
     * @mbggenerated
     */
    public String getCompanyRatio() {
        return companyRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_group_detail.company_ratio
     *
     * @param companyRatio the value for sb_group_detail.company_ratio
     *
     * @mbggenerated
     */
    public void setCompanyRatio(String companyRatio) {
        this.companyRatio = companyRatio == null ? null : companyRatio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_group_detail.individual_ratio
     *
     * @return the value of sb_group_detail.individual_ratio
     *
     * @mbggenerated
     */
    public String getIndividualRatio() {
        return individualRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_group_detail.individual_ratio
     *
     * @param individualRatio the value for sb_group_detail.individual_ratio
     *
     * @mbggenerated
     */
    public void setIndividualRatio(String individualRatio) {
        this.individualRatio = individualRatio == null ? null : individualRatio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_group_detail.service_type
     *
     * @return the value of sb_group_detail.service_type
     *
     * @mbggenerated
     */
    public Long getServiceType() {
        return serviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_group_detail.service_type
     *
     * @param serviceType the value for sb_group_detail.service_type
     *
     * @mbggenerated
     */
    public void setServiceType(Long serviceType) {
        this.serviceType = serviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_group_detail.is_load
     *
     * @return the value of sb_group_detail.is_load
     *
     * @mbggenerated
     */
    public Boolean getIsLoad() {
        return isLoad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_group_detail.is_load
     *
     * @param isLoad the value for sb_group_detail.is_load
     *
     * @mbggenerated
     */
    public void setIsLoad(Boolean isLoad) {
        this.isLoad = isLoad;
    }
}