package com.jabava.dao.manage;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.jabava.pojo.manage.EhrAttendance;

public interface EhrAttendanceMapper {
	List<Map<String, Object>> listAttentancePage(Map<String, Object> params);

	List<Map<String, Object>> listAttentance(Map<String, Object> params);
	
	int deleteByYearMonthRecord(@Param("companyId")Long companyId, @Param("yearMonthRecord")String yearMonthRecord);
	
	int deleteById(@Param("companyId")Long companyId, @Param("attendId")Long attendId);
	
	Map<String,Object> sumAttendance(@Param("personId")Long personId, @Param("yearMonthRecord")String yearMonthRecord);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_attendance
     *
     * @mbggenerated Mon Jan 04 14:11:04 CST 2016
     */
    int deleteByPrimaryKey(Long attendId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_attendance
     *
     * @mbggenerated Mon Jan 04 14:11:04 CST 2016
     */
    int insert(EhrAttendance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_attendance
     *
     * @mbggenerated Mon Jan 04 14:11:04 CST 2016
     */
    int insertSelective(EhrAttendance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_attendance
     *
     * @mbggenerated Mon Jan 04 14:11:04 CST 2016
     */
    EhrAttendance selectByPrimaryKey(Long attendId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_attendance
     *
     * @mbggenerated Mon Jan 04 14:11:04 CST 2016
     */
    int updateByPrimaryKeySelective(EhrAttendance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_attendance
     *
     * @mbggenerated Mon Jan 04 14:11:04 CST 2016
     */
    int updateByPrimaryKey(EhrAttendance record);

	/**
	 * 获取考勤列表，分页
	 * 
	 * @param params
	 *            查询参数
	 * @return
	 */
	List<Map<String, Object>> getTimeListPage(Map<String, Object> params);

	/**
	 * 修改考勤记录
	 * 
	 * @param params
	 *            修改参数
	 * @return
	 */
	int updateByParam(Map<String, Object> params);

	/**
	 * 批量导入Excel
	 * 
	 * @param map
	 *            插入数据
	 * @return
	 */
	int importTimeExcel(Map<String, Object> map);

	/**
	 * 导出Excel
	 * 
	 * @param params
	 *            查询参数
	 * @return
	 */
	List<Map<String, Object>> downTimeExcel(Map<String, Object> params);
	/***
	 * 根据 attendId 修改 is_deleted 字段为 1
	 * <pre>
	 * @author steven.chen
	 * @date 2016年4月11日 下午2:20:00 
	 * </pre>
	 *
	 * @param attendId
	 * @return
	 */
	int updateIsDeleted(Long attendId);
	
	List<EhrAttendance> getByPersonId(@Param("personId") Long personId);
}