package com.jabava.dao.manage;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.jabava.pojo.manage.EhrBaseData;
import com.jabava.pojo.manage.EhrBaseDataType;

public interface EhrBaseDataMapper {
	List<Map<String,Object>> selectFromTemplate();
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_base_data
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    int deleteByPrimaryKey(Long baseDataId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_base_data
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    int insert(EhrBaseData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_base_data
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    int insertSelective(EhrBaseData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_base_data
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    EhrBaseData selectByPrimaryKey(Long baseDataId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_base_data
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    int updateByPrimaryKeySelective(EhrBaseData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_base_data
     *
     * @mbggenerated Tue Dec 22 13:34:15 CST 2015
     */
    int updateByPrimaryKey(EhrBaseData record);
    
	/**
	 * 删除(逻辑删除)
	 * @param baseDataId
	 * @return
	 */
    int updateByIsvalid(@Param("baseDataId")Long baseDataId,@Param("isValid")Long isValid);
	 
    /**
     * 查询基础数据
     * @param baseDataCode
     * @param baseDataName
     * @param baseDataType
     * @param isValid
     * @param companyId
     * @return
     */
    List<EhrBaseData> searchBaseDataPage(Map<String,Object> map);
    
    		
    /**
     * 查询数据类型
     * @return 
     */
    List<EhrBaseDataType> selectByBaseDataType ();
    
    List<EhrBaseData> getByCompanyId(@Param("companyId") Long companyId);

    EhrBaseData selectBaseDataByCode(@Param("companyId") Long companyId,
			@Param("baseDataType") int baseDataType,
			@Param("baseDataCode") String baseDataCode);

    List<EhrBaseData> selectBaseData(@Param("companyId") Long companyId,
			@Param("baseDataType") int baseDataType,
			@Param("baseDataName") String baseDataName);

    List<EhrBaseData> selectByType(@Param("companyId") Long companyId, @Param("baseDataType") int baseDataType);
    
    /**
     * 检查是否有重复数据
     * @param data
     * @return
     */
    int checkRepeat(EhrBaseData data);
    /**
     * 检查基本数据编号是否重复
     * @param data
     * @return
     */
    int checkCode(EhrBaseData data);
    /**
     * 检查基本数据名称是否重复
     * @param data
     * @return
     */
    int checkName(EhrBaseData data);
    
    int updateByCode(EhrBaseData baseData);
    
    int countByCompany(Long companyId);
}