package com.jabava.dao.manage;

import java.util.List;

import com.jabava.pojo.manage.EhrButton;

public interface EhrButtonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_button
     *
     * @mbggenerated Wed Dec 16 17:30:42 CST 2015
     */
    int deleteByPrimaryKey(Long buttonId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_button
     *
     * @mbggenerated Wed Dec 16 17:30:42 CST 2015
     */
    int insert(EhrButton record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_button
     *
     * @mbggenerated Wed Dec 16 17:30:42 CST 2015
     */
    int insertSelective(EhrButton record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_button
     *
     * @mbggenerated Wed Dec 16 17:30:42 CST 2015
     */
    EhrButton selectByPrimaryKey(Long buttonId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_button
     *
     * @mbggenerated Wed Dec 16 17:30:42 CST 2015
     */
    int updateByPrimaryKeySelective(EhrButton record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_button
     *
     * @mbggenerated Wed Dec 16 17:30:42 CST 2015
     */
    int updateByPrimaryKey(EhrButton record);
    
    List<EhrButton> queryButtonByUserId(long userId);
}