package com.jabava.dao.manage;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.jabava.pojo.manage.EhrRole;
import com.jabava.pojo.manage.EhrRolePower;
import com.jabava.pojo.manage.RolePower;

public interface EhrRoleMapper {
	EhrRole selectByRoleName(@Param("companyId")Long companyId, @Param("roleName")String roleName);
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ehr_role
	 * 
	 * @mbggenerated Wed Dec 23 14:21:27 CST 2015
	 */
	int deleteByPrimaryKey(Long roleId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ehr_role
	 * 
	 * @mbggenerated Wed Dec 23 14:21:27 CST 2015
	 */
	int insert(EhrRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ehr_role
	 * 
	 * @mbggenerated Wed Dec 23 14:21:27 CST 2015
	 */
	int insertSelective(EhrRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ehr_role
	 * 
	 * @mbggenerated Wed Dec 23 14:21:27 CST 2015
	 */
	EhrRole selectByPrimaryKey(Long roleId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ehr_role
	 * 
	 * @mbggenerated Wed Dec 23 14:21:27 CST 2015
	 */
	int updateByPrimaryKeySelective(EhrRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ehr_role
	 * 
	 * @mbggenerated Wed Dec 23 14:21:27 CST 2015
	 */
	int updateByPrimaryKey(EhrRole record);

	/***
	 * 查询
	 * 
	 * @param roleName
	 * @param companyId
	 * @return
	 */
	List<EhrRole> searchEhrRolePage(Map<String, Object> map);
	
	int deleteRoleUser(Long roleId);

	int deleteRolePower(Long roleId);

	int deleteRole(Long roleId);

	/**
	 * parent_id不为0的菜单
	 * @return
	 */
	List<RolePower> getMenu();
	
	/**
	 * parent_id为0的菜单
	 * @return
	 */
	RolePower getZeroMenu();
	
	/**
	 * ehr_page表
	 * @return
	 */
	List<RolePower> getPages();
	
	/**
	 * ehr_button表
	 * @return
	 */
	List<RolePower> getPageButton();
	
	List<EhrRolePower> getPowerListByRole(@Param("roleId")Long roleId, @Param("type")int type);
	
	/**
	 * 根据角色id，删除该角色的所有权限（删除后再添加）
	 * @param roleId
	 * @return
	 */
	int delRolePower(@Param("roleId")Long roleId);
	
	List<EhrRole> selectByUser(Long userId);
	
	List<EhrRole> selectByRole(EhrRole role);
}