package com.jabava.dao.accumulationfund;

import java.util.List;
import java.util.Map;

import com.jabava.pojo.accumulationfund.AfAccumulationFundAccount;
import com.jabava.pojo.accumulationfund.AfAccumulationFundAccountVO;


public interface AfAccumulationFundAccountMapper {
	
	/**
	 * 分页查询公积金账户列表
	 * <pre>
	 * @author steven.chen
	 * @date 2016年4月14日 下午7:46:56 
	 * </pre>
	 *
	 * @param map
	 * @return
	 */
	public List<AfAccumulationFundAccountVO> findAccumulationFundAccountPage(Map<String, Object> map);
	/**
	 * 分页查询人员列表
	 * <pre>
	 * @author steven.chen
	 * @date 2016年4月19日 下午7:42:37 
	 * </pre>
	 *
	 * @param map
	 * @return
	 */
	public List<AfAccumulationFundAccountVO> findPersonListPage(Map<String, Object> map);
	
	   /**
     * 根据accumulationFundCode  查询公积金账户列表  
     * 
     * accumulationFundCode 不可 可为空
     * <pre>
     * @author steven.chen
     * @date 2016年4月14日 下午4:31:41 
     * </pre>
     *
     * @param record
     * @return
     */
    List<AfAccumulationFundAccount> findAccumulationFundByCode(String  accumulationFundCode);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_accumulation_fund_account
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long accumulationFundAccountId);
    /**
     * 把 is_deleted 设为  1
     * <pre>
     * @author steven.chen
     * @date 2016年4月19日 下午3:58:04 
     * </pre>
     *
     * @param accumulationFundAccountId
     * @return
     */
    int deleteById(Long accumulationFundAccountId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_accumulation_fund_account
     *
     * @mbggenerated
     */
    int insert(AfAccumulationFundAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_accumulation_fund_account
     *
     * @mbggenerated
     */
    int insertSelective(AfAccumulationFundAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_accumulation_fund_account
     *
     * @mbggenerated
     */
    AfAccumulationFundAccountVO selectByPrimaryKey(Long accumulationFundAccountId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_accumulation_fund_account
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AfAccumulationFundAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_accumulation_fund_account
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AfAccumulationFundAccount record);
    
    /**
     * 根据公司代码查询企业公积金账号
     * @param companyId 企业代码
     * @return
     */
    List<AfAccumulationFundAccount> getAccumulationFundProfileByCompanyId(Long companyId);
}