package com.jabava.dao.accumulationfund;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.jabava.pojo.accumulationfund.AfPaymentBillPersonDetail;

public interface AfPaymentBillPersonDetailMapper {
	List<Map<String,Object>> listGroupDetail(Long afPaymentBillId);
	
	List<Map<String,Object>> selectByBillPersonId(Long afPaymentBillPersonId);
	
	List<Map<String,Object>> listGroupDetailZy(@Param("afPaymentBillId")Long afPaymentBillId,
			@Param("lastSsPaymentBillId")Long lastSsPaymentBillId);
	
	List<Map<String,Object>> selectZyByBillId(@Param("afPaymentBillId")Long afPaymentBillId,
			@Param("lastSsPaymentBillId")Long lastSsPaymentBillId);
	
	List<Map<String,Object>> listGroupDetailJy(@Param("afPaymentBillId")Long afPaymentBillId,
			@Param("lastSsPaymentBillId")Long lastSsPaymentBillId);
	
	List<Map<String,Object>> selectJyByBillId(@Param("afPaymentBillId")Long afPaymentBillId,
			@Param("lastSsPaymentBillId")Long lastSsPaymentBillId);
	
	List<Map<String,Object>> listGroupDetailTj(@Param("afPaymentBillId")Long afPaymentBillId,
			@Param("lastSsPaymentBillId")Long lastSsPaymentBillId);
	
	List<Map<String,Object>> selectTjByBillId(@Param("afPaymentBillId")Long afPaymentBillId,
			@Param("lastSsPaymentBillId")Long lastSsPaymentBillId);
	
	List<Map<String,Object>> listGroupDetailBj(@Param("afPaymentBillId")Long afPaymentBillId);
	
	List<Map<String,Object>> selectBjByBillId(@Param("afPaymentBillId")Long afPaymentBillId);

	List<Map<String,Object>> listGroupDetailByPerson(Map<String,Object> params);
	
	List<Map<String, Object>> listPersonDetail(Long afPaymentBillPersonId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_payment_bill_person_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long afPaymentBillPersonDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_payment_bill_person_detail
     *
     * @mbggenerated
     */
    int insert(AfPaymentBillPersonDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_payment_bill_person_detail
     *
     * @mbggenerated
     */
    int insertSelective(AfPaymentBillPersonDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_payment_bill_person_detail
     *
     * @mbggenerated
     */
    AfPaymentBillPersonDetail selectByPrimaryKey(Long afPaymentBillPersonDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_payment_bill_person_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AfPaymentBillPersonDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_payment_bill_person_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AfPaymentBillPersonDetail record);
}