package com.jabava.dao.accumulationfund;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.jabava.pojo.accumulationfund.AfPaymentBill;

public interface AfPaymentBillMapper {
	/**
	 * 公积金汇缴列表
	 */
	List<AfPaymentBill> listPaymentBillPage(Map<String, Object> params);

	AfPaymentBill getValidPaymentBill(@Param("companyId")Long companyId, @Param("accumulationFundAccountId")Long accumulationFundAccountId, 
			@Param("month")String month);

	AfPaymentBill selectById(@Param("companyId")Long companyId, @Param("afPaymentBillId")Long afPaymentBillId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_payment_bill
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long afPaymentBillId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_payment_bill
     *
     * @mbggenerated
     */
    int insert(AfPaymentBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_payment_bill
     *
     * @mbggenerated
     */
    int insertSelective(AfPaymentBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_payment_bill
     *
     * @mbggenerated
     */
    AfPaymentBill selectByPrimaryKey(Long afPaymentBillId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_payment_bill
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AfPaymentBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_payment_bill
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AfPaymentBill record);
}