package com.jabava.dao.report;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.jabava.pojo.report.EhrReport;

public interface EhrReportMapper {
	List<EhrReport> listReportPage(Map<String, Object> params);
	
	EhrReport selectByTypeAndName(@Param("companyId")Long companyId, @Param("reportType")String reportType, 
			@Param("reportName")String reportName);
	
	int deleteById(@Param("companyId")Long companyId, @Param("reportId")Long reportId);
	
	EhrReport selectByReportId(@Param("companyId")Long companyId, @Param("reportId")Long reportId);
	
	List<EhrReport> listReportByType(@Param("companyId")Long companyId, @Param("reportType")String reportType);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_report
     *
     * @mbggenerated Thu Apr 07 11:45:34 CST 2016
     */
    int deleteByPrimaryKey(Long reportId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_report
     *
     * @mbggenerated Thu Apr 07 11:45:34 CST 2016
     */
    int insert(EhrReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_report
     *
     * @mbggenerated Thu Apr 07 11:45:34 CST 2016
     */
    int insertSelective(EhrReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_report
     *
     * @mbggenerated Thu Apr 07 11:45:34 CST 2016
     */
    EhrReport selectByPrimaryKey(Long reportId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_report
     *
     * @mbggenerated Thu Apr 07 11:45:34 CST 2016
     */
    int updateByPrimaryKeySelective(EhrReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_report
     *
     * @mbggenerated Thu Apr 07 11:45:34 CST 2016
     */
    int updateByPrimaryKey(EhrReport record);
}