package com.jabava.dao.common;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.jabava.pojo.common.EhrCommonData;

public interface EhrCommonDataMapper {
	List<EhrCommonData> listByCommonDataType(Integer commonDataType);
	
	EhrCommonData selectByTypeAndCode(@Param("commonDataType")Integer commonDataType, @Param("commonDataCode")String commonDataCode);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_common_data
     *
     * @mbggenerated Tue Apr 12 12:05:38 CST 2016
     */
    int deleteByPrimaryKey(Long commonDataId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_common_data
     *
     * @mbggenerated Tue Apr 12 12:05:38 CST 2016
     */
    int insert(EhrCommonData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_common_data
     *
     * @mbggenerated Tue Apr 12 12:05:38 CST 2016
     */
    int insertSelective(EhrCommonData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_common_data
     *
     * @mbggenerated Tue Apr 12 12:05:38 CST 2016
     */
    EhrCommonData selectByPrimaryKey(Long commonDataId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_common_data
     *
     * @mbggenerated Tue Apr 12 12:05:38 CST 2016
     */
    int updateByPrimaryKeySelective(EhrCommonData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_common_data
     *
     * @mbggenerated Tue Apr 12 12:05:38 CST 2016
     */
    int updateByPrimaryKey(EhrCommonData record);
}