package com.jabava.dao.common;

import org.apache.ibatis.annotations.Param;

import com.jabava.pojo.common.EhrSequence;

public interface EhrSequenceMapper {
	EhrSequence queryByParams(EhrSequence paramSequence);
	
	int updateByIdAndValue(@Param("id")Long id, @Param("value")Long value);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_sequence
     *
     * @mbggenerated Sun Jun 12 15:55:05 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_sequence
     *
     * @mbggenerated Sun Jun 12 15:55:05 CST 2016
     */
    int insert(EhrSequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_sequence
     *
     * @mbggenerated Sun Jun 12 15:55:05 CST 2016
     */
    int insertSelective(EhrSequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_sequence
     *
     * @mbggenerated Sun Jun 12 15:55:05 CST 2016
     */
    EhrSequence selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_sequence
     *
     * @mbggenerated Sun Jun 12 15:55:05 CST 2016
     */
    int updateByPrimaryKeySelective(EhrSequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_sequence
     *
     * @mbggenerated Sun Jun 12 15:55:05 CST 2016
     */
    int updateByPrimaryKey(EhrSequence record);
}