package com.jabava.dao.employee;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.jabava.pojo.employee.EhrProject;

public interface EhrProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_project
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    int deleteByPrimaryKey(Long projectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_project
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    int insert(EhrProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_project
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    int insertSelective(EhrProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_project
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    EhrProject selectByPrimaryKey(Long projectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_project
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    int updateByPrimaryKeySelective(EhrProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_project
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    int updateByPrimaryKey(EhrProject record);
    
    List<EhrProject> getByPersonId(@Param("personId") Long personId);
}