package com.jabava.dao.employee;

import java.util.List;

import com.jabava.pojo.employee.EhrPosition;
import com.jabava.pojo.employee.EhrPositionVO;
import com.jabava.pojo.manage.EhrPerson;
import com.jabava.pojo.manage.EhrPersonVO;
/**
 * 岗位信息
 *
 * @version $Id: EhrPositionMapper.java, 
 * v 0.1 2016年2月17日 下午5:45:13 
 * <pre>
 * @author steven.chen
 * @date 2016年2月17日 下午5:45:13 
 * </pre>
 */
public interface EhrPositionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_position
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long positionId);
    /**
     * 根据员工ID和公司ID查询 岗位信息
     * <pre>
     * @author steven.chen
     * @date 2016年2月19日 下午2:13:56 
     * </pre>
     *
     * @param ehrPerson
     * @return
     */
    List<EhrPosition> getPositionByPersonIdAndCompanyId(EhrPerson ehrPerson); 
    /**
     * 根据工号 查询 岗位信息
     *  参数有  工号jobNumber   公司ID  companyId
     * <pre>
     * @author steven.chen
     * @date 2016年2月19日 下午2:13:56 
     * </pre>
     *
     * @param ehrPerson
     * @return
     */
    List<EhrPerson> getPositionByEmployeeNumberAndCompanyId(EhrPerson ehrPerson); 

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_position
     *
     * @mbggenerated
     */
    int insert(EhrPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_position
     *
     * @mbggenerated
     */
    int insertSelective(EhrPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_position
     *
     * @mbggenerated
     */
    EhrPosition selectByPrimaryKey(Long positionId);
    /**
     * 根据PersonId获取岗位信息
     * <pre>
     * @author steven.chen
     * @date 2016年2月18日 下午2:04:04 
     * </pre>
     *
     * @param personId
     * @return
     */
    EhrPositionVO selectByPersonId(Long personId);
    
    public  EhrPersonVO selectPositionByPersonId(Long personId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_position
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EhrPosition record);
    /**
     * 根据personId更新岗位信息
     * <pre>
     * @author steven.chen
     * @date 2016年2月24日 上午11:10:31 
     * </pre>
     *
     * @param ehrPosition
     * @return
     */
    int updateByPersonId(EhrPosition ehrPosition);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_position
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EhrPosition record);
}