package com.jabava.pojo.employee;

import java.util.Date;

import com.jabava.core.EnumConstents.WorkContractProperty;
import com.jabava.core.EnumConstents.WorkContractType;
import com.jabava.pojo.manage.EhrOrganization;

public class EhrContractVO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_contract.contract_id
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    private Long contractId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_contract.person_id
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    private Long personId;
    //合同类型显示
    private String contractTypeShow;
    //合同性质显示
    private String contractPropertyShow;
    //主体
    private EhrOrganization ehrOrganization;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_contract.contract_type
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    private Integer contractType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_contract.contract_start_date
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    private Date contractStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_contract.contract_end_date
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    private Date contractEndDate;
    private String contractEndDate1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_contract.trial_month
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    private Byte trialMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_contract.contract_month
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    private Byte contractMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_contract.contract_property
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    private Integer contractProperty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_contract.memo
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_contract.create_user_id
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    private Long createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_contract.create_user_name
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    private String createUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_contract.create_date
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_contract.last_modify_user_id
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    private Long lastModifyUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_contract.last_modify_user_name
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    private String lastModifyUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_contract.last_modify_date
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    private Date lastModifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_contract.old_expire_date
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    private Date oldExpireDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_contract.flag
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    private Byte flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_contract.contract_subject
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    private Long contractSubject;
    
    private String jobNumber;
    
    private String employeeName;
    
    private String mobile;
    
    private String email;
    
    private String org;
    
    private String post;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_contract.contract_id
     *
     * @return the value of ehr_contract.contract_id 
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public String getContractEndDate1() {
    	return contractEndDate1;
    }
    
    public void setContractEndDate1(String contractEndDate1) {
    	this.contractEndDate1 = contractEndDate1;
    }
    
    public Long getContractId() {
        return contractId;
    }


	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_contract.contract_id
     *
     * @param contractId the value for ehr_contract.contract_id
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public void setContractId(Long contractId) {
        this.contractId = contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_contract.person_id
     *
     * @return the value of ehr_contract.person_id
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public Long getPersonId() {
        return personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_contract.person_id
     *
     * @param personId the value for ehr_contract.person_id
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public void setPersonId(Long personId) {
        this.personId = personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_contract.contract_type
     *
     * @return the value of ehr_contract.contract_type
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public Integer getContractType() {
        return contractType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_contract.contract_type
     *
     * @param contractType the value for ehr_contract.contract_type
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public void setContractType(Integer contractType) {
        this.contractType = contractType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_contract.contract_start_date
     *
     * @return the value of ehr_contract.contract_start_date
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public Date getContractStartDate() {
        return contractStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_contract.contract_start_date
     *
     * @param contractStartDate the value for ehr_contract.contract_start_date
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public void setContractStartDate(Date contractStartDate) {
        this.contractStartDate = contractStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_contract.contract_end_date
     *
     * @return the value of ehr_contract.contract_end_date
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public Date getContractEndDate() {
        return contractEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_contract.contract_end_date
     *
     * @param contractEndDate the value for ehr_contract.contract_end_date
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public void setContractEndDate(Date contractEndDate) {
        this.contractEndDate = contractEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_contract.trial_month
     *
     * @return the value of ehr_contract.trial_month
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public Byte getTrialMonth() {
        return trialMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_contract.trial_month
     *
     * @param trialMonth the value for ehr_contract.trial_month
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public void setTrialMonth(Byte trialMonth) {
        this.trialMonth = trialMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_contract.contract_month
     *
     * @return the value of ehr_contract.contract_month
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public Byte getContractMonth() {
        return contractMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_contract.contract_month
     *
     * @param contractMonth the value for ehr_contract.contract_month
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public void setContractMonth(Byte contractMonth) {
        this.contractMonth = contractMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_contract.contract_property
     *
     * @return the value of ehr_contract.contract_property
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public Integer getContractProperty() {
        return contractProperty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_contract.contract_property
     *
     * @param contractProperty the value for ehr_contract.contract_property
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public void setContractProperty(Integer contractProperty) {
        this.contractProperty = contractProperty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_contract.memo
     *
     * @return the value of ehr_contract.memo
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_contract.memo
     *
     * @param memo the value for ehr_contract.memo
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public void setMemo(String memo) {
        this.memo = memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_contract.create_user_id
     *
     * @return the value of ehr_contract.create_user_id
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_contract.create_user_id
     *
     * @param createUserId the value for ehr_contract.create_user_id
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_contract.create_user_name
     *
     * @return the value of ehr_contract.create_user_name
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public String getCreateUserName() {
        return createUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_contract.create_user_name
     *
     * @param createUserName the value for ehr_contract.create_user_name
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public void setCreateUserName(String createUserName) {
        this.createUserName = createUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_contract.create_date
     *
     * @return the value of ehr_contract.create_date
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_contract.create_date
     *
     * @param createDate the value for ehr_contract.create_date
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_contract.last_modify_user_id
     *
     * @return the value of ehr_contract.last_modify_user_id
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public Long getLastModifyUserId() {
        return lastModifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_contract.last_modify_user_id
     *
     * @param lastModifyUserId the value for ehr_contract.last_modify_user_id
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public void setLastModifyUserId(Long lastModifyUserId) {
        this.lastModifyUserId = lastModifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_contract.last_modify_user_name
     *
     * @return the value of ehr_contract.last_modify_user_name
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public String getLastModifyUserName() {
        return lastModifyUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_contract.last_modify_user_name
     *
     * @param lastModifyUserName the value for ehr_contract.last_modify_user_name
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public void setLastModifyUserName(String lastModifyUserName) {
        this.lastModifyUserName = lastModifyUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_contract.last_modify_date
     *
     * @return the value of ehr_contract.last_modify_date
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public Date getLastModifyDate() {
        return lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_contract.last_modify_date
     *
     * @param lastModifyDate the value for ehr_contract.last_modify_date
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public void setLastModifyDate(Date lastModifyDate) {
        this.lastModifyDate = lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_contract.old_expire_date
     *
     * @return the value of ehr_contract.old_expire_date
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public Date getOldExpireDate() {
        return oldExpireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_contract.old_expire_date
     *
     * @param oldExpireDate the value for ehr_contract.old_expire_date
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public void setOldExpireDate(Date oldExpireDate) {
        this.oldExpireDate = oldExpireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_contract.flag
     *
     * @return the value of ehr_contract.flag
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public Byte getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_contract.flag
     *
     * @param flag the value for ehr_contract.flag
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public void setFlag(Byte flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_contract.contract_subject
     *
     * @return the value of ehr_contract.contract_subject
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public Long getContractSubject() {
        return contractSubject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_contract.contract_subject
     *
     * @param contractSubject the value for ehr_contract.contract_subject
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public void setContractSubject(Long contractSubject) {
        this.contractSubject = contractSubject;
    }

	public String getJobNumber() {
		return jobNumber;
	}

	public void setJobNumber(String jobNumber) {
		this.jobNumber = jobNumber;
	}

	public String getEmployeeName() {
		return employeeName;
	}

	public void setEmployeeName(String employeeName) {
		this.employeeName = employeeName;
	}

	public String getMobile() {
		return mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getOrg() {
		return org;
	}

	public void setOrg(String org) {
		this.org = org;
	}

	public String getPost() {
		return post;
	}

	public void setPost(String post) {
		this.post = post;
	}	
	public String getContractTypeShow() {
		if(this.getContractType()!=null){
			if(this.getContractType().equals(WorkContractType.WORK_CONTRACT_TYPE_1.getValue())){				
				return "固定期限";
			}else if(this.getContractType().equals(WorkContractType.WORK_CONTRACT_TYPE_2.getValue())){
				return "无固定期限";
			}else if(this.getContractType().equals(WorkContractType.WORK_CONTRACT_TYPE_3.getValue())){
				return "以完成一定工作量的协议";
			}else if(this.getContractType().equals(WorkContractType.WORK_CONTRACT_TYPE_4.getValue())){
				return "劳务";
			}else if(this.getContractType().equals(WorkContractType.WORK_CONTRACT_TYPE_5.getValue())){
				return "派遣";
			}else if(this.getContractType().equals(WorkContractType.WORK_CONTRACT_TYPE_6.getValue())){
				return "实习";
			}
		}
		return contractTypeShow;
	}

	public void setContractTypeShow(String contractTypeShow) {
		this.contractTypeShow = contractTypeShow;
	}

	public String getContractPropertyShow() {
		if(this.getContractProperty()!=null){
			if(this.getContractProperty().equals(WorkContractProperty.FIRST_SIGN.getValue())){
				return "首签";
			}else if(this.getContractProperty().equals(WorkContractProperty.RENEWAL.getValue())){
				return "续签";
			}
			
		}
		return contractPropertyShow;
	}

	public void setContractPropertyShow(String contractPropertyShow) {
		this.contractPropertyShow = contractPropertyShow;
	}

	public EhrOrganization getEhrOrganization() {
		return ehrOrganization;
	}

	public void setEhrOrganization(EhrOrganization ehrOrganization) {
		this.ehrOrganization = ehrOrganization;
	}
    
}