package com.jabava.pojo.employee;

import java.util.Date;

public class EhrExperience {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_experience.experience_id
     *
     * @mbggenerated Fri Jul 01 16:13:07 CST 2016
     */
    private Long experienceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_experience.person_id
     *
     * @mbggenerated Fri Jul 01 16:13:07 CST 2016
     */
    private Long personId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_experience.employer
     *
     * @mbggenerated Fri Jul 01 16:13:07 CST 2016
     */
    private String employer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_experience.work_Post
     *
     * @mbggenerated Fri Jul 01 16:13:07 CST 2016
     */
    private String workPost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_experience.start_date
     *
     * @mbggenerated Fri Jul 01 16:13:07 CST 2016
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_experience.end_date
     *
     * @mbggenerated Fri Jul 01 16:13:07 CST 2016
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_experience.prove_mobile
     *
     * @mbggenerated Fri Jul 01 16:13:07 CST 2016
     */
    private String proveMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_experience.authenticator
     *
     * @mbggenerated Fri Jul 01 16:13:07 CST 2016
     */
    private String authenticator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_experience.description
     *
     * @mbggenerated Fri Jul 01 16:13:07 CST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_experience.background_investigation
     *
     * @mbggenerated Fri Jul 01 16:13:07 CST 2016
     */
    private String backgroundInvestigation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_experience.memo
     *
     * @mbggenerated Fri Jul 01 16:13:07 CST 2016
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_experience.create_user_id
     *
     * @mbggenerated Fri Jul 01 16:13:07 CST 2016
     */
    private Long createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_experience.create_user_name
     *
     * @mbggenerated Fri Jul 01 16:13:07 CST 2016
     */
    private String createUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_experience.create_date
     *
     * @mbggenerated Fri Jul 01 16:13:07 CST 2016
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_experience.last_modify_user_id
     *
     * @mbggenerated Fri Jul 01 16:13:07 CST 2016
     */
    private Long lastModifyUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_experience.last_modify_user_name
     *
     * @mbggenerated Fri Jul 01 16:13:07 CST 2016
     */
    private String lastModifyUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_experience.last_modify_date
     *
     * @mbggenerated Fri Jul 01 16:13:07 CST 2016
     */
    private Date lastModifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_experience.is_delete
     *
     * @mbggenerated Fri Jul 01 16:13:07 CST 2016
     */
    private Integer isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_experience.experience_id
     *
     * @return the value of ehr_experience.experience_id
     *
     * @mbggenerated Fri Jul 01 16:13:07 CST 2016
     */
    public Long getExperienceId() {
        return experienceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_experience.experience_id
     *
     * @param experienceId the value for ehr_experience.experience_id
     *
     * @mbggenerated Fri Jul 01 16:13:07 CST 2016
     */
    public void setExperienceId(Long experienceId) {
        this.experienceId = experienceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_experience.person_id
     *
     * @return the value of ehr_experience.person_id
     *
     * @mbggenerated Fri Jul 01 16:13:07 CST 2016
     */
    public Long getPersonId() {
        return personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_experience.person_id
     *
     * @param personId the value for ehr_experience.person_id
     *
     * @mbggenerated Fri Jul 01 16:13:07 CST 2016
     */
    public void setPersonId(Long personId) {
        this.personId = personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_experience.employer
     *
     * @return the value of ehr_experience.employer
     *
     * @mbggenerated Fri Jul 01 16:13:07 CST 2016
     */
    public String getEmployer() {
        return employer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_experience.employer
     *
     * @param employer the value for ehr_experience.employer
     *
     * @mbggenerated Fri Jul 01 16:13:07 CST 2016
     */
    public void setEmployer(String employer) {
        this.employer = employer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_experience.work_Post
     *
     * @return the value of ehr_experience.work_Post
     *
     * @mbggenerated Fri Jul 01 16:13:07 CST 2016
     */
    public String getWorkPost() {
        return workPost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_experience.work_Post
     *
     * @param workPost the value for ehr_experience.work_Post
     *
     * @mbggenerated Fri Jul 01 16:13:07 CST 2016
     */
    public void setWorkPost(String workPost) {
        this.workPost = workPost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_experience.start_date
     *
     * @return the value of ehr_experience.start_date
     *
     * @mbggenerated Fri Jul 01 16:13:07 CST 2016
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_experience.start_date
     *
     * @param startDate the value for ehr_experience.start_date
     *
     * @mbggenerated Fri Jul 01 16:13:07 CST 2016
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_experience.end_date
     *
     * @return the value of ehr_experience.end_date
     *
     * @mbggenerated Fri Jul 01 16:13:07 CST 2016
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_experience.end_date
     *
     * @param endDate the value for ehr_experience.end_date
     *
     * @mbggenerated Fri Jul 01 16:13:07 CST 2016
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_experience.prove_mobile
     *
     * @return the value of ehr_experience.prove_mobile
     *
     * @mbggenerated Fri Jul 01 16:13:07 CST 2016
     */
    public String getProveMobile() {
        return proveMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_experience.prove_mobile
     *
     * @param proveMobile the value for ehr_experience.prove_mobile
     *
     * @mbggenerated Fri Jul 01 16:13:07 CST 2016
     */
    public void setProveMobile(String proveMobile) {
        this.proveMobile = proveMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_experience.authenticator
     *
     * @return the value of ehr_experience.authenticator
     *
     * @mbggenerated Fri Jul 01 16:13:07 CST 2016
     */
    public String getAuthenticator() {
        return authenticator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_experience.authenticator
     *
     * @param authenticator the value for ehr_experience.authenticator
     *
     * @mbggenerated Fri Jul 01 16:13:07 CST 2016
     */
    public void setAuthenticator(String authenticator) {
        this.authenticator = authenticator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_experience.description
     *
     * @return the value of ehr_experience.description
     *
     * @mbggenerated Fri Jul 01 16:13:07 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_experience.description
     *
     * @param description the value for ehr_experience.description
     *
     * @mbggenerated Fri Jul 01 16:13:07 CST 2016
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_experience.background_investigation
     *
     * @return the value of ehr_experience.background_investigation
     *
     * @mbggenerated Fri Jul 01 16:13:07 CST 2016
     */
    public String getBackgroundInvestigation() {
        return backgroundInvestigation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_experience.background_investigation
     *
     * @param backgroundInvestigation the value for ehr_experience.background_investigation
     *
     * @mbggenerated Fri Jul 01 16:13:07 CST 2016
     */
    public void setBackgroundInvestigation(String backgroundInvestigation) {
        this.backgroundInvestigation = backgroundInvestigation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_experience.memo
     *
     * @return the value of ehr_experience.memo
     *
     * @mbggenerated Fri Jul 01 16:13:07 CST 2016
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_experience.memo
     *
     * @param memo the value for ehr_experience.memo
     *
     * @mbggenerated Fri Jul 01 16:13:07 CST 2016
     */
    public void setMemo(String memo) {
        this.memo = memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_experience.create_user_id
     *
     * @return the value of ehr_experience.create_user_id
     *
     * @mbggenerated Fri Jul 01 16:13:07 CST 2016
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_experience.create_user_id
     *
     * @param createUserId the value for ehr_experience.create_user_id
     *
     * @mbggenerated Fri Jul 01 16:13:07 CST 2016
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_experience.create_user_name
     *
     * @return the value of ehr_experience.create_user_name
     *
     * @mbggenerated Fri Jul 01 16:13:07 CST 2016
     */
    public String getCreateUserName() {
        return createUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_experience.create_user_name
     *
     * @param createUserName the value for ehr_experience.create_user_name
     *
     * @mbggenerated Fri Jul 01 16:13:07 CST 2016
     */
    public void setCreateUserName(String createUserName) {
        this.createUserName = createUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_experience.create_date
     *
     * @return the value of ehr_experience.create_date
     *
     * @mbggenerated Fri Jul 01 16:13:07 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_experience.create_date
     *
     * @param createDate the value for ehr_experience.create_date
     *
     * @mbggenerated Fri Jul 01 16:13:07 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_experience.last_modify_user_id
     *
     * @return the value of ehr_experience.last_modify_user_id
     *
     * @mbggenerated Fri Jul 01 16:13:07 CST 2016
     */
    public Long getLastModifyUserId() {
        return lastModifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_experience.last_modify_user_id
     *
     * @param lastModifyUserId the value for ehr_experience.last_modify_user_id
     *
     * @mbggenerated Fri Jul 01 16:13:07 CST 2016
     */
    public void setLastModifyUserId(Long lastModifyUserId) {
        this.lastModifyUserId = lastModifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_experience.last_modify_user_name
     *
     * @return the value of ehr_experience.last_modify_user_name
     *
     * @mbggenerated Fri Jul 01 16:13:07 CST 2016
     */
    public String getLastModifyUserName() {
        return lastModifyUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_experience.last_modify_user_name
     *
     * @param lastModifyUserName the value for ehr_experience.last_modify_user_name
     *
     * @mbggenerated Fri Jul 01 16:13:07 CST 2016
     */
    public void setLastModifyUserName(String lastModifyUserName) {
        this.lastModifyUserName = lastModifyUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_experience.last_modify_date
     *
     * @return the value of ehr_experience.last_modify_date
     *
     * @mbggenerated Fri Jul 01 16:13:07 CST 2016
     */
    public Date getLastModifyDate() {
        return lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_experience.last_modify_date
     *
     * @param lastModifyDate the value for ehr_experience.last_modify_date
     *
     * @mbggenerated Fri Jul 01 16:13:07 CST 2016
     */
    public void setLastModifyDate(Date lastModifyDate) {
        this.lastModifyDate = lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_experience.is_delete
     *
     * @return the value of ehr_experience.is_delete
     *
     * @mbggenerated Fri Jul 01 16:13:07 CST 2016
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_experience.is_delete
     *
     * @param isDelete the value for ehr_experience.is_delete
     *
     * @mbggenerated Fri Jul 01 16:13:07 CST 2016
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }
}