package com.jabava.pojo.employee;

import java.util.Date;

public class EhrResume {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_resume.resume_id
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    private Long resumeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_resume.person_id
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    private Long personId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_resume.start_date
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_resume.end_date
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_resume.company_name
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_resume.work_post
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    private String workPost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_resume.description
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_resume.certifier
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    private String certifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_resume.create_user_id
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    private Long createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_resume.create_user_name
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    private String createUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_resume.create_date
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_resume.last_modify_user_id
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    private Long lastModifyUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_resume.last_modify_user_name
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    private String lastModifyUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_resume.last_modify_date
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    private Date lastModifyDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_resume.resume_id
     *
     * @return the value of ehr_resume.resume_id
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public Long getResumeId() {
        return resumeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_resume.resume_id
     *
     * @param resumeId the value for ehr_resume.resume_id
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public void setResumeId(Long resumeId) {
        this.resumeId = resumeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_resume.person_id
     *
     * @return the value of ehr_resume.person_id
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public Long getPersonId() {
        return personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_resume.person_id
     *
     * @param personId the value for ehr_resume.person_id
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public void setPersonId(Long personId) {
        this.personId = personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_resume.start_date
     *
     * @return the value of ehr_resume.start_date
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_resume.start_date
     *
     * @param startDate the value for ehr_resume.start_date
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_resume.end_date
     *
     * @return the value of ehr_resume.end_date
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_resume.end_date
     *
     * @param endDate the value for ehr_resume.end_date
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_resume.company_name
     *
     * @return the value of ehr_resume.company_name
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_resume.company_name
     *
     * @param companyName the value for ehr_resume.company_name
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_resume.work_post
     *
     * @return the value of ehr_resume.work_post
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public String getWorkPost() {
        return workPost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_resume.work_post
     *
     * @param workPost the value for ehr_resume.work_post
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public void setWorkPost(String workPost) {
        this.workPost = workPost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_resume.description
     *
     * @return the value of ehr_resume.description
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_resume.description
     *
     * @param description the value for ehr_resume.description
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_resume.certifier
     *
     * @return the value of ehr_resume.certifier
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public String getCertifier() {
        return certifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_resume.certifier
     *
     * @param certifier the value for ehr_resume.certifier
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public void setCertifier(String certifier) {
        this.certifier = certifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_resume.create_user_id
     *
     * @return the value of ehr_resume.create_user_id
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_resume.create_user_id
     *
     * @param createUserId the value for ehr_resume.create_user_id
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_resume.create_user_name
     *
     * @return the value of ehr_resume.create_user_name
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public String getCreateUserName() {
        return createUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_resume.create_user_name
     *
     * @param createUserName the value for ehr_resume.create_user_name
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public void setCreateUserName(String createUserName) {
        this.createUserName = createUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_resume.create_date
     *
     * @return the value of ehr_resume.create_date
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_resume.create_date
     *
     * @param createDate the value for ehr_resume.create_date
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_resume.last_modify_user_id
     *
     * @return the value of ehr_resume.last_modify_user_id
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public Long getLastModifyUserId() {
        return lastModifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_resume.last_modify_user_id
     *
     * @param lastModifyUserId the value for ehr_resume.last_modify_user_id
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public void setLastModifyUserId(Long lastModifyUserId) {
        this.lastModifyUserId = lastModifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_resume.last_modify_user_name
     *
     * @return the value of ehr_resume.last_modify_user_name
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public String getLastModifyUserName() {
        return lastModifyUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_resume.last_modify_user_name
     *
     * @param lastModifyUserName the value for ehr_resume.last_modify_user_name
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public void setLastModifyUserName(String lastModifyUserName) {
        this.lastModifyUserName = lastModifyUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_resume.last_modify_date
     *
     * @return the value of ehr_resume.last_modify_date
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public Date getLastModifyDate() {
        return lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_resume.last_modify_date
     *
     * @param lastModifyDate the value for ehr_resume.last_modify_date
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public void setLastModifyDate(Date lastModifyDate) {
        this.lastModifyDate = lastModifyDate;
    }
}