package com.jabava.pojo.employee;

import java.math.BigDecimal;
import java.util.Date;

import com.jabava.utils.enums.JabavaEnum.RewardType;

public class EhrRewards {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_rewards.reward_id
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    private Long rewardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_rewards.person_id
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    private Long personId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_rewards.reward_date
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    private Date rewardDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_rewards.reward_type
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    private Integer rewardType;
    private String rewardTypeShow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_rewards.reward_cost
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    private BigDecimal rewardCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_rewards.memo
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_rewards.create_user_id
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    private Long createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_rewards.create_user_name
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    private String createUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_rewards.create_date
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_rewards.last_modify_user_id
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    private Long lastModifyUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_rewards.last_modify_user_name
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    private String lastModifyUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_rewards.last_modify_date
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    private Date lastModifyDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_rewards.reward_id
     *
     * @return the value of ehr_rewards.reward_id
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public Long getRewardId() {
        return rewardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_rewards.reward_id
     *
     * @param rewardId the value for ehr_rewards.reward_id
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public void setRewardId(Long rewardId) {
        this.rewardId = rewardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_rewards.person_id
     *
     * @return the value of ehr_rewards.person_id
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public Long getPersonId() {
        return personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_rewards.person_id
     *
     * @param personId the value for ehr_rewards.person_id
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public void setPersonId(Long personId) {
        this.personId = personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_rewards.reward_date
     *
     * @return the value of ehr_rewards.reward_date
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public Date getRewardDate() {
        return rewardDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_rewards.reward_date
     *
     * @param rewardDate the value for ehr_rewards.reward_date
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public void setRewardDate(Date rewardDate) {
        this.rewardDate = rewardDate;
    }

  

    public Integer getRewardType() {
		return rewardType;
	}

	public void setRewardType(Integer rewardType) {
		this.rewardType = rewardType;
	}

	public String getRewardTypeShow() {
		if(this.getRewardType()!=null){
			if(this.getRewardType().equals(RewardType.REWARD.getValue())){
				return "奖励";
			}else if(this.getRewardType().equals(RewardType.PUNISHMENT.getValue())){
				return "惩罚";
			}
		}
		return rewardTypeShow;
	}

	public void setRewardTypeShow(String rewardTypeShow) {
		this.rewardTypeShow = rewardTypeShow;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_rewards.reward_cost
     *
     * @return the value of ehr_rewards.reward_cost
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public BigDecimal getRewardCost() {
        return rewardCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_rewards.reward_cost
     *
     * @param rewardCost the value for ehr_rewards.reward_cost
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public void setRewardCost(BigDecimal rewardCost) {
        this.rewardCost = rewardCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_rewards.memo
     *
     * @return the value of ehr_rewards.memo
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_rewards.memo
     *
     * @param memo the value for ehr_rewards.memo
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public void setMemo(String memo) {
        this.memo = memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_rewards.create_user_id
     *
     * @return the value of ehr_rewards.create_user_id
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_rewards.create_user_id
     *
     * @param createUserId the value for ehr_rewards.create_user_id
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_rewards.create_user_name
     *
     * @return the value of ehr_rewards.create_user_name
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public String getCreateUserName() {
        return createUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_rewards.create_user_name
     *
     * @param createUserName the value for ehr_rewards.create_user_name
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public void setCreateUserName(String createUserName) {
        this.createUserName = createUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_rewards.create_date
     *
     * @return the value of ehr_rewards.create_date
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_rewards.create_date
     *
     * @param createDate the value for ehr_rewards.create_date
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_rewards.last_modify_user_id
     *
     * @return the value of ehr_rewards.last_modify_user_id
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public Long getLastModifyUserId() {
        return lastModifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_rewards.last_modify_user_id
     *
     * @param lastModifyUserId the value for ehr_rewards.last_modify_user_id
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public void setLastModifyUserId(Long lastModifyUserId) {
        this.lastModifyUserId = lastModifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_rewards.last_modify_user_name
     *
     * @return the value of ehr_rewards.last_modify_user_name
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public String getLastModifyUserName() {
        return lastModifyUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_rewards.last_modify_user_name
     *
     * @param lastModifyUserName the value for ehr_rewards.last_modify_user_name
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public void setLastModifyUserName(String lastModifyUserName) {
        this.lastModifyUserName = lastModifyUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_rewards.last_modify_date
     *
     * @return the value of ehr_rewards.last_modify_date
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public Date getLastModifyDate() {
        return lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_rewards.last_modify_date
     *
     * @param lastModifyDate the value for ehr_rewards.last_modify_date
     *
     * @mbggenerated Wed Jan 13 19:57:44 CST 2016
     */
    public void setLastModifyDate(Date lastModifyDate) {
        this.lastModifyDate = lastModifyDate;
    }
}