package com.jabava.pojo.accumulationfund;

import java.util.Date;
import java.util.List;

import com.jabava.pojo.manage.EhrPerson;
import com.jabava.pojo.policygroup.PolicyGroup;
import com.jabava.pojo.policygroup.SbGroup;
import com.jabava.pojo.socialsecurity.EhrPersonSecurityProfile;
import com.jabava.pojo.tools.EhrCity;

public class AfAccumulationFundAccountVO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_accumulation_fund_account.accumulation_fund_account_id
     *
     * @mbggenerated
     */
    private Long accumulationFundAccountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_accumulation_fund_account.company_id
     *
     * @mbggenerated
     */
    private Long companyId;
    //参保地所在省份的ID
    private Long provinceId;
    //参保地
    private EhrCity city;
    //参保规则
    private String accumulationFundRuleShow;
    //参保地列表
    private List<EhrCity> cityList;
    //政策包列表
    private List<PolicyGroup> policyGroupList;
    //政策包组合列表
    private List<SbGroup> groupList;
    //姓名
    private String personName;
    //政策组合包
    private SbGroup group;
    // 社保档案
    private EhrPersonSecurityProfile personSecurityProfile;
    //人员
    private  EhrPerson person;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_accumulation_fund_account.accumulation_fund_account_name
     *
     * @mbggenerated
     */
    private String accumulationFundAccountName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_accumulation_fund_account.location_city_id
     *
     * @mbggenerated
     */
    private Long locationCityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_accumulation_fund_account.accumulation_fund_code
     *
     * @mbggenerated
     */
    private String accumulationFundCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_accumulation_fund_account.accumulation_fund_role
     *
     * @mbggenerated
     */
    private String accumulationFundRule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_accumulation_fund_account.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_accumulation_fund_account.create_user_id
     *
     * @mbggenerated
     */
    private Long createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_accumulation_fund_account.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_accumulation_fund_account.update_user_id
     *
     * @mbggenerated
     */
    private Long updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_accumulation_fund_account.update_date
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_accumulation_fund_account.is_deleted
     *
     * @mbggenerated
     */
    private Integer isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_accumulation_fund_account.accumulation_fund_account_id
     *
     * @return the value of af_accumulation_fund_account.accumulation_fund_account_id
     *
     * @mbggenerated
     */
    public Long getAccumulationFundAccountId() {
        return accumulationFundAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_accumulation_fund_account.accumulation_fund_account_id
     *
     * @param accumulationFundAccountId the value for af_accumulation_fund_account.accumulation_fund_account_id
     *
     * @mbggenerated
     */
    public void setAccumulationFundAccountId(Long accumulationFundAccountId) {
        this.accumulationFundAccountId = accumulationFundAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_accumulation_fund_account.company_id
     *
     * @return the value of af_accumulation_fund_account.company_id
     *
     * @mbggenerated
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_accumulation_fund_account.company_id
     *
     * @param companyId the value for af_accumulation_fund_account.company_id
     *
     * @mbggenerated
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_accumulation_fund_account.accumulation_fund_account_name
     *
     * @return the value of af_accumulation_fund_account.accumulation_fund_account_name
     *
     * @mbggenerated
     */
    public String getAccumulationFundAccountName() {
        return accumulationFundAccountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_accumulation_fund_account.accumulation_fund_account_name
     *
     * @param accumulationFundAccountName the value for af_accumulation_fund_account.accumulation_fund_account_name
     *
     * @mbggenerated
     */
    public void setAccumulationFundAccountName(String accumulationFundAccountName) {
        this.accumulationFundAccountName = accumulationFundAccountName == null ? null : accumulationFundAccountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_accumulation_fund_account.location_city_id
     *
     * @return the value of af_accumulation_fund_account.location_city_id
     *
     * @mbggenerated
     */
    public Long getLocationCityId() {
        return locationCityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_accumulation_fund_account.location_city_id
     *
     * @param locationCityId the value for af_accumulation_fund_account.location_city_id
     *
     * @mbggenerated
     */
    public void setLocationCityId(Long locationCityId) {
        this.locationCityId = locationCityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_accumulation_fund_account.accumulation_fund_code
     *
     * @return the value of af_accumulation_fund_account.accumulation_fund_code
     *
     * @mbggenerated
     */
    public String getAccumulationFundCode() {
        return accumulationFundCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_accumulation_fund_account.accumulation_fund_code
     *
     * @param accumulationFundCode the value for af_accumulation_fund_account.accumulation_fund_code
     *
     * @mbggenerated
     */
    public void setAccumulationFundCode(String accumulationFundCode) {
        this.accumulationFundCode = accumulationFundCode == null ? null : accumulationFundCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_accumulation_fund_account.accumulation_fund_role
     *
     * @return the value of af_accumulation_fund_account.accumulation_fund_role
     *
     * @mbggenerated
     */
    public String getAccumulationFundRule() {
        return accumulationFundRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_accumulation_fund_account.accumulation_fund_role
     *
     * @param accumulationFundRule the value for af_accumulation_fund_account.accumulation_fund_role
     *
     * @mbggenerated
     */
    public void setAccumulationFundRule(String accumulationFundRule) {
        this.accumulationFundRule = accumulationFundRule == null ? null : accumulationFundRule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_accumulation_fund_account.remark
     *
     * @return the value of af_accumulation_fund_account.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_accumulation_fund_account.remark
     *
     * @param remark the value for af_accumulation_fund_account.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_accumulation_fund_account.create_user_id
     *
     * @return the value of af_accumulation_fund_account.create_user_id
     *
     * @mbggenerated
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_accumulation_fund_account.create_user_id
     *
     * @param createUserId the value for af_accumulation_fund_account.create_user_id
     *
     * @mbggenerated
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_accumulation_fund_account.create_date
     *
     * @return the value of af_accumulation_fund_account.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_accumulation_fund_account.create_date
     *
     * @param createDate the value for af_accumulation_fund_account.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_accumulation_fund_account.update_user_id
     *
     * @return the value of af_accumulation_fund_account.update_user_id
     *
     * @mbggenerated
     */
    public Long getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_accumulation_fund_account.update_user_id
     *
     * @param updateUserId the value for af_accumulation_fund_account.update_user_id
     *
     * @mbggenerated
     */
    public void setUpdateUserId(Long updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_accumulation_fund_account.update_date
     *
     * @return the value of af_accumulation_fund_account.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_accumulation_fund_account.update_date
     *
     * @param updateDate the value for af_accumulation_fund_account.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_accumulation_fund_account.is_deleted
     *
     * @return the value of af_accumulation_fund_account.is_deleted
     *
     * @mbggenerated
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_accumulation_fund_account.is_deleted
     *
     * @param isDeleted the value for af_accumulation_fund_account.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

	public Long getProvinceId() {
		return provinceId;
	}

	public void setProvinceId(Long provinceId) {
		this.provinceId = provinceId;
	}

	public EhrCity getCity() {
		return city;
	}

	public void setCity(EhrCity city) {
		this.city = city;
	}


	public String getAccumulationFundRuleShow() {
		return accumulationFundRuleShow;
	}

	public void setAccumulationFundRuleShow(String accumulationFundRuleShow) {
		this.accumulationFundRuleShow = accumulationFundRuleShow;
	}

	public List<EhrCity> getCityList() {
		return cityList;
	}

	public void setCityList(List<EhrCity> cityList) {
		this.cityList = cityList;
	}

	public List<PolicyGroup> getPolicyGroupList() {
		return policyGroupList;
	}

	public void setPolicyGroupList(List<PolicyGroup> policyGroupList) {
		this.policyGroupList = policyGroupList;
	}

	public List<SbGroup> getGroupList() {
		return groupList;
	}

	public void setGroupList(List<SbGroup> groupList) {
		this.groupList = groupList;
	}

	public String getPersonName() {
		return personName;
	}

	public void setPersonName(String personName) {
		this.personName = personName;
	}

	public SbGroup getGroup() {
		return group;
	}

	public void setGroup(SbGroup group) {
		this.group = group;
	}

	public EhrPersonSecurityProfile getPersonSecurityProfile() {
		return personSecurityProfile;
	}

	public void setPersonSecurityProfile(
			EhrPersonSecurityProfile personSecurityProfile) {
		this.personSecurityProfile = personSecurityProfile;
	}

	public EhrPerson getPerson() {
		return person;
	}

	public void setPerson(EhrPerson person) {
		this.person = person;
	}
    
}