package com.jabava.pojo.accumulationfund;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AfPaymentBillPerson {
	public AfPaymentBillPerson(){
		
	}
	
	public AfPaymentBillPerson(Long psProfileId, Long personId, String accumulationFundAccount){
		this.psProfileId = psProfileId;
		this.personId = personId;
		this.accumulationFundAccount = accumulationFundAccount;
		
		this.bjBaseE = BigDecimal.ZERO;
		this.bjBaseP = BigDecimal.ZERO;
		this.bjAmount = BigDecimal.ZERO;
		this.bjAmountE = BigDecimal.ZERO;
		this.bjAmountP = BigDecimal.ZERO;
		this.hjBaseE = BigDecimal.ZERO;
		this.hjBaseP = BigDecimal.ZERO;
		this.hjAmount = BigDecimal.ZERO;
		this.hjAmountE = BigDecimal.ZERO;
		this.hjAmountP = BigDecimal.ZERO;
	}
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_payment_bill_person.af_payment_bill_person_id
     *
     * @mbggenerated
     */
    private Long afPaymentBillPersonId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_payment_bill_person.af_payment_bill_id
     *
     * @mbggenerated
     */
    private Long afPaymentBillId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_payment_bill_person.ps_profile_id
     *
     * @mbggenerated
     */
    private Long psProfileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_payment_bill_person.person_id
     *
     * @mbggenerated
     */
    private Long personId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_payment_bill_person.accumulation_fund_account
     *
     * @mbggenerated
     */
    private String accumulationFundAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_payment_bill_person.hj_base_e
     *
     * @mbggenerated
     */
    private BigDecimal hjBaseE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_payment_bill_person.hj_base_p
     *
     * @mbggenerated
     */
    private BigDecimal hjBaseP;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_payment_bill_person.hj_amount
     *
     * @mbggenerated
     */
    private BigDecimal hjAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_payment_bill_person.hj_amount_e
     *
     * @mbggenerated
     */
    private BigDecimal hjAmountE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_payment_bill_person.hj_amount_p
     *
     * @mbggenerated
     */
    private BigDecimal hjAmountP;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_payment_bill_person.bj_amount
     *
     * @mbggenerated
     */
    private BigDecimal bjAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_payment_bill_person.bj_amount_e
     *
     * @mbggenerated
     */
    private BigDecimal bjAmountE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_payment_bill_person.bj_amount_p
     *
     * @mbggenerated
     */
    private BigDecimal bjAmountP;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_payment_bill_person.bj_base_e
     *
     * @mbggenerated
     */
    private BigDecimal bjBaseE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_payment_bill_person.bj_base_p
     *
     * @mbggenerated
     */
    private BigDecimal bjBaseP;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_payment_bill_person.create_user_id
     *
     * @mbggenerated
     */
    private Long createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_payment_bill_person.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_payment_bill_person.update_user_id
     *
     * @mbggenerated
     */
    private Long updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_payment_bill_person.update_date
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column af_payment_bill_person.is_deleted
     *
     * @mbggenerated
     */
    private Integer isDeleted;
	
	private String personName;
    
    private List<AfPaymentBillPersonDetail> personDetailList = new ArrayList<AfPaymentBillPersonDetail>();

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_payment_bill_person.af_payment_bill_person_id
     *
     * @return the value of af_payment_bill_person.af_payment_bill_person_id
     *
     * @mbggenerated
     */
    public Long getAfPaymentBillPersonId() {
        return afPaymentBillPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_payment_bill_person.af_payment_bill_person_id
     *
     * @param afPaymentBillPersonId the value for af_payment_bill_person.af_payment_bill_person_id
     *
     * @mbggenerated
     */
    public void setAfPaymentBillPersonId(Long afPaymentBillPersonId) {
        this.afPaymentBillPersonId = afPaymentBillPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_payment_bill_person.af_payment_bill_id
     *
     * @return the value of af_payment_bill_person.af_payment_bill_id
     *
     * @mbggenerated
     */
    public Long getAfPaymentBillId() {
        return afPaymentBillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_payment_bill_person.af_payment_bill_id
     *
     * @param afPaymentBillId the value for af_payment_bill_person.af_payment_bill_id
     *
     * @mbggenerated
     */
    public void setAfPaymentBillId(Long afPaymentBillId) {
        this.afPaymentBillId = afPaymentBillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_payment_bill_person.ps_profile_id
     *
     * @return the value of af_payment_bill_person.ps_profile_id
     *
     * @mbggenerated
     */
    public Long getPsProfileId() {
        return psProfileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_payment_bill_person.ps_profile_id
     *
     * @param psProfileId the value for af_payment_bill_person.ps_profile_id
     *
     * @mbggenerated
     */
    public void setPsProfileId(Long psProfileId) {
        this.psProfileId = psProfileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_payment_bill_person.person_id
     *
     * @return the value of af_payment_bill_person.person_id
     *
     * @mbggenerated
     */
    public Long getPersonId() {
        return personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_payment_bill_person.person_id
     *
     * @param personId the value for af_payment_bill_person.person_id
     *
     * @mbggenerated
     */
    public void setPersonId(Long personId) {
        this.personId = personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_payment_bill_person.accumulation_fund_account
     *
     * @return the value of af_payment_bill_person.accumulation_fund_account
     *
     * @mbggenerated
     */
    public String getAccumulationFundAccount() {
        return accumulationFundAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_payment_bill_person.accumulation_fund_account
     *
     * @param accumulationFundAccount the value for af_payment_bill_person.accumulation_fund_account
     *
     * @mbggenerated
     */
    public void setAccumulationFundAccount(String accumulationFundAccount) {
        this.accumulationFundAccount = accumulationFundAccount == null ? null : accumulationFundAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_payment_bill_person.hj_base_e
     *
     * @return the value of af_payment_bill_person.hj_base_e
     *
     * @mbggenerated
     */
    public BigDecimal getHjBaseE() {
        return hjBaseE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_payment_bill_person.hj_base_e
     *
     * @param hjBaseE the value for af_payment_bill_person.hj_base_e
     *
     * @mbggenerated
     */
    public void setHjBaseE(BigDecimal hjBaseE) {
        this.hjBaseE = hjBaseE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_payment_bill_person.hj_base_p
     *
     * @return the value of af_payment_bill_person.hj_base_p
     *
     * @mbggenerated
     */
    public BigDecimal getHjBaseP() {
        return hjBaseP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_payment_bill_person.hj_base_p
     *
     * @param hjBaseP the value for af_payment_bill_person.hj_base_p
     *
     * @mbggenerated
     */
    public void setHjBaseP(BigDecimal hjBaseP) {
        this.hjBaseP = hjBaseP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_payment_bill_person.hj_amount
     *
     * @return the value of af_payment_bill_person.hj_amount
     *
     * @mbggenerated
     */
    public BigDecimal getHjAmount() {
        return hjAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_payment_bill_person.hj_amount
     *
     * @param hjAmount the value for af_payment_bill_person.hj_amount
     *
     * @mbggenerated
     */
    public void setHjAmount(BigDecimal hjAmount) {
        this.hjAmount = hjAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_payment_bill_person.hj_amount_e
     *
     * @return the value of af_payment_bill_person.hj_amount_e
     *
     * @mbggenerated
     */
    public BigDecimal getHjAmountE() {
        return hjAmountE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_payment_bill_person.hj_amount_e
     *
     * @param hjAmountE the value for af_payment_bill_person.hj_amount_e
     *
     * @mbggenerated
     */
    public void setHjAmountE(BigDecimal hjAmountE) {
        this.hjAmountE = hjAmountE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_payment_bill_person.hj_amount_p
     *
     * @return the value of af_payment_bill_person.hj_amount_p
     *
     * @mbggenerated
     */
    public BigDecimal getHjAmountP() {
        return hjAmountP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_payment_bill_person.hj_amount_p
     *
     * @param hjAmountP the value for af_payment_bill_person.hj_amount_p
     *
     * @mbggenerated
     */
    public void setHjAmountP(BigDecimal hjAmountP) {
        this.hjAmountP = hjAmountP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_payment_bill_person.bj_amount
     *
     * @return the value of af_payment_bill_person.bj_amount
     *
     * @mbggenerated
     */
    public BigDecimal getBjAmount() {
        return bjAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_payment_bill_person.bj_amount
     *
     * @param bjAmount the value for af_payment_bill_person.bj_amount
     *
     * @mbggenerated
     */
    public void setBjAmount(BigDecimal bjAmount) {
        this.bjAmount = bjAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_payment_bill_person.bj_amount_e
     *
     * @return the value of af_payment_bill_person.bj_amount_e
     *
     * @mbggenerated
     */
    public BigDecimal getBjAmountE() {
        return bjAmountE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_payment_bill_person.bj_amount_e
     *
     * @param bjAmountE the value for af_payment_bill_person.bj_amount_e
     *
     * @mbggenerated
     */
    public void setBjAmountE(BigDecimal bjAmountE) {
        this.bjAmountE = bjAmountE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_payment_bill_person.bj_amount_p
     *
     * @return the value of af_payment_bill_person.bj_amount_p
     *
     * @mbggenerated
     */
    public BigDecimal getBjAmountP() {
        return bjAmountP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_payment_bill_person.bj_amount_p
     *
     * @param bjAmountP the value for af_payment_bill_person.bj_amount_p
     *
     * @mbggenerated
     */
    public void setBjAmountP(BigDecimal bjAmountP) {
        this.bjAmountP = bjAmountP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_payment_bill_person.bj_base_e
     *
     * @return the value of af_payment_bill_person.bj_base_e
     *
     * @mbggenerated
     */
    public BigDecimal getBjBaseE() {
        return bjBaseE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_payment_bill_person.bj_base_e
     *
     * @param bjBaseE the value for af_payment_bill_person.bj_base_e
     *
     * @mbggenerated
     */
    public void setBjBaseE(BigDecimal bjBaseE) {
        this.bjBaseE = bjBaseE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_payment_bill_person.bj_base_p
     *
     * @return the value of af_payment_bill_person.bj_base_p
     *
     * @mbggenerated
     */
    public BigDecimal getBjBaseP() {
        return bjBaseP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_payment_bill_person.bj_base_p
     *
     * @param bjBaseP the value for af_payment_bill_person.bj_base_p
     *
     * @mbggenerated
     */
    public void setBjBaseP(BigDecimal bjBaseP) {
        this.bjBaseP = bjBaseP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_payment_bill_person.create_user_id
     *
     * @return the value of af_payment_bill_person.create_user_id
     *
     * @mbggenerated
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_payment_bill_person.create_user_id
     *
     * @param createUserId the value for af_payment_bill_person.create_user_id
     *
     * @mbggenerated
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_payment_bill_person.create_date
     *
     * @return the value of af_payment_bill_person.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_payment_bill_person.create_date
     *
     * @param createDate the value for af_payment_bill_person.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_payment_bill_person.update_user_id
     *
     * @return the value of af_payment_bill_person.update_user_id
     *
     * @mbggenerated
     */
    public Long getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_payment_bill_person.update_user_id
     *
     * @param updateUserId the value for af_payment_bill_person.update_user_id
     *
     * @mbggenerated
     */
    public void setUpdateUserId(Long updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_payment_bill_person.update_date
     *
     * @return the value of af_payment_bill_person.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_payment_bill_person.update_date
     *
     * @param updateDate the value for af_payment_bill_person.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column af_payment_bill_person.is_deleted
     *
     * @return the value of af_payment_bill_person.is_deleted
     *
     * @mbggenerated
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column af_payment_bill_person.is_deleted
     *
     * @param isDeleted the value for af_payment_bill_person.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

	public String getPersonName() {
		return personName;
	}

	public void setPersonName(String personName) {
		this.personName = personName;
	}

	public void addPersonDetail(AfPaymentBillPersonDetail pd){
    	this.personDetailList.add(pd);
    }

	public List<AfPaymentBillPersonDetail> getPersonDetailList() {
		return personDetailList;
	}

	public void setPersonDetailList(List<AfPaymentBillPersonDetail> personDetailList) {
		this.personDetailList = personDetailList;
	}
}