package com.jabava.pojo.weixin;

import java.util.Date;

public class WeiXinNews {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_news.news_id
     *
     * @mbggenerated
     */
    private Long newsId;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_news.company_id
     *
     * @mbggenerated
     */
    private Long companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_news.news_title
     *
     * @mbggenerated
     */
    private String newsTitle;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_news.news_content
     *
     * @mbggenerated
     */
    private String newsContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_news.news_body
     *
     * @mbggenerated
     */
    private String newsBody;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_news.image_url
     *
     * @mbggenerated
     */
    private String imageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_news.is_deleted
     *
     * @mbggenerated
     */
    private Integer isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_news.create_user_id
     *
     * @mbggenerated
     */
    private Long createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_news.created_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_news.update_user_id
     *
     * @mbggenerated
     */
    private Long updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_news.update_date
     *
     * @mbggenerated
     */
    private Date updateDate;
    
 

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_news.news_content
     *
     * @return the value of weixin_news.news_content
     *
     * @mbggenerated
     */
    public String getNewsContent() {
        return newsContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_news.news_content
     *
     * @param newsContent the value for weixin_news.news_content
     *
     * @mbggenerated
     */
    public void setNewsContent(String newsContent) {
        this.newsContent = newsContent == null ? null : newsContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_news.news_body
     *
     * @return the value of weixin_news.news_body
     *
     * @mbggenerated
     */
    public String getNewsBody() {
        return newsBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_news.news_body
     *
     * @param newsBody the value for weixin_news.news_body
     *
     * @mbggenerated
     */
    public void setNewsBody(String newsBody) {
        this.newsBody = newsBody == null ? null : newsBody.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_news.news_id
     *
     * @return the value of weixin_news.news_id
     *
     * @mbggenerated
     */
    public Long getNewsId() {
        return newsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_news.news_id
     *
     * @param newsId the value for weixin_news.news_id
     *
     * @mbggenerated
     */
    public void setNewsId(Long newsId) {
        this.newsId = newsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_news.news_title
     *
     * @return the value of weixin_news.news_title
     *
     * @mbggenerated
     */
    public String getNewsTitle() {
        return newsTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_news.news_title
     *
     * @param newsTitle the value for weixin_news.news_title
     *
     * @mbggenerated
     */
    public void setNewsTitle(String newsTitle) {
        this.newsTitle = newsTitle == null ? null : newsTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_news.image_url
     *
     * @return the value of weixin_news.image_url
     *
     * @mbggenerated
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_news.image_url
     *
     * @param imageUrl the value for weixin_news.image_url
     *
     * @mbggenerated
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl == null ? null : imageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_news.is_deleted
     *
     * @return the value of weixin_news.is_deleted
     *
     * @mbggenerated
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_news.is_deleted
     *
     * @param isDeleted the value for weixin_news.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_news.create_user_id
     *
     * @return the value of weixin_news.create_user_id
     *
     * @mbggenerated
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_news.create_user_id
     *
     * @param createUserId the value for weixin_news.create_user_id
     *
     * @mbggenerated
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_news.created_date
     *
     * @return the value of weixin_news.created_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_news.created_date
     *
     * @param createdDate the value for weixin_news.created_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_news.update_user_id
     *
     * @return the value of weixin_news.update_user_id
     *
     * @mbggenerated
     */
    public Long getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_news.update_user_id
     *
     * @param updateUserId the value for weixin_news.update_user_id
     *
     * @mbggenerated
     */
    public void setUpdateUserId(Long updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_news.update_date
     *
     * @return the value of weixin_news.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_news.update_date
     *
     * @param updateDate the value for weixin_news.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

	public Long getCompanyId() {
		return companyId;
	}

	public void setCompanyId(Long companyId) {
		this.companyId = companyId;
	}
    
}