package com.jabava.dao.policygroup;

import java.util.List;

import com.jabava.pojo.policygroup.PolicyGroup;

public interface PolicyGroupMapper {
	/**
	 * 根据城市和类型获取政策包
	 * <pre>
	 * @author steven.chen
	 * @date 2016年4月14日 下午4:05:40 
	 * </pre>
	 *
	 * @param policyGroup
	 * @return
	 */
	List<PolicyGroup> getPolicyGroupByCityAndType(PolicyGroup policyGroup);
	/**
	 * 根据政策包Id 获取政策包名称,
	 * 会将多个名称拼接成一个字符串
	 * <pre>
	 * @author steven.chen
	 * @date 2016年4月14日 下午8:04:12 
	 * </pre>List<PolicyGroup>
	 *
	 * @param list
	 * @return
	 */
	String getGroupNamePlus(List<Long> list);
	/**
	 * 根据ID列表获取政策包列表
	 * <pre>
	 * @author steven.chen
	 * @date 2016年4月15日 下午2:51:28 
	 * </pre>
	 *
	 * @param list
	 * @return
	 */
	List<PolicyGroup> getGroupListByIdList(List<Long> list);
	/**
	 * 根据政策包名称获取政策包
	 * <pre>
	 * @author steven.chen
	 * @date 2016年4月15日 上午10:58:05 
	 * </pre>
	 *
	 * @param policyGroupName
	 * @return
	 */
	public List<PolicyGroup> getPolicyGroupByName(String policyGroupName);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table policy_group
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table policy_group
     *
     * @mbggenerated
     */
    int insert(PolicyGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table policy_group
     *
     * @mbggenerated
     */
    int insertSelective(PolicyGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table policy_group
     *
     * @mbggenerated
     */
    PolicyGroup selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table policy_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PolicyGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table policy_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PolicyGroup record);
    /**
     * 批量或者更新 政策包 如果 ID存在就更新，否则就新增
     * <pre>
     * @author steven.chen
     * @date 2016年4月14日 下午2:39:55 
     * </pre>
     *
     * @param list
     * @return
     */
    int insertOrUpdateList(List<PolicyGroup> list);
}