package com.jabava.dao.policygroup;

import java.util.List;

import com.jabava.pojo.policygroup.PolicyProdRatio;


public interface PolicyProdRatioMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table policy_prod_ratio
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table policy_prod_ratio
     *
     * @mbggenerated
     */
    int insert(PolicyProdRatio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table policy_prod_ratio
     *
     * @mbggenerated
     */
    int insertSelective(PolicyProdRatio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table policy_prod_ratio
     *
     * @mbggenerated
     */
    PolicyProdRatio selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table policy_prod_ratio
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PolicyProdRatio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table policy_prod_ratio
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PolicyProdRatio record);
    /**
     * 批量新增或者更新 ID 存在就更新否则就更新
     * <pre>
     * @author steven.chen
     * @date 2016年4月20日 下午8:49:32 
     * </pre>
     *
     * @param list
     * @return
     */
    int insertOrUpdateList(List<PolicyProdRatio> list);

}