package com.jabava.pojo.hro;

import java.util.Date;

public class BdSb {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_sb.sb_id
     *
     * @mbggenerated
     */
    private Long sbId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_sb.order_id
     *
     * @mbggenerated
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_sb.policy_group_id
     *
     * @mbggenerated
     */
    private Long policyGroupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_sb.policy_group_type
     *
     * @mbggenerated
     */
    private Integer policyGroupType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_sb.policy_name
     *
     * @mbggenerated
     */
    private String policyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_sb.handle_party_id
     *
     * @mbggenerated
     */
    private Long handlePartyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_sb.org_id
     *
     * @mbggenerated
     */
    private Long orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_sb.employee_id
     *
     * @mbggenerated
     */
    private Long employeeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_sb.company_id
     *
     * @mbggenerated
     */
    private Long companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_sb.handle_month
     *
     * @mbggenerated
     */
    private String handleMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_sb.sb_start_month
     *
     * @mbggenerated
     */
    private String sbStartMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_sb.sb_stop_month
     *
     * @mbggenerated
     */
    private String sbStopMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_sb.apply_status
     *
     * @mbggenerated
     */
    private String applyStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_sb.handle_status
     *
     * @mbggenerated
     */
    private String handleStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_sb.pay_status
     *
     * @mbggenerated
     */
    private String payStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_sb.apply_stop_status
     *
     * @mbggenerated
     */
    private String applyStopStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_sb.add_type
     *
     * @mbggenerated
     */
    private String addType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_sb.stop_type
     *
     * @mbggenerated
     */
    private String stopType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_sb.add_remark
     *
     * @mbggenerated
     */
    private String addRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_sb.handle_reject_remark
     *
     * @mbggenerated
     */
    private String handleRejectRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_sb.stop_reject_remark
     *
     * @mbggenerated
     */
    private String stopRejectRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_sb.update_remark
     *
     * @mbggenerated
     */
    private String updateRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_sb.stop_remark
     *
     * @mbggenerated
     */
    private String stopRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_sb.add_fail_reason
     *
     * @mbggenerated
     */
    private String addFailReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_sb.apply_by
     *
     * @mbggenerated
     */
    private Long applyBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_sb.apply_dt
     *
     * @mbggenerated
     */
    private Date applyDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_sb.handle_by
     *
     * @mbggenerated
     */
    private Long handleBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_sb.handle_dt
     *
     * @mbggenerated
     */
    private Date handleDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_sb.stop_by
     *
     * @mbggenerated
     */
    private Long stopBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_sb.stop_dt
     *
     * @mbggenerated
     */
    private Date stopDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_sb.apply_stop_by
     *
     * @mbggenerated
     */
    private Long applyStopBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_sb.apply_stop_dt
     *
     * @mbggenerated
     */
    private Date applyStopDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_sb.serial_number
     *
     * @mbggenerated
     */
    private Long serialNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_sb.is_deleted
     *
     * @mbggenerated
     */
    private Integer isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_sb.create_by
     *
     * @mbggenerated
     */
    private Long createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_sb.create_dt
     *
     * @mbggenerated
     */
    private Date createDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_sb.update_by
     *
     * @mbggenerated
     */
    private Long updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_sb.update_dt
     *
     * @mbggenerated
     */
    private Date updateDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_sb.mimic_by
     *
     * @mbggenerated
     */
    private Long mimicBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_sb.proxy_by
     *
     * @mbggenerated
     */
    private Long proxyBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_sb.apply_update_status
     *
     * @mbggenerated
     */
    private String applyUpdateStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_sb.update_reject_remark
     *
     * @mbggenerated
     */
    private String updateRejectRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_sb.apply_update_by
     *
     * @mbggenerated
     */
    private Long applyUpdateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_sb.apply_update_dt
     *
     * @mbggenerated
     */
    private Date applyUpdateDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_sb.not_sbgjj
     *
     * @mbggenerated
     */
    private Integer notSbgjj;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_sb.sb_id
     *
     * @return the value of bd_sb.sb_id
     *
     * @mbggenerated
     */
    public Long getSbId() {
        return sbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_sb.sb_id
     *
     * @param sbId the value for bd_sb.sb_id
     *
     * @mbggenerated
     */
    public void setSbId(Long sbId) {
        this.sbId = sbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_sb.order_id
     *
     * @return the value of bd_sb.order_id
     *
     * @mbggenerated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_sb.order_id
     *
     * @param orderId the value for bd_sb.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_sb.policy_group_id
     *
     * @return the value of bd_sb.policy_group_id
     *
     * @mbggenerated
     */
    public Long getPolicyGroupId() {
        return policyGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_sb.policy_group_id
     *
     * @param policyGroupId the value for bd_sb.policy_group_id
     *
     * @mbggenerated
     */
    public void setPolicyGroupId(Long policyGroupId) {
        this.policyGroupId = policyGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_sb.policy_group_type
     *
     * @return the value of bd_sb.policy_group_type
     *
     * @mbggenerated
     */
    public Integer getPolicyGroupType() {
        return policyGroupType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_sb.policy_group_type
     *
     * @param policyGroupType the value for bd_sb.policy_group_type
     *
     * @mbggenerated
     */
    public void setPolicyGroupType(Integer policyGroupType) {
        this.policyGroupType = policyGroupType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_sb.policy_name
     *
     * @return the value of bd_sb.policy_name
     *
     * @mbggenerated
     */
    public String getPolicyName() {
        return policyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_sb.policy_name
     *
     * @param policyName the value for bd_sb.policy_name
     *
     * @mbggenerated
     */
    public void setPolicyName(String policyName) {
        this.policyName = policyName == null ? null : policyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_sb.handle_party_id
     *
     * @return the value of bd_sb.handle_party_id
     *
     * @mbggenerated
     */
    public Long getHandlePartyId() {
        return handlePartyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_sb.handle_party_id
     *
     * @param handlePartyId the value for bd_sb.handle_party_id
     *
     * @mbggenerated
     */
    public void setHandlePartyId(Long handlePartyId) {
        this.handlePartyId = handlePartyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_sb.org_id
     *
     * @return the value of bd_sb.org_id
     *
     * @mbggenerated
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_sb.org_id
     *
     * @param orgId the value for bd_sb.org_id
     *
     * @mbggenerated
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_sb.employee_id
     *
     * @return the value of bd_sb.employee_id
     *
     * @mbggenerated
     */
    public Long getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_sb.employee_id
     *
     * @param employeeId the value for bd_sb.employee_id
     *
     * @mbggenerated
     */
    public void setEmployeeId(Long employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_sb.company_id
     *
     * @return the value of bd_sb.company_id
     *
     * @mbggenerated
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_sb.company_id
     *
     * @param companyId the value for bd_sb.company_id
     *
     * @mbggenerated
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_sb.handle_month
     *
     * @return the value of bd_sb.handle_month
     *
     * @mbggenerated
     */
    public String getHandleMonth() {
        return handleMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_sb.handle_month
     *
     * @param handleMonth the value for bd_sb.handle_month
     *
     * @mbggenerated
     */
    public void setHandleMonth(String handleMonth) {
        this.handleMonth = handleMonth == null ? null : handleMonth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_sb.sb_start_month
     *
     * @return the value of bd_sb.sb_start_month
     *
     * @mbggenerated
     */
    public String getSbStartMonth() {
        return sbStartMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_sb.sb_start_month
     *
     * @param sbStartMonth the value for bd_sb.sb_start_month
     *
     * @mbggenerated
     */
    public void setSbStartMonth(String sbStartMonth) {
        this.sbStartMonth = sbStartMonth == null ? null : sbStartMonth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_sb.sb_stop_month
     *
     * @return the value of bd_sb.sb_stop_month
     *
     * @mbggenerated
     */
    public String getSbStopMonth() {
        return sbStopMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_sb.sb_stop_month
     *
     * @param sbStopMonth the value for bd_sb.sb_stop_month
     *
     * @mbggenerated
     */
    public void setSbStopMonth(String sbStopMonth) {
        this.sbStopMonth = sbStopMonth == null ? null : sbStopMonth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_sb.apply_status
     *
     * @return the value of bd_sb.apply_status
     *
     * @mbggenerated
     */
    public String getApplyStatus() {
        return applyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_sb.apply_status
     *
     * @param applyStatus the value for bd_sb.apply_status
     *
     * @mbggenerated
     */
    public void setApplyStatus(String applyStatus) {
        this.applyStatus = applyStatus == null ? null : applyStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_sb.handle_status
     *
     * @return the value of bd_sb.handle_status
     *
     * @mbggenerated
     */
    public String getHandleStatus() {
        return handleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_sb.handle_status
     *
     * @param handleStatus the value for bd_sb.handle_status
     *
     * @mbggenerated
     */
    public void setHandleStatus(String handleStatus) {
        this.handleStatus = handleStatus == null ? null : handleStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_sb.pay_status
     *
     * @return the value of bd_sb.pay_status
     *
     * @mbggenerated
     */
    public String getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_sb.pay_status
     *
     * @param payStatus the value for bd_sb.pay_status
     *
     * @mbggenerated
     */
    public void setPayStatus(String payStatus) {
        this.payStatus = payStatus == null ? null : payStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_sb.apply_stop_status
     *
     * @return the value of bd_sb.apply_stop_status
     *
     * @mbggenerated
     */
    public String getApplyStopStatus() {
        return applyStopStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_sb.apply_stop_status
     *
     * @param applyStopStatus the value for bd_sb.apply_stop_status
     *
     * @mbggenerated
     */
    public void setApplyStopStatus(String applyStopStatus) {
        this.applyStopStatus = applyStopStatus == null ? null : applyStopStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_sb.add_type
     *
     * @return the value of bd_sb.add_type
     *
     * @mbggenerated
     */
    public String getAddType() {
        return addType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_sb.add_type
     *
     * @param addType the value for bd_sb.add_type
     *
     * @mbggenerated
     */
    public void setAddType(String addType) {
        this.addType = addType == null ? null : addType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_sb.stop_type
     *
     * @return the value of bd_sb.stop_type
     *
     * @mbggenerated
     */
    public String getStopType() {
        return stopType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_sb.stop_type
     *
     * @param stopType the value for bd_sb.stop_type
     *
     * @mbggenerated
     */
    public void setStopType(String stopType) {
        this.stopType = stopType == null ? null : stopType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_sb.add_remark
     *
     * @return the value of bd_sb.add_remark
     *
     * @mbggenerated
     */
    public String getAddRemark() {
        return addRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_sb.add_remark
     *
     * @param addRemark the value for bd_sb.add_remark
     *
     * @mbggenerated
     */
    public void setAddRemark(String addRemark) {
        this.addRemark = addRemark == null ? null : addRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_sb.handle_reject_remark
     *
     * @return the value of bd_sb.handle_reject_remark
     *
     * @mbggenerated
     */
    public String getHandleRejectRemark() {
        return handleRejectRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_sb.handle_reject_remark
     *
     * @param handleRejectRemark the value for bd_sb.handle_reject_remark
     *
     * @mbggenerated
     */
    public void setHandleRejectRemark(String handleRejectRemark) {
        this.handleRejectRemark = handleRejectRemark == null ? null : handleRejectRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_sb.stop_reject_remark
     *
     * @return the value of bd_sb.stop_reject_remark
     *
     * @mbggenerated
     */
    public String getStopRejectRemark() {
        return stopRejectRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_sb.stop_reject_remark
     *
     * @param stopRejectRemark the value for bd_sb.stop_reject_remark
     *
     * @mbggenerated
     */
    public void setStopRejectRemark(String stopRejectRemark) {
        this.stopRejectRemark = stopRejectRemark == null ? null : stopRejectRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_sb.update_remark
     *
     * @return the value of bd_sb.update_remark
     *
     * @mbggenerated
     */
    public String getUpdateRemark() {
        return updateRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_sb.update_remark
     *
     * @param updateRemark the value for bd_sb.update_remark
     *
     * @mbggenerated
     */
    public void setUpdateRemark(String updateRemark) {
        this.updateRemark = updateRemark == null ? null : updateRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_sb.stop_remark
     *
     * @return the value of bd_sb.stop_remark
     *
     * @mbggenerated
     */
    public String getStopRemark() {
        return stopRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_sb.stop_remark
     *
     * @param stopRemark the value for bd_sb.stop_remark
     *
     * @mbggenerated
     */
    public void setStopRemark(String stopRemark) {
        this.stopRemark = stopRemark == null ? null : stopRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_sb.add_fail_reason
     *
     * @return the value of bd_sb.add_fail_reason
     *
     * @mbggenerated
     */
    public String getAddFailReason() {
        return addFailReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_sb.add_fail_reason
     *
     * @param addFailReason the value for bd_sb.add_fail_reason
     *
     * @mbggenerated
     */
    public void setAddFailReason(String addFailReason) {
        this.addFailReason = addFailReason == null ? null : addFailReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_sb.apply_by
     *
     * @return the value of bd_sb.apply_by
     *
     * @mbggenerated
     */
    public Long getApplyBy() {
        return applyBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_sb.apply_by
     *
     * @param applyBy the value for bd_sb.apply_by
     *
     * @mbggenerated
     */
    public void setApplyBy(Long applyBy) {
        this.applyBy = applyBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_sb.apply_dt
     *
     * @return the value of bd_sb.apply_dt
     *
     * @mbggenerated
     */
    public Date getApplyDt() {
        return applyDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_sb.apply_dt
     *
     * @param applyDt the value for bd_sb.apply_dt
     *
     * @mbggenerated
     */
    public void setApplyDt(Date applyDt) {
        this.applyDt = applyDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_sb.handle_by
     *
     * @return the value of bd_sb.handle_by
     *
     * @mbggenerated
     */
    public Long getHandleBy() {
        return handleBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_sb.handle_by
     *
     * @param handleBy the value for bd_sb.handle_by
     *
     * @mbggenerated
     */
    public void setHandleBy(Long handleBy) {
        this.handleBy = handleBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_sb.handle_dt
     *
     * @return the value of bd_sb.handle_dt
     *
     * @mbggenerated
     */
    public Date getHandleDt() {
        return handleDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_sb.handle_dt
     *
     * @param handleDt the value for bd_sb.handle_dt
     *
     * @mbggenerated
     */
    public void setHandleDt(Date handleDt) {
        this.handleDt = handleDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_sb.stop_by
     *
     * @return the value of bd_sb.stop_by
     *
     * @mbggenerated
     */
    public Long getStopBy() {
        return stopBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_sb.stop_by
     *
     * @param stopBy the value for bd_sb.stop_by
     *
     * @mbggenerated
     */
    public void setStopBy(Long stopBy) {
        this.stopBy = stopBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_sb.stop_dt
     *
     * @return the value of bd_sb.stop_dt
     *
     * @mbggenerated
     */
    public Date getStopDt() {
        return stopDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_sb.stop_dt
     *
     * @param stopDt the value for bd_sb.stop_dt
     *
     * @mbggenerated
     */
    public void setStopDt(Date stopDt) {
        this.stopDt = stopDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_sb.apply_stop_by
     *
     * @return the value of bd_sb.apply_stop_by
     *
     * @mbggenerated
     */
    public Long getApplyStopBy() {
        return applyStopBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_sb.apply_stop_by
     *
     * @param applyStopBy the value for bd_sb.apply_stop_by
     *
     * @mbggenerated
     */
    public void setApplyStopBy(Long applyStopBy) {
        this.applyStopBy = applyStopBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_sb.apply_stop_dt
     *
     * @return the value of bd_sb.apply_stop_dt
     *
     * @mbggenerated
     */
    public Date getApplyStopDt() {
        return applyStopDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_sb.apply_stop_dt
     *
     * @param applyStopDt the value for bd_sb.apply_stop_dt
     *
     * @mbggenerated
     */
    public void setApplyStopDt(Date applyStopDt) {
        this.applyStopDt = applyStopDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_sb.serial_number
     *
     * @return the value of bd_sb.serial_number
     *
     * @mbggenerated
     */
    public Long getSerialNumber() {
        return serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_sb.serial_number
     *
     * @param serialNumber the value for bd_sb.serial_number
     *
     * @mbggenerated
     */
    public void setSerialNumber(Long serialNumber) {
        this.serialNumber = serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_sb.is_deleted
     *
     * @return the value of bd_sb.is_deleted
     *
     * @mbggenerated
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_sb.is_deleted
     *
     * @param isDeleted the value for bd_sb.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_sb.create_by
     *
     * @return the value of bd_sb.create_by
     *
     * @mbggenerated
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_sb.create_by
     *
     * @param createBy the value for bd_sb.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_sb.create_dt
     *
     * @return the value of bd_sb.create_dt
     *
     * @mbggenerated
     */
    public Date getCreateDt() {
        return createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_sb.create_dt
     *
     * @param createDt the value for bd_sb.create_dt
     *
     * @mbggenerated
     */
    public void setCreateDt(Date createDt) {
        this.createDt = createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_sb.update_by
     *
     * @return the value of bd_sb.update_by
     *
     * @mbggenerated
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_sb.update_by
     *
     * @param updateBy the value for bd_sb.update_by
     *
     * @mbggenerated
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_sb.update_dt
     *
     * @return the value of bd_sb.update_dt
     *
     * @mbggenerated
     */
    public Date getUpdateDt() {
        return updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_sb.update_dt
     *
     * @param updateDt the value for bd_sb.update_dt
     *
     * @mbggenerated
     */
    public void setUpdateDt(Date updateDt) {
        this.updateDt = updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_sb.mimic_by
     *
     * @return the value of bd_sb.mimic_by
     *
     * @mbggenerated
     */
    public Long getMimicBy() {
        return mimicBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_sb.mimic_by
     *
     * @param mimicBy the value for bd_sb.mimic_by
     *
     * @mbggenerated
     */
    public void setMimicBy(Long mimicBy) {
        this.mimicBy = mimicBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_sb.proxy_by
     *
     * @return the value of bd_sb.proxy_by
     *
     * @mbggenerated
     */
    public Long getProxyBy() {
        return proxyBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_sb.proxy_by
     *
     * @param proxyBy the value for bd_sb.proxy_by
     *
     * @mbggenerated
     */
    public void setProxyBy(Long proxyBy) {
        this.proxyBy = proxyBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_sb.apply_update_status
     *
     * @return the value of bd_sb.apply_update_status
     *
     * @mbggenerated
     */
    public String getApplyUpdateStatus() {
        return applyUpdateStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_sb.apply_update_status
     *
     * @param applyUpdateStatus the value for bd_sb.apply_update_status
     *
     * @mbggenerated
     */
    public void setApplyUpdateStatus(String applyUpdateStatus) {
        this.applyUpdateStatus = applyUpdateStatus == null ? null : applyUpdateStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_sb.update_reject_remark
     *
     * @return the value of bd_sb.update_reject_remark
     *
     * @mbggenerated
     */
    public String getUpdateRejectRemark() {
        return updateRejectRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_sb.update_reject_remark
     *
     * @param updateRejectRemark the value for bd_sb.update_reject_remark
     *
     * @mbggenerated
     */
    public void setUpdateRejectRemark(String updateRejectRemark) {
        this.updateRejectRemark = updateRejectRemark == null ? null : updateRejectRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_sb.apply_update_by
     *
     * @return the value of bd_sb.apply_update_by
     *
     * @mbggenerated
     */
    public Long getApplyUpdateBy() {
        return applyUpdateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_sb.apply_update_by
     *
     * @param applyUpdateBy the value for bd_sb.apply_update_by
     *
     * @mbggenerated
     */
    public void setApplyUpdateBy(Long applyUpdateBy) {
        this.applyUpdateBy = applyUpdateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_sb.apply_update_dt
     *
     * @return the value of bd_sb.apply_update_dt
     *
     * @mbggenerated
     */
    public Date getApplyUpdateDt() {
        return applyUpdateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_sb.apply_update_dt
     *
     * @param applyUpdateDt the value for bd_sb.apply_update_dt
     *
     * @mbggenerated
     */
    public void setApplyUpdateDt(Date applyUpdateDt) {
        this.applyUpdateDt = applyUpdateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_sb.not_sbgjj
     *
     * @return the value of bd_sb.not_sbgjj
     *
     * @mbggenerated
     */
    public Integer getNotSbgjj() {
        return notSbgjj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_sb.not_sbgjj
     *
     * @param notSbgjj the value for bd_sb.not_sbgjj
     *
     * @mbggenerated
     */
    public void setNotSbgjj(Integer notSbgjj) {
        this.notSbgjj = notSbgjj;
    }
}