package com.jabava.pojo.hro;

import java.math.BigDecimal;
import java.util.Date;

public class EfArapDetailEmpSb  {
	private Long billDetailId;

    private String billYm;
	
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ef_arap_detail_emp_sb.bill_id
     *
     * @mbggenerated
     */
    private Long billId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ef_arap_detail_emp_sb.bill_template_id
     *
     * @mbggenerated
     */
    private Long billTemplateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ef_arap_detail_emp_sb.emp_id
     *
     * @mbggenerated
     */
    private Long empId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ef_arap_detail_emp_sb.client_id
     *
     * @mbggenerated
     */
    private Long clientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ef_arap_detail_emp_sb.previous_send_id
     *
     * @mbggenerated
     */
    private Long previousSendId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ef_arap_detail_emp_sb.city_id
     *
     * @mbggenerated
     */
    private Long cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ef_arap_detail_emp_sb.sb_ym
     *
     * @mbggenerated
     */
    private String sbYm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ef_arap_detail_emp_sb.server_ym
     *
     * @mbggenerated
     */
    private String serverYm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ef_arap_detail_emp_sb.policy_group_id
     *
     * @mbggenerated
     */
    private Long policyGroupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ef_arap_detail_emp_sb.prod_id
     *
     * @mbggenerated
     */
    private Long prodId;
    
    private String prodName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ef_arap_detail_emp_sb.is_sum
     *
     * @mbggenerated
     */
    private Integer isSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ef_arap_detail_emp_sb.is_one_off
     *
     * @mbggenerated
     */
    private Integer isOneOff;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ef_arap_detail_emp_sb.amount
     *
     * @mbggenerated
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ef_arap_detail_emp_sb.amount_e
     *
     * @mbggenerated
     */
    private BigDecimal amountE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ef_arap_detail_emp_sb.amount_p
     *
     * @mbggenerated
     */
    private BigDecimal amountP;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ef_arap_detail_emp_sb.base_e
     *
     * @mbggenerated
     */
    private BigDecimal baseE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ef_arap_detail_emp_sb.base_p
     *
     * @mbggenerated
     */
    private BigDecimal baseP;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ef_arap_detail_emp_sb.ratio_e
     *
     * @mbggenerated
     */
    private BigDecimal ratioE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ef_arap_detail_emp_sb.ratio_p
     *
     * @mbggenerated
     */
    private BigDecimal ratioP;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ef_arap_detail_emp_sb.add_amt_e
     *
     * @mbggenerated
     */
    private BigDecimal addAmtE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ef_arap_detail_emp_sb.add_amt_p
     *
     * @mbggenerated
     */
    private BigDecimal addAmtP;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ef_arap_detail_emp_sb.contract_id
     *
     * @mbggenerated
     */
    private Long contractId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ef_arap_detail_emp_sb.contract_type
     *
     * @mbggenerated
     */
    private String contractType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ef_arap_detail_emp_sb.second_contract_id
     *
     * @mbggenerated
     */
    private Long secondContractId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ef_arap_detail_emp_sb.red_flag
     *
     * @mbggenerated
     */
    private Integer redFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ef_arap_detail_emp_sb.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ef_arap_detail_emp_sb.is_deleted
     *
     * @mbggenerated
     */
    private Integer isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ef_arap_detail_emp_sb.create_user_id
     *
     * @mbggenerated
     */
    private Long createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ef_arap_detail_emp_sb.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ef_arap_detail_emp_sb.update_user_id
     *
     * @mbggenerated
     */
    private Long updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ef_arap_detail_emp_sb.update_date
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ef_arap_detail_emp_sb.order_id
     *
     * @mbggenerated
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ef_arap_detail_emp_sb.employee_rec_id
     *
     * @mbggenerated
     */
    private Long employeeRecId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ef_arap_detail_emp_sb.city_name
     *
     * @mbggenerated
     */
    private String cityName;
    
    private String certId;
    private Integer certType;
    
    //关联字段
    private Long personId;
    private String employeeName;
    private String jobNumber;
    private String workLocation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ef_arap_detail_emp_sb.bill_id
     *
     * @return the value of ef_arap_detail_emp_sb.bill_id
     *
     * @mbggenerated
     */
    public Long getBillId() {
        return billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ef_arap_detail_emp_sb.bill_id
     *
     * @param billId the value for ef_arap_detail_emp_sb.bill_id
     *
     * @mbggenerated
     */
    public void setBillId(Long billId) {
        this.billId = billId;
    }

    public String getBillYm() {
		return billYm;
	}

	public void setBillYm(String billYm) {
		this.billYm = billYm;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ef_arap_detail_emp_sb.bill_template_id
     *
     * @return the value of ef_arap_detail_emp_sb.bill_template_id
     *
     * @mbggenerated
     */
    public Long getBillTemplateId() {
        return billTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ef_arap_detail_emp_sb.bill_template_id
     *
     * @param billTemplateId the value for ef_arap_detail_emp_sb.bill_template_id
     *
     * @mbggenerated
     */
    public void setBillTemplateId(Long billTemplateId) {
        this.billTemplateId = billTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ef_arap_detail_emp_sb.emp_id
     *
     * @return the value of ef_arap_detail_emp_sb.emp_id
     *
     * @mbggenerated
     */
    public Long getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ef_arap_detail_emp_sb.emp_id
     *
     * @param empId the value for ef_arap_detail_emp_sb.emp_id
     *
     * @mbggenerated
     */
    public void setEmpId(Long empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ef_arap_detail_emp_sb.client_id
     *
     * @return the value of ef_arap_detail_emp_sb.client_id
     *
     * @mbggenerated
     */
    public Long getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ef_arap_detail_emp_sb.client_id
     *
     * @param clientId the value for ef_arap_detail_emp_sb.client_id
     *
     * @mbggenerated
     */
    public void setClientId(Long clientId) {
        this.clientId = clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ef_arap_detail_emp_sb.previous_send_id
     *
     * @return the value of ef_arap_detail_emp_sb.previous_send_id
     *
     * @mbggenerated
     */
    public Long getPreviousSendId() {
        return previousSendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ef_arap_detail_emp_sb.previous_send_id
     *
     * @param previousSendId the value for ef_arap_detail_emp_sb.previous_send_id
     *
     * @mbggenerated
     */
    public void setPreviousSendId(Long previousSendId) {
        this.previousSendId = previousSendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ef_arap_detail_emp_sb.city_id
     *
     * @return the value of ef_arap_detail_emp_sb.city_id
     *
     * @mbggenerated
     */
    public Long getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ef_arap_detail_emp_sb.city_id
     *
     * @param cityId the value for ef_arap_detail_emp_sb.city_id
     *
     * @mbggenerated
     */
    public void setCityId(Long cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ef_arap_detail_emp_sb.sb_ym
     *
     * @return the value of ef_arap_detail_emp_sb.sb_ym
     *
     * @mbggenerated
     */
    public String getSbYm() {
        return sbYm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ef_arap_detail_emp_sb.sb_ym
     *
     * @param sbYm the value for ef_arap_detail_emp_sb.sb_ym
     *
     * @mbggenerated
     */
    public void setSbYm(String sbYm) {
        this.sbYm = sbYm == null ? null : sbYm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ef_arap_detail_emp_sb.server_ym
     *
     * @return the value of ef_arap_detail_emp_sb.server_ym
     *
     * @mbggenerated
     */
    public String getServerYm() {
        return serverYm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ef_arap_detail_emp_sb.server_ym
     *
     * @param serverYm the value for ef_arap_detail_emp_sb.server_ym
     *
     * @mbggenerated
     */
    public void setServerYm(String serverYm) {
        this.serverYm = serverYm == null ? null : serverYm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ef_arap_detail_emp_sb.policy_group_id
     *
     * @return the value of ef_arap_detail_emp_sb.policy_group_id
     *
     * @mbggenerated
     */
    public Long getPolicyGroupId() {
        return policyGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ef_arap_detail_emp_sb.policy_group_id
     *
     * @param policyGroupId the value for ef_arap_detail_emp_sb.policy_group_id
     *
     * @mbggenerated
     */
    public void setPolicyGroupId(Long policyGroupId) {
        this.policyGroupId = policyGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ef_arap_detail_emp_sb.prod_id
     *
     * @return the value of ef_arap_detail_emp_sb.prod_id
     *
     * @mbggenerated
     */
    public Long getProdId() {
        return prodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ef_arap_detail_emp_sb.prod_id
     *
     * @param prodId the value for ef_arap_detail_emp_sb.prod_id
     *
     * @mbggenerated
     */
    public void setProdId(Long prodId) {
        this.prodId = prodId;
    }

    public String getProdName() {
		return prodName;
	}

	public void setProdName(String prodName) {
		this.prodName = prodName;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ef_arap_detail_emp_sb.is_sum
     *
     * @return the value of ef_arap_detail_emp_sb.is_sum
     *
     * @mbggenerated
     */
    public Integer getIsSum() {
        return isSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ef_arap_detail_emp_sb.is_sum
     *
     * @param isSum the value for ef_arap_detail_emp_sb.is_sum
     *
     * @mbggenerated
     */
    public void setIsSum(Integer isSum) {
        this.isSum = isSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ef_arap_detail_emp_sb.is_one_off
     *
     * @return the value of ef_arap_detail_emp_sb.is_one_off
     *
     * @mbggenerated
     */
    public Integer getIsOneOff() {
        return isOneOff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ef_arap_detail_emp_sb.is_one_off
     *
     * @param isOneOff the value for ef_arap_detail_emp_sb.is_one_off
     *
     * @mbggenerated
     */
    public void setIsOneOff(Integer isOneOff) {
        this.isOneOff = isOneOff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ef_arap_detail_emp_sb.amount
     *
     * @return the value of ef_arap_detail_emp_sb.amount
     *
     * @mbggenerated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ef_arap_detail_emp_sb.amount
     *
     * @param amount the value for ef_arap_detail_emp_sb.amount
     *
     * @mbggenerated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ef_arap_detail_emp_sb.amount_e
     *
     * @return the value of ef_arap_detail_emp_sb.amount_e
     *
     * @mbggenerated
     */
    public BigDecimal getAmountE() {
        return amountE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ef_arap_detail_emp_sb.amount_e
     *
     * @param amountE the value for ef_arap_detail_emp_sb.amount_e
     *
     * @mbggenerated
     */
    public void setAmountE(BigDecimal amountE) {
        this.amountE = amountE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ef_arap_detail_emp_sb.amount_p
     *
     * @return the value of ef_arap_detail_emp_sb.amount_p
     *
     * @mbggenerated
     */
    public BigDecimal getAmountP() {
        return amountP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ef_arap_detail_emp_sb.amount_p
     *
     * @param amountP the value for ef_arap_detail_emp_sb.amount_p
     *
     * @mbggenerated
     */
    public void setAmountP(BigDecimal amountP) {
        this.amountP = amountP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ef_arap_detail_emp_sb.base_e
     *
     * @return the value of ef_arap_detail_emp_sb.base_e
     *
     * @mbggenerated
     */
    public BigDecimal getBaseE() {
        return baseE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ef_arap_detail_emp_sb.base_e
     *
     * @param baseE the value for ef_arap_detail_emp_sb.base_e
     *
     * @mbggenerated
     */
    public void setBaseE(BigDecimal baseE) {
        this.baseE = baseE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ef_arap_detail_emp_sb.base_p
     *
     * @return the value of ef_arap_detail_emp_sb.base_p
     *
     * @mbggenerated
     */
    public BigDecimal getBaseP() {
        return baseP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ef_arap_detail_emp_sb.base_p
     *
     * @param baseP the value for ef_arap_detail_emp_sb.base_p
     *
     * @mbggenerated
     */
    public void setBaseP(BigDecimal baseP) {
        this.baseP = baseP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ef_arap_detail_emp_sb.ratio_e
     *
     * @return the value of ef_arap_detail_emp_sb.ratio_e
     *
     * @mbggenerated
     */
    public BigDecimal getRatioE() {
        return ratioE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ef_arap_detail_emp_sb.ratio_e
     *
     * @param ratioE the value for ef_arap_detail_emp_sb.ratio_e
     *
     * @mbggenerated
     */
    public void setRatioE(BigDecimal ratioE) {
        this.ratioE = ratioE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ef_arap_detail_emp_sb.ratio_p
     *
     * @return the value of ef_arap_detail_emp_sb.ratio_p
     *
     * @mbggenerated
     */
    public BigDecimal getRatioP() {
        return ratioP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ef_arap_detail_emp_sb.ratio_p
     *
     * @param ratioP the value for ef_arap_detail_emp_sb.ratio_p
     *
     * @mbggenerated
     */
    public void setRatioP(BigDecimal ratioP) {
        this.ratioP = ratioP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ef_arap_detail_emp_sb.add_amt_e
     *
     * @return the value of ef_arap_detail_emp_sb.add_amt_e
     *
     * @mbggenerated
     */
    public BigDecimal getAddAmtE() {
        return addAmtE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ef_arap_detail_emp_sb.add_amt_e
     *
     * @param addAmtE the value for ef_arap_detail_emp_sb.add_amt_e
     *
     * @mbggenerated
     */
    public void setAddAmtE(BigDecimal addAmtE) {
        this.addAmtE = addAmtE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ef_arap_detail_emp_sb.add_amt_p
     *
     * @return the value of ef_arap_detail_emp_sb.add_amt_p
     *
     * @mbggenerated
     */
    public BigDecimal getAddAmtP() {
        return addAmtP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ef_arap_detail_emp_sb.add_amt_p
     *
     * @param addAmtP the value for ef_arap_detail_emp_sb.add_amt_p
     *
     * @mbggenerated
     */
    public void setAddAmtP(BigDecimal addAmtP) {
        this.addAmtP = addAmtP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ef_arap_detail_emp_sb.contract_id
     *
     * @return the value of ef_arap_detail_emp_sb.contract_id
     *
     * @mbggenerated
     */
    public Long getContractId() {
        return contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ef_arap_detail_emp_sb.contract_id
     *
     * @param contractId the value for ef_arap_detail_emp_sb.contract_id
     *
     * @mbggenerated
     */
    public void setContractId(Long contractId) {
        this.contractId = contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ef_arap_detail_emp_sb.contract_type
     *
     * @return the value of ef_arap_detail_emp_sb.contract_type
     *
     * @mbggenerated
     */
    public String getContractType() {
        return contractType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ef_arap_detail_emp_sb.contract_type
     *
     * @param contractType the value for ef_arap_detail_emp_sb.contract_type
     *
     * @mbggenerated
     */
    public void setContractType(String contractType) {
        this.contractType = contractType == null ? null : contractType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ef_arap_detail_emp_sb.second_contract_id
     *
     * @return the value of ef_arap_detail_emp_sb.second_contract_id
     *
     * @mbggenerated
     */
    public Long getSecondContractId() {
        return secondContractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ef_arap_detail_emp_sb.second_contract_id
     *
     * @param secondContractId the value for ef_arap_detail_emp_sb.second_contract_id
     *
     * @mbggenerated
     */
    public void setSecondContractId(Long secondContractId) {
        this.secondContractId = secondContractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ef_arap_detail_emp_sb.red_flag
     *
     * @return the value of ef_arap_detail_emp_sb.red_flag
     *
     * @mbggenerated
     */
    public Integer getRedFlag() {
        return redFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ef_arap_detail_emp_sb.red_flag
     *
     * @param redFlag the value for ef_arap_detail_emp_sb.red_flag
     *
     * @mbggenerated
     */
    public void setRedFlag(Integer redFlag) {
        this.redFlag = redFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ef_arap_detail_emp_sb.remark
     *
     * @return the value of ef_arap_detail_emp_sb.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ef_arap_detail_emp_sb.remark
     *
     * @param remark the value for ef_arap_detail_emp_sb.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ef_arap_detail_emp_sb.is_deleted
     *
     * @return the value of ef_arap_detail_emp_sb.is_deleted
     *
     * @mbggenerated
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ef_arap_detail_emp_sb.is_deleted
     *
     * @param isDeleted the value for ef_arap_detail_emp_sb.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ef_arap_detail_emp_sb.create_user_id
     *
     * @return the value of ef_arap_detail_emp_sb.create_user_id
     *
     * @mbggenerated
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ef_arap_detail_emp_sb.create_user_id
     *
     * @param createUserId the value for ef_arap_detail_emp_sb.create_user_id
     *
     * @mbggenerated
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ef_arap_detail_emp_sb.create_date
     *
     * @return the value of ef_arap_detail_emp_sb.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ef_arap_detail_emp_sb.create_date
     *
     * @param createDate the value for ef_arap_detail_emp_sb.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ef_arap_detail_emp_sb.update_user_id
     *
     * @return the value of ef_arap_detail_emp_sb.update_user_id
     *
     * @mbggenerated
     */
    public Long getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ef_arap_detail_emp_sb.update_user_id
     *
     * @param updateUserId the value for ef_arap_detail_emp_sb.update_user_id
     *
     * @mbggenerated
     */
    public void setUpdateUserId(Long updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ef_arap_detail_emp_sb.update_date
     *
     * @return the value of ef_arap_detail_emp_sb.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ef_arap_detail_emp_sb.update_date
     *
     * @param updateDate the value for ef_arap_detail_emp_sb.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ef_arap_detail_emp_sb.order_id
     *
     * @return the value of ef_arap_detail_emp_sb.order_id
     *
     * @mbggenerated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ef_arap_detail_emp_sb.order_id
     *
     * @param orderId the value for ef_arap_detail_emp_sb.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ef_arap_detail_emp_sb.employee_rec_id
     *
     * @return the value of ef_arap_detail_emp_sb.employee_rec_id
     *
     * @mbggenerated
     */
    public Long getEmployeeRecId() {
        return employeeRecId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ef_arap_detail_emp_sb.employee_rec_id
     *
     * @param employeeRecId the value for ef_arap_detail_emp_sb.employee_rec_id
     *
     * @mbggenerated
     */
    public void setEmployeeRecId(Long employeeRecId) {
        this.employeeRecId = employeeRecId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ef_arap_detail_emp_sb.city_name
     *
     * @return the value of ef_arap_detail_emp_sb.city_name
     *
     * @mbggenerated
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ef_arap_detail_emp_sb.city_name
     *
     * @param cityName the value for ef_arap_detail_emp_sb.city_name
     *
     * @mbggenerated
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

	public Long getBillDetailId() {
		return billDetailId;
	}

	public void setBillDetailId(Long billDetailId) {
		this.billDetailId = billDetailId;
	}

	public String getCertId() {
		return certId;
	}

	public void setCertId(String certId) {
		this.certId = certId;
	}

	public Integer getCertType() {
		return certType;
	}

	public void setCertType(Integer certType) {
		this.certType = certType;
	}

	public Long getPersonId() {
		return personId;
	}

	public void setPersonId(Long personId) {
		this.personId = personId;
	}

	public String getEmployeeName() {
		return employeeName;
	}

	public void setEmployeeName(String employeeName) {
		this.employeeName = employeeName;
	}

	public String getJobNumber() {
		return jobNumber;
	}

	public void setJobNumber(String jobNumber) {
		this.jobNumber = jobNumber;
	}

	public String getWorkLocation() {
		return workLocation;
	}

	public void setWorkLocation(String workLocation) {
		this.workLocation = workLocation;
	}
	
}