package com.jabava.pojo.hro;

import java.math.BigDecimal;
import java.util.Date;

/**
 * 增减变详情
 *
 * @version $Id: HroSendDetail.java, 
 * v 0.1 2016年1月15日 上午10:56:36 
 * <pre>
 * @author steven.chen
 * @date 2016年1月15日 上午10:56:36 
 * </pre>
 */
public class HroSendDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hro_send_detail.hro_send_detail_id
     *
     * @mbggenerated
     */
    private Long hroSendDetailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hro_send_detail.hro_order_send_id
     *
     * @mbggenerated
     */
    private Long hroOrderSendId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hro_send_detail.company_id
     *
     * @mbggenerated
     */
    private Long companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hro_send_detail.protocol_code
     *
     * @mbggenerated
     */
    private String protocolCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hro_send_detail.employee_name
     *
     * @mbggenerated
     */
    private String employeeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hro_send_detail.batch_code
     *
     * @mbggenerated
     */
    private String batchCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hro_send_detail.card_type
     *
     * @mbggenerated
     */
    private Integer cardType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hro_send_detail.card_id
     *
     * @mbggenerated
     */
    private String cardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hro_send_detail.hire_date
     *
     * @mbggenerated
     */
    private Date hireDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hro_send_detail.hire_remark
     *
     * @mbggenerated
     */
    private String hireRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hro_send_detail.mobile
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hro_send_detail.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hro_send_detail.sb_base
     *
     * @mbggenerated
     */
    private BigDecimal sbBase;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hro_send_detail.gjj_base
     *
     * @mbggenerated
     */
    private BigDecimal gjjBase;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hro_send_detail.gjj_company_ratio
     *
     * @mbggenerated
     */
    private BigDecimal gjjCompanyRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hro_send_detail.gjj_individual_ratio
     *
     * @mbggenerated
     */
    private BigDecimal gjjIndividualRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hro_send_detail.gjj_account
     *
     * @mbggenerated
     */
    private String gjjAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hro_send_detail.sb_group_name
     *
     * @mbggenerated
     */
    private String sbGroupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hro_send_detail.payment_month
     *
     * @mbggenerated
     */
    private String paymentMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hro_send_detail.bill_month
     *
     * @mbggenerated
     */
    private String billMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hro_send_detail.sb_month
     *
     * @mbggenerated
     */
    private String sbMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hro_send_detail.dimission_type
     *
     * @mbggenerated
     */
    private String dimissionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hro_send_detail.dimission_date
     *
     * @mbggenerated
     */
    private Date dimissionDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hro_send_detail.dimission_remark
     *
     * @mbggenerated
     */
    private String dimissionRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hro_send_detail.handle_type
     *
     * @mbggenerated
     */
    private Integer handleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hro_send_detail.operate_type
     *
     * @mbggenerated
     */
    private Integer operateType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hro_send_detail.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hro_send_detail.hro_system_id
     *
     * @mbggenerated
     */
    private Long hroSystemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hro_send_detail.is_deleted
     *
     * @mbggenerated
     */
    private Integer isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hro_send_detail.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hro_send_detail.create_user_id
     *
     * @mbggenerated
     */
    private Long createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hro_send_detail.update_date
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hro_send_detail.update_user_id
     *
     * @mbggenerated
     */
    private Long updateUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hro_send_detail.hro_send_detail_id
     *
     * @return the value of hro_send_detail.hro_send_detail_id
     *
     * @mbggenerated
     */
    public Long getHroSendDetailId() {
        return hroSendDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hro_send_detail.hro_send_detail_id
     *
     * @param hroSendDetailId the value for hro_send_detail.hro_send_detail_id
     *
     * @mbggenerated
     */
    public void setHroSendDetailId(Long hroSendDetailId) {
        this.hroSendDetailId = hroSendDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hro_send_detail.hro_order_send_id
     *
     * @return the value of hro_send_detail.hro_order_send_id
     *
     * @mbggenerated
     */
    public Long getHroOrderSendId() {
        return hroOrderSendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hro_send_detail.hro_order_send_id
     *
     * @param hroOrderSendId the value for hro_send_detail.hro_order_send_id
     *
     * @mbggenerated
     */
    public void setHroOrderSendId(Long hroOrderSendId) {
        this.hroOrderSendId = hroOrderSendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hro_send_detail.company_id
     *
     * @return the value of hro_send_detail.company_id
     *
     * @mbggenerated
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hro_send_detail.company_id
     *
     * @param companyId the value for hro_send_detail.company_id
     *
     * @mbggenerated
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hro_send_detail.protocol_code
     *
     * @return the value of hro_send_detail.protocol_code
     *
     * @mbggenerated
     */
    public String getProtocolCode() {
        return protocolCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hro_send_detail.protocol_code
     *
     * @param protocolCode the value for hro_send_detail.protocol_code
     *
     * @mbggenerated
     */
    public void setProtocolCode(String protocolCode) {
        this.protocolCode = protocolCode == null ? null : protocolCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hro_send_detail.employee_name
     *
     * @return the value of hro_send_detail.employee_name
     *
     * @mbggenerated
     */
    public String getEmployeeName() {
        return employeeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hro_send_detail.employee_name
     *
     * @param employeeName the value for hro_send_detail.employee_name
     *
     * @mbggenerated
     */
    public void setEmployeeName(String employeeName) {
        this.employeeName = employeeName == null ? null : employeeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hro_send_detail.batch_code
     *
     * @return the value of hro_send_detail.batch_code
     *
     * @mbggenerated
     */
    public String getBatchCode() {
        return batchCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hro_send_detail.batch_code
     *
     * @param batchCode the value for hro_send_detail.batch_code
     *
     * @mbggenerated
     */
    public void setBatchCode(String batchCode) {
        this.batchCode = batchCode == null ? null : batchCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hro_send_detail.card_type
     *
     * @return the value of hro_send_detail.card_type
     *
     * @mbggenerated
     */
    public Integer getCardType() {
        return cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hro_send_detail.card_type
     *
     * @param cardType the value for hro_send_detail.card_type
     *
     * @mbggenerated
     */
    public void setCardType(Integer cardType) {
        this.cardType = cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hro_send_detail.card_id
     *
     * @return the value of hro_send_detail.card_id
     *
     * @mbggenerated
     */
    public String getCardId() {
        return cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hro_send_detail.card_id
     *
     * @param cardId the value for hro_send_detail.card_id
     *
     * @mbggenerated
     */
    public void setCardId(String cardId) {
        this.cardId = cardId == null ? null : cardId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hro_send_detail.hire_date
     *
     * @return the value of hro_send_detail.hire_date
     *
     * @mbggenerated
     */
    public Date getHireDate() {
        return hireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hro_send_detail.hire_date
     *
     * @param hireDate the value for hro_send_detail.hire_date
     *
     * @mbggenerated
     */
    public void setHireDate(Date hireDate) {
        this.hireDate = hireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hro_send_detail.hire_remark
     *
     * @return the value of hro_send_detail.hire_remark
     *
     * @mbggenerated
     */
    public String getHireRemark() {
        return hireRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hro_send_detail.hire_remark
     *
     * @param hireRemark the value for hro_send_detail.hire_remark
     *
     * @mbggenerated
     */
    public void setHireRemark(String hireRemark) {
        this.hireRemark = hireRemark == null ? null : hireRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hro_send_detail.mobile
     *
     * @return the value of hro_send_detail.mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hro_send_detail.mobile
     *
     * @param mobile the value for hro_send_detail.mobile
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hro_send_detail.phone
     *
     * @return the value of hro_send_detail.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hro_send_detail.phone
     *
     * @param phone the value for hro_send_detail.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

   
    public BigDecimal getSbBase() {
		return sbBase;
	}

	public void setSbBase(BigDecimal sbBase) {
		this.sbBase = sbBase;
	}

	public BigDecimal getGjjBase() {
		return gjjBase;
	}

	public void setGjjBase(BigDecimal gjjBase) {
		this.gjjBase = gjjBase;
	}

	public BigDecimal getGjjCompanyRatio() {
		return gjjCompanyRatio;
	}

	public void setGjjCompanyRatio(BigDecimal gjjCompanyRatio) {
		this.gjjCompanyRatio = gjjCompanyRatio;
	}

	public BigDecimal getGjjIndividualRatio() {
		return gjjIndividualRatio;
	}

	public void setGjjIndividualRatio(BigDecimal gjjIndividualRatio) {
		this.gjjIndividualRatio = gjjIndividualRatio;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hro_send_detail.gjj_account
     *
     * @return the value of hro_send_detail.gjj_account
     *
     * @mbggenerated
     */
    public String getGjjAccount() {
        return gjjAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hro_send_detail.gjj_account
     *
     * @param gjjAccount the value for hro_send_detail.gjj_account
     *
     * @mbggenerated
     */
    public void setGjjAccount(String gjjAccount) {
        this.gjjAccount = gjjAccount == null ? null : gjjAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hro_send_detail.sb_group_name
     *
     * @return the value of hro_send_detail.sb_group_name
     *
     * @mbggenerated
     */
    public String getSbGroupName() {
        return sbGroupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hro_send_detail.sb_group_name
     *
     * @param sbGroupName the value for hro_send_detail.sb_group_name
     *
     * @mbggenerated
     */
    public void setSbGroupName(String sbGroupName) {
        this.sbGroupName = sbGroupName == null ? null : sbGroupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hro_send_detail.payment_month
     *
     * @return the value of hro_send_detail.payment_month
     *
     * @mbggenerated
     */
    public String getPaymentMonth() {
        return paymentMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hro_send_detail.payment_month
     *
     * @param paymentMonth the value for hro_send_detail.payment_month
     *
     * @mbggenerated
     */
    public void setPaymentMonth(String paymentMonth) {
        this.paymentMonth = paymentMonth == null ? null : paymentMonth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hro_send_detail.bill_month
     *
     * @return the value of hro_send_detail.bill_month
     *
     * @mbggenerated
     */
    public String getBillMonth() {
        return billMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hro_send_detail.bill_month
     *
     * @param billMonth the value for hro_send_detail.bill_month
     *
     * @mbggenerated
     */
    public void setBillMonth(String billMonth) {
        this.billMonth = billMonth == null ? null : billMonth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hro_send_detail.sb_month
     *
     * @return the value of hro_send_detail.sb_month
     *
     * @mbggenerated
     */
    public String getSbMonth() {
        return sbMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hro_send_detail.sb_month
     *
     * @param sbMonth the value for hro_send_detail.sb_month
     *
     * @mbggenerated
     */
    public void setSbMonth(String sbMonth) {
        this.sbMonth = sbMonth == null ? null : sbMonth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hro_send_detail.dimission_type
     *
     * @return the value of hro_send_detail.dimission_type
     *
     * @mbggenerated
     */
    public String getDimissionType() {
        return dimissionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hro_send_detail.dimission_type
     *
     * @param dimissionType the value for hro_send_detail.dimission_type
     *
     * @mbggenerated
     */
    public void setDimissionType(String dimissionType) {
        this.dimissionType = dimissionType == null ? null : dimissionType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hro_send_detail.dimission_date
     *
     * @return the value of hro_send_detail.dimission_date
     *
     * @mbggenerated
     */
    public Date getDimissionDate() {
        return dimissionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hro_send_detail.dimission_date
     *
     * @param dimissionDate the value for hro_send_detail.dimission_date
     *
     * @mbggenerated
     */
    public void setDimissionDate(Date dimissionDate) {
        this.dimissionDate = dimissionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hro_send_detail.dimission_remark
     *
     * @return the value of hro_send_detail.dimission_remark
     *
     * @mbggenerated
     */
    public String getDimissionRemark() {
        return dimissionRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hro_send_detail.dimission_remark
     *
     * @param dimissionRemark the value for hro_send_detail.dimission_remark
     *
     * @mbggenerated
     */
    public void setDimissionRemark(String dimissionRemark) {
        this.dimissionRemark = dimissionRemark == null ? null : dimissionRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hro_send_detail.handle_type
     *
     * @return the value of hro_send_detail.handle_type
     *
     * @mbggenerated
     */
    public Integer getHandleType() {
        return handleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hro_send_detail.handle_type
     *
     * @param handleType the value for hro_send_detail.handle_type
     *
     * @mbggenerated
     */
    public void setHandleType(Integer handleType) {
        this.handleType = handleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hro_send_detail.operate_type
     *
     * @return the value of hro_send_detail.operate_type
     *
     * @mbggenerated
     */
    public Integer getOperateType() {
        return operateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hro_send_detail.operate_type
     *
     * @param operateType the value for hro_send_detail.operate_type
     *
     * @mbggenerated
     */
    public void setOperateType(Integer operateType) {
        this.operateType = operateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hro_send_detail.status
     *
     * @return the value of hro_send_detail.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hro_send_detail.status
     *
     * @param status the value for hro_send_detail.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hro_send_detail.hro_system_id
     *
     * @return the value of hro_send_detail.hro_system_id
     *
     * @mbggenerated
     */
    public Long getHroSystemId() {
        return hroSystemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hro_send_detail.hro_system_id
     *
     * @param hroSystemId the value for hro_send_detail.hro_system_id
     *
     * @mbggenerated
     */
    public void setHroSystemId(Long hroSystemId) {
        this.hroSystemId = hroSystemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hro_send_detail.is_deleted
     *
     * @return the value of hro_send_detail.is_deleted
     *
     * @mbggenerated
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hro_send_detail.is_deleted
     *
     * @param isDeleted the value for hro_send_detail.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hro_send_detail.create_date
     *
     * @return the value of hro_send_detail.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hro_send_detail.create_date
     *
     * @param createDate the value for hro_send_detail.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hro_send_detail.create_user_id
     *
     * @return the value of hro_send_detail.create_user_id
     *
     * @mbggenerated
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hro_send_detail.create_user_id
     *
     * @param createUserId the value for hro_send_detail.create_user_id
     *
     * @mbggenerated
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hro_send_detail.update_date
     *
     * @return the value of hro_send_detail.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hro_send_detail.update_date
     *
     * @param updateDate the value for hro_send_detail.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hro_send_detail.update_user_id
     *
     * @return the value of hro_send_detail.update_user_id
     *
     * @mbggenerated
     */
    public Long getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hro_send_detail.update_user_id
     *
     * @param updateUserId the value for hro_send_detail.update_user_id
     *
     * @mbggenerated
     */
    public void setUpdateUserId(Long updateUserId) {
        this.updateUserId = updateUserId;
    }
}